### ISSUE TITLE
"illegal operation on empty result set"

### ISSUE THREAD

**Issue by rbos** [LogBlock/LogBlock#338]
My log has been full of these messages for a few weeks; upgrading to 1.70 has not fixed it. Any advice?

Occasionally the queue will back up and I have to restart the server. It processes the queue on startup without issue and then continues.

Server: 20:13:38 [INFO] This server is running CraftBukkit version git-Spigot-1.4.6-R0.3-23-g5bcb87d (MC: 1.4.6) (Implementing API version 1.4.6-R0.4-SNAPSHOT)

RIght now it does not seem to be developing a queue but is still giving me these errors.

2013-01-28 20:16:27 [INFO] [Consumer] Queue overloaded. Size: 1032
2013-01-28 20:16:27 [SEVERE] [Consumer] SQL exception on insertion: 
java.sql.SQLException: Illegal operation on empty result set.
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
        at com.mysql.jdbc.ResultSetImpl.checkRowPos(ResultSetImpl.java:841)
        at com.mysql.jdbc.ResultSetImpl.getInt(ResultSetImpl.java:2672)
        at de.diddiz.LogBlock.Consumer$BlockRow.executeStatements(Consumer.java:479)
        at de.diddiz.LogBlock.Consumer.run(Consumer.java:294)
        at org.bukkit.craftbukkit.v1_4_6.scheduler.CraftTask.run(CraftTask.java:53)
        at org.bukkit.craftbukkit.v1_4_6.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by Brokkonaut** [comment]
I think this is fixed
