### ISSUE TITLE
Could not pass event InventoryOpenEvent to LogBlock v1.70

### ISSUE THREAD

**Issue by Bronski** [LogBlock/LogBlock#416]
The server crashed shortly after this but I don't know if it's related.  CB 2771:

17:10:40 [SEVERE] Could not pass event InventoryOpenEvent to LogBlock v1.70
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:35)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
        at org.bukkit.craftbukkit.v1_5_R3.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:549)
        at net.minecraft.server.v1_5_R3.EntityPlayer.openContainer(EntityPlayer.java:516)
        at net.minecraft.server.v1_5_R3.BlockChest.interact(SourceFile:239)
        at net.minecraft.server.v1_5_R3.PlayerInteractManager.interact(PlayerInteractManager.java:379)
        at net.minecraft.server.v1_5_R3.PlayerConnection.a(PlayerConnection.java:631)
        at net.minecraft.server.v1_5_R3.Packet15Place.handle(SourceFile:58)
        at net.minecraft.server.v1_5_R3.NetworkManager.b(NetworkManager.java:292)
        at net.minecraft.server.v1_5_R3.PlayerConnection.d(PlayerConnection.java:109)
        at net.minecraft.server.v1_5_R3.ServerConnection.b(SourceFile:35)
        at net.minecraft.server.v1_5_R3.DedicatedServerConnection.b(SourceFile:30)
        at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:581)
        at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:226)
        at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:477)
        at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:410)
        at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
Caused by: java.lang.NullPointerException
        at org.bukkit.block.DoubleChest.getWorld(DoubleChest.java:33)
        at org.bukkit.block.DoubleChest.getLocation(DoubleChest.java:29)
        at de.diddiz.util.BukkitUtils.getInventoryHolderType(BukkitUtils.java:145)
        at de.diddiz.LogBlock.listeners.ChestAccessLogging.onInventoryOpen(ChestAccessLogging.java:53)
        at sun.reflect.GeneratedMethodAccessor355.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
        ... 19 more
17:11:27 [SEVERE] net.minecraft.server.v1_5_R3.ReportedException: Ticking tile entity
17:11:27 [SEVERE]       at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:567)
17:11:27 [SEVERE]       at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:226)
17:11:27 [SEVERE]       at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:477)
17:11:27 [SEVERE]       at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:410)
17:11:27 [SEVERE]       at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
17:11:27 [SEVERE] Caused by: java.lang.NullPointerException
17:11:27 [SEVERE]       at net.minecraft.server.v1_5_R3.TileEntityHopper.addEntityItem(TileEntityHopper.java:334)
17:11:27 [SEVERE]       at net.minecraft.server.v1_5_R3.TileEntityHopper.suckInItems(TileEntityHopper.java:271)
17:11:27 [SEVERE]       at net.minecraft.server.v1_5_R3.TileEntityHopper.j(TileEntityHopper.java:181)
17:11:27 [SEVERE]       at net.minecraft.server.v1_5_R3.TileEntityHopper.h(TileEntityHopper.java:173)
17:11:27 [SEVERE]       at net.minecraft.server.v1_5_R3.World.tickEntities(World.java:1264)
17:11:27 [SEVERE]       at net.minecraft.server.v1_5_R3.WorldServer.tickEntities(WorldServer.java:480)
17:11:27 [SEVERE]       at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:563)
17:11:27 [SEVERE]       ... 4 more
17:11:27 [SEVERE] Encountered an unexpected exception ReportedException
net.minecraft.server.v1_5_R3.ReportedException: Ticking tile entity
        at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:567)
        at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:226)
        at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:477)
        at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:410)
        at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
Caused by: java.lang.NullPointerException
        at net.minecraft.server.v1_5_R3.TileEntityHopper.addEntityItem(TileEntityHopper.java:334)
        at net.minecraft.server.v1_5_R3.TileEntityHopper.suckInItems(TileEntityHopper.java:271)
        at net.minecraft.server.v1_5_R3.TileEntityHopper.j(TileEntityHopper.java:181)
        at net.minecraft.server.v1_5_R3.TileEntityHopper.h(TileEntityHopper.java:173)
        at net.minecraft.server.v1_5_R3.World.tickEntities(World.java:1264)
        at net.minecraft.server.v1_5_R3.WorldServer.tickEntities(WorldServer.java:480)
        at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:563)
        ... 4 more
17:11:27 [SEVERE] This crash report has been saved to: c:\mc.\crash-reports\crash-2013-05-18_17.11.27-server.txt

**Comment by Brokkonaut** [comment]
It was a bukkit bug that is fixed
