### ISSUE TITLE
Could not pass event InventoryCloseEvent

### ISSUE THREAD

**Issue by mibby** [LogBlock/LogBlock#456]
Logblock dev 204. http://ci.md-5.net/job/LogBlock/204

```
2013-07-20 23:54:37 [SEVERE] Could not pass event InventoryCloseEvent to LogBlock v1.70
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:30)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:478)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:463)
    at org.bukkit.craftbukkit.v1_6_R2.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:701)
    at net.minecraft.server.v1_6_R2.EntityPlayer.closeInventory(EntityPlayer.java:702)
    at net.minecraft.server.v1_6_R2.EntityHuman.l_(EntityHuman.java:159)
    at net.minecraft.server.v1_6_R2.EntityPlayer.h(EntityPlayer.java:222)
    at net.minecraft.server.v1_6_R2.PlayerConnection.a(PlayerConnection.java:345)
    at net.minecraft.server.v1_6_R2.Packet10Flying.handle(SourceFile:136)
    at org.spigotmc.netty.NettyNetworkManager.b(NettyNetworkManager.java:230)
    at net.minecraft.server.v1_6_R2.PlayerConnection.e(PlayerConnection.java:118)
    at net.minecraft.server.v1_6_R2.ServerConnection.b(SourceFile:37)
    at org.spigotmc.netty.NettyServerConnection.b(NettyServerConnection.java:125)
    at net.minecraft.server.v1_6_R2.MinecraftServer.t(MinecraftServer.java:592)
    at net.minecraft.server.v1_6_R2.DedicatedServer.t(DedicatedServer.java:239)
    at net.minecraft.server.v1_6_R2.MinecraftServer.s(MinecraftServer.java:481)
    at net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java:413)
    at net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:582)
Caused by: java.lang.NullPointerException
    at org.bukkit.block.DoubleChest.getX(DoubleChest.java:37)
    at org.bukkit.block.DoubleChest.getLocation(DoubleChest.java:29)
    at de.diddiz.util.BukkitUtils.getInventoryHolderLocation(BukkitUtils.java:192)
    at de.diddiz.LogBlock.listeners.ChestAccessLogging.onInventoryClose(ChestAccessLogging.java:44)
    at sun.reflect.GeneratedMethodAccessor150.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
    ... 19 more
```

**Comment by frymaster** [comment]
The InventoryOpenEvent bug is fixed; the InventoryCloseEvent bug has a totally different cause (which I can't yet reproduce)
