### ISSUE TITLE
4-byte unicode on signs throws SQL exception

### ISSUE THREAD

**Issue by jomo** [LogBlock/LogBlock#535]
This happened when someone put russian characters on a sign.

```
[pool-3-thread-173/ERROR]: [Consumer] SQL exception on insertion: 
java.sql.SQLException: Incorrect string value: '\xD0\xAB\xD0\xB3\xD0\xB7...' for column 'signtext' at row 1
  at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
  at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
  at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
  at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
  at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
  at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
  at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
  at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
  at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
  at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
  at de.diddiz.LogBlock.Consumer$BlockRow.executeStatements(Consumer.java:488) ~[logblock.jar:?]
  at de.diddiz.LogBlock.Consumer.run(Consumer.java:294) [logblock.jar:?]
  at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftTask.run(CraftTask.java:53) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
  at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_51]
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_51]
  at java.lang.Thread.run(Thread.java:744) [?:1.7.0_51]
```

fyi: `\xD0\xAB\xD0\xB3\xD0\xB7` = "Ыгз"
These characters have 4 bytes each (`Ы` is a single character)
Using mysqld  Ver 5.5.35-0ubuntu0.12.04.2 for debian-linux-gnu on x86_64 ((Ubuntu))

Mysql < 5.5 only supports 1-3 byte utf8 characters while MySQL >= 5.5 supports up to 4 bytes using [utf8mb4](https://dev.mysql.com/doc/refman/5.5/en/charset-unicode-utf8mb4.html).
Either require MySQL 5.5 or replace the characters with questionmarks if it's lower.

**Comment by frymaster** [comment]
Just looked into it again.  I looks like  Ыгз are all 2-byte characters (which makes sense, as there's only 6 hex values there
The character on this page (though not part of the minecraft font) causes the error
http://www.fileformat.info/info/unicode/char/1d49c/browsertest.htm

Should have a fix posted tonight. A very **late** fix, but afaik we'll still be the first block logger to support this ;)

**Comment by frymaster** [comment]
@jomo thanks for the report.  This *should* have no effect on your server, as you already made these changes.  Let me know if it's otherwise
