### ISSUE TITLE
Out of range value for column 'x' at row 1

### ISSUE THREAD

**Issue by jomo** [LogBlock/LogBlock#553]
I noticed this weird error in the logs.

```log
[pool-3-thread-110/ERROR]: [Consumer] SQL exception on insertion: 
com.mysql.jdbc.MysqlDataTruncation: Data truncation: Out of range value for column 'x' at row 1
 at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3591) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
 at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
 at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
 at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
 at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
 at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
 at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
 at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
 at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
 at de.diddiz.LogBlock.Consumer$BlockRow.executeStatements(Consumer.java:490) ~[logblock.jar:?]
 at de.diddiz.LogBlock.Consumer.run(Consumer.java:307) [logblock.jar:?]
 at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftTask.run(CraftTask.java:53) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
 at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_55]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_55]
 at java.lang.Thread.run(Thread.java:744) [?:1.7.0_55]
```

This repeated a bunch of times in the logs.

The `x` column is `mediumint(9)` (signed), meaning it can take any number between -8388608 and 8388607.    
AFAIK `Out of range value` means the inserted number must have been greater or lower than that. I've checked for records with high or low numbers, but there's nothing even close to the limit.

----

It would also be useful if SQL errors would be catched and then logged with additional info, such as location, block type and username.

**Comment by jomo** [comment]
Is this actually fixed or do people have to migrate the columns themselves (i.e. with a clean LB installation)?

**Comment by frymaster** [comment]
d'oh, I read that the last commenter's issue had been fixed and assumed.  I'll check

**Comment by qq291462491** [comment]
+1

**Comment by sfxworks** [comment]
Can you possibly apply cb5741d to 1.7.10's version?

**Comment by md-5** [comment]
No, 1.7 is years outdated.
You can update your sql db yourself

**Comment by sfxworks** [comment]
Setting everything to ints then? 

https://cdn.discordapp.com/attachments/422639882335420417/436381238597779459/unknown.png

**Comment by md-5** [comment]
Yes for the locations
