### ISSUE TITLE
ERROR]: [Consumer] SQL exception on insertion:

### ISSUE THREAD

**Issue by Max633** [LogBlock/LogBlock#555]
[00:52:47 ERROR]: [Consumer] SQL exception on insertion: 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '3394868' for key 'PRIMARY'
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_03]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[?:1.7.0_03]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.7.0_03]
at java.lang.reflect.Constructor.newInstance(Constructor.java:525) ~[?:1.7.0_03]
at com.mysql.jdbc.Util.handleNewInstance(Util.java:407) ~[spigot.jar:git-Spigot-1482]
at com.mysql.jdbc.Util.getInstance(Util.java:382) ~[spigot.jar:git-Spigot-1482]
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039) ~[spigot.jar:git-Spigot-1482]
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593) ~[spigot.jar:git-Spigot-1482]
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525) ~[spigot.jar:git-Spigot-1482]
at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986) ~[spigot.jar:git-Spigot-1482]
at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140) ~[spigot.jar:git-Spigot-1482]
at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626) ~[spigot.jar:git-Spigot-1482]
at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111) ~[spigot.jar:git-Spigot-1482]
at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407) ~[spigot.jar:git-Spigot-1482]
at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325) ~[spigot.jar:git-Spigot-1482]
at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310) ~[spigot.jar:git-Spigot-1482]
at de.diddiz.LogBlock.Consumer$BlockRow.executeStatements(Consumer.java:508) ~[LogBlock.jar:?]
at de.diddiz.LogBlock.Consumer.run(Consumer.java:307) [LogBlock.jar:?]
at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftTask.run(CraftTask.java:67) [spigot.jar:git-Spigot-1482]
at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot.jar:git-Spigot-1482]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110) [?:1.7.0_03]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603) [?:1.7.0_03]
at java.lang.Thread.run(Thread.java:722) [?:1.7.0_03]

Thanks you

**Comment by Mahagon** [comment]
Your Database seems to be corrupt.
Thats not a Logblock Bug

Try to Delete 3394868

You could also create an SQL dump of that table -> Remove the 3394868 entry drop the table and insert the SQL Dump again

**Comment by frymaster** [comment]
Corrupt DB
