### ISSUE TITLE
Could not pass event InventoryCloseEvent 

### ISSUE THREAD

**Issue by SmallSansSerif** [LogBlock/LogBlock#563]
Getting this error now on recent Spigot builds, @md-5 

Could not pass event InventoryCloseEvent to LogBlock v1.81

http://hastebin.com/xeyiyewiwo.avrasm

**Comment by mibby** [comment]
Just confirming that this still occurs with the latest spigot compile and logblock dev 256.

```
[22:09:10] [Server thread/ERROR]: Could not pass event InventoryCloseEvent to LogBlock v1.94-dev-SNAPSHOT (build #256)
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-2ec6f06-7722428]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-2ec6f06-7722428]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:838) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.EntityPlayer.closeInventory(EntityPlayer.java:787) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.EntityPlayer.t_(EntityPlayer.java:201) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.World.entityJoinedWorld(World.java:1605) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.World.g(World.java:1580) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.World.tickEntities(World.java:1425) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.WorldServer.tickEntities(WorldServer.java:597) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:783) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.NullPointerException
	at org.bukkit.block.DoubleChest.getWorld(DoubleChest.java:36) ~[spigot.jar:git-Spigot-2ec6f06-7722428]
	at org.bukkit.block.DoubleChest.getLocation(DoubleChest.java:32) ~[spigot.jar:git-Spigot-2ec6f06-7722428]
	at de.diddiz.util.BukkitUtils.getInventoryHolderLocation(BukkitUtils.java:217) ~[?:?]
	at de.diddiz.LogBlock.listeners.ChestAccessLogging.onInventoryClose(ChestAccessLogging.java:43) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor388.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-Spigot-2ec6f06-7722428]
	... 15 more
```

**Comment by frymaster** [comment]
this happens when there are three chests or more of the same type next to each other.  This is something logblock can cause happen (if a rollback/redo causes the creation of a chest next to pre-existing chests) and something I want to fix, but:

* It's by no means the only way triple chests can happen
* The fix won't remove pre-existing chests

....so it's likely that a fix won't prevent getting those errors for pre-existing problematic chests.

**Comment by mibby** [comment]
LogBlock dev 258.

```
[12:22:15] [Server thread/ERROR]: Could not pass event InventoryOpenEvent to LogBlock v1.94-dev-SNAPSHOT (build #258)
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-f928e7a-e91aed8]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-f928e7a-e91aed8]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-f928e7a-e91aed8]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-f928e7a-e91aed8]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:715) [spigot.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.EntityPlayer.openContainer(EntityPlayer.java:663) [spigot.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.BlockChest.interact(SourceFile:339) [spigot.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:496) [spigot.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:736) [spigot.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [spigot.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-f928e7a-e91aed8]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [spigot.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot.jar:git-Spigot-f928e7a-e91aed8]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.ClassCastException: org.bukkit.block.DoubleChest cannot be cast to org.bukkit.block.Chest
	at org.bukkit.block.DoubleChest.getWorld(DoubleChest.java:36) ~[spigot.jar:git-Spigot-f928e7a-e91aed8]
	at org.bukkit.block.DoubleChest.getLocation(DoubleChest.java:32) ~[spigot.jar:git-Spigot-f928e7a-e91aed8]
	at de.diddiz.util.BukkitUtils.getInventoryHolderType(BukkitUtils.java:207) ~[?:?]
	at de.diddiz.LogBlock.listeners.ChestAccessLogging.onInventoryOpen(ChestAccessLogging.java:61) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor319.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-f928e7a-e91aed8]
	... 19 more
```

**Comment by frymaster** [comment]
this is a bug thrown by bukkit when you try to call chest methods on a double chest and it turns out to be in an "impossible" state

check the location where that happened in mcedit and look for a triple chest
