### ISSUE TITLE
Error on startup if legacy version of WorldEdit installed

### ISSUE THREAD

**Issue by frymaster** [LogBlock/LogBlock#584]
We should detect this and provide a friendlier error

````
2015-02-23 10:17:15 [ERROR] Error occurred while enabling LogBlock v1.92 (Is it up to date?)
java.lang.NoSuchMethodError: com.sk89q.worldedit.WorldEdit.getEventBus()Lcom/sk89q/worldedit/util/eventbus/EventBus;
        at de.diddiz.worldedit.WorldEditLoggingHook.hook(WorldEditLoggingHook.java:52) ~[?:?]
        at de.diddiz.LogBlock.LogBlock.onEnable(LogBlock.java:120) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-e81edfc]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327) [craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-e81edfc]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-e81edfc]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:341) [craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-e81edfc]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:313) [craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-e81edfc]
        at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:394) [craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-e81edfc]
        at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:362) [craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-e81edfc]
        at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:317) [craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-e81edfc]
        at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:190) [craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-e81edfc]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:484) [craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-e81edfc]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
````

**Comment by frymaster** [comment]
Fixed in 1cb32d26ed614e14c7844922397274112bb8d985
