### ISSUE TITLE
Could not pass event PlayerInteractEvent to LogBlock v1.91

### ISSUE THREAD

**Issue by fungreenfox** [LogBlock/LogBlock#595]
[16:01:24 ERROR]: Could not pass event PlayerInteractEvent to LogBlock v1.91
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.8.jar:git-Spigot-e497721-a1ce164]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.jar:git-Spigot-e497721-a1ce164]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.jar:git-Spigot-e497721-a1ce164]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.jar:git-Spigot-e497721-a1ce164]
        at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:226) [spigot-1.8.jar:git-Spigot-e497721-a1ce164]
        at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:193) [spigot-1.8.jar:git-Spigot-e497721-a1ce164]
        at net.minecraft.server.v1_8_R1.PlayerInteractManager.a(PlayerInteractManager.java:107) [spigot-1.8.jar:git-Spigot-e497721-a1ce164]
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:588) [spigot-1.8.jar:git-Spigot-e497721-a1ce164]
        at net.minecraft.server.v1_8_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot-1.8.jar:git-Spigot-e497721-a1ce164]
        at net.minecraft.server.v1_8_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot-1.8.jar:git-Spigot-e497721-a1ce164]
        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot-1.8.jar:git-Spigot-e497721-a1ce164]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_31]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_31]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [spigot-1.8.jar:git-Spigot-e497721-a1ce164]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-e497721-a1ce164]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot-1.8.jar:git-Spigot-e497721-a1ce164]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot-1.8.jar:git-Spigot-e497721-a1ce164]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]
Caused by: java.lang.IllegalStateException: Start block missed in BlockIterator
        at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:170) ~[spigot-1.8.jar:git-Spigot-e497721-a1ce164]
        at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:233) ~[spigot-1.8.jar:git-Spigot-e497721-a1ce164]
        at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:268) ~[spigot-1.8.jar:git-Spigot-e497721-a1ce164]
        at org.bukkit.craftbukkit.v1_8_R1.entity.CraftLivingEntity.getLineOfSight(CraftLivingEntity.java:133) ~[spigot-1.8.jar:git-Spigot-e497721-a1ce164]
        at org.bukkit.craftbukkit.v1_8_R1.entity.CraftLivingEntity.getTargetBlock(CraftLivingEntity.java:159) ~[spigot-1.8.jar:git-Spigot-e497721-a1ce164]
        at de.diddiz.LogBlock.listeners.BlockBurnLogging.onExtinguish(BlockBurnLogging.java:38) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor264.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot-1.8.jar:git-Spigot-e497721-a1ce164]
        ... 17 more

CraftBukkit version git-Spigot-e497721-a1ce164 (MC: 1.8) I see i am 98 versions behind, so i dont know who is going to correct what actually.

**Comment by frymaster** [comment]
Fixed in commit 8c232b59970cc959a2a3fe10cf58f2e6ece86927 - see also issue #583
