### ISSUE TITLE
Troublesome queries with insertion into MySQL databases

### ISSUE THREAD

**Issue by jflory7** [LogBlock/LogBlock#617]
This stacktrace is continually generating in my server logs, and I am unable to figure out the cause. It's repetitive and I'm not sure if I should be severely concerned or if it's a minor issue. If more information is needed, please do not hesitate to ask!

*Server Version*: git-PaperSpigot-55b35d8-7723b90 (MC: 1.8.7)

```
[19:23:22 ERROR]: [Consumer] Troublesome query: com.zaxxer.hikari.proxy.PreparedStatementJavassistProxy@6ba268ed
[19:23:22 ERROR]: [Consumer] SQL exception on insertion: 
com.mysql.jdbc.MysqlDataTruncation: Data truncation: Out of range value for column 'x' at row 1
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3591) ~[paperspigot.jar:git-PaperSpigot-55b35d8-7723b90]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525) ~[paperspigot.jar:git-PaperSpigot-55b35d8-7723b90]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986) ~[paperspigot.jar:git-PaperSpigot-55b35d8-7723b90]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140) ~[paperspigot.jar:git-PaperSpigot-55b35d8-7723b90]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626) ~[paperspigot.jar:git-PaperSpigot-55b35d8-7723b90]
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111) ~[paperspigot.jar:git-PaperSpigot-55b35d8-7723b90]
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407) ~[paperspigot.jar:git-PaperSpigot-55b35d8-7723b90]
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325) ~[paperspigot.jar:git-PaperSpigot-55b35d8-7723b90]
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310) ~[paperspigot.jar:git-PaperSpigot-55b35d8-7723b90]
        at com.zaxxer.hikari.proxy.PreparedStatementProxy.executeUpdate(PreparedStatementProxy.java:61) ~[LogBlock.jar:?]
        at com.zaxxer.hikari.proxy.PreparedStatementJavassistProxy.executeUpdate(PreparedStatementJavassistProxy.java) ~[LogBlock.jar:?]
        at de.diddiz.LogBlock.Consumer$BlockRow.executeStatements(Consumer.java:567) ~[LogBlock.jar:?]
        at de.diddiz.LogBlock.Consumer.run(Consumer.java:339) [LogBlock.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [paperspigot.jar:git-PaperSpigot-55b35d8-7723b90]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [paperspigot.jar:git-PaperSpigot-55b35d8-7723b90]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
```

**Comment by frymaster** [comment]
On mobile right now so I can't link to the exact entry, but search for "truncation" on this page:

https://github.com/LogBlock/LogBlock/wiki/FAQ

Unfortunately the version of the database library we're currently using doesn't show the original query, but I reported that and a fix was scheduled to be released, so hopefully future versions will show the exact query that's failing

**Comment by jflory7** [comment]
@frymaster Thanks for the fast response. As far as I know, updating my database to use medium ints for x and z did resolve the problem. I have tried breaking blocks beyond those coordinates, around 500,000 on x and z axis, and nothing fired in my console.

If I notice anything else, I will reopen this issue. Thank you!
