### ISSUE TITLE
Logblock not work

### ISSUE THREAD

**Issue by agorapolis** [LogBlock/LogBlock#619]
Hello, logblock is not ok...
I have a error message in game when i send /lb tool : "mysql connection lost"

Console :

[15:54:52] [ERROR] Error occurred while enabling LogBlock v1.94-dev-SNAPSHOT (build #256) (Is it up to date?)
java.lang.IllegalArgumentException: Task cannot be null
at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[minecraft_server.jar:git-Spigot-44c59bf-8f0f4ed]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.validate(CraftScheduler.java:398) ~[minecraft_server.jar:git-Spigot-44c59bf-8f0f4ed]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:141) ~[minecraft_server.jar:git-Spigot-44c59bf-8f0f4ed]
at de.diddiz.LogBlock.LogBlock.onEnable(LogBlock.java:116) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[minecraft_server.jar:git-Spigot-44c59bf-8f0f4ed]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [minecraft_server.jar:git-Spigot-44c59bf-8f0f4ed]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [minecraft_server.jar:git-Spigot-44c59bf-8f0f4ed]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356) [minecraft_server.jar:git-Spigot-44c59bf-8f0f4ed]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [minecraft_server.jar:git-Spigot-44c59bf-8f0f4ed]
at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:418) [minecraft_server.jar:git-Spigot-44c59bf-8f0f4ed]
at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:382) [minecraft_server.jar:git-Spigot-44c59bf-8f0f4ed]
at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:337) [minecraft_server.jar:git-Spigot-44c59bf-8f0f4ed]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:256) [minecraft_server.jar:git-Spigot-44c59bf-8f0f4ed]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528) [minecraft_server.jar:git-Spigot-44c59bf-8f0f4ed]
at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]

**Comment by frymaster** [comment]
Hi,

Can you post the full startup log of your server to https://gist.github.com/ and link it please?

**Comment by frymaster** [comment]
No response
