### ISSUE TITLE
Could not pass event InventoryCloseEvent to LogBlock v1.94-dev-SNAPSHOT (build #258)

### ISSUE THREAD

**Issue by bobeeb** [LogBlock/LogBlock#624]
Server Version:
This server is running CraftBukkit version git-Spigot-f928e7a-994b2aa (MC: 1.8.7) (Implementing API version 1.8.7-R0.1-SNAPSHOT)

[19:17:54] [Server thread/ERROR]: Could not pass event InventoryCloseEvent to LogBlock v1.94-dev-SNAPSHOT (build #258)
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-f928e7a-994b2aa]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-f928e7a-994b2aa]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-f928e7a-994b2aa]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-f928e7a-994b2aa]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:838) [spigot.jar:git-Spigot-f928e7a-994b2aa]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1384) [spigot.jar:git-Spigot-f928e7a-994b2aa]
	at net.minecraft.server.v1_8_R3.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:18) [spigot.jar:git-Spigot-f928e7a-994b2aa]
	at net.minecraft.server.v1_8_R3.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:1) [spigot.jar:git-Spigot-f928e7a-994b2aa]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-f928e7a-994b2aa]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_31]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_31]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot.jar:git-Spigot-f928e7a-994b2aa]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [spigot.jar:git-Spigot-f928e7a-994b2aa]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot.jar:git-Spigot-f928e7a-994b2aa]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot.jar:git-Spigot-f928e7a-994b2aa]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot.jar:git-Spigot-f928e7a-994b2aa]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]
Caused by: java.lang.NullPointerException
	at org.bukkit.block.DoubleChest.getWorld(DoubleChest.java:36) ~[spigot.jar:git-Spigot-f928e7a-994b2aa]
	at org.bukkit.block.DoubleChest.getLocation(DoubleChest.java:32) ~[spigot.jar:git-Spigot-f928e7a-994b2aa]
	at de.diddiz.util.BukkitUtils.getInventoryHolderLocation(BukkitUtils.java:217) ~[?:?]
	at de.diddiz.LogBlock.listeners.ChestAccessLogging.onInventoryClose(ChestAccessLogging.java:43) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor172.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-f928e7a-994b2aa]
	... 16 more

got this bug also at build 256, was my last version

**Comment by bobeeb** [comment]
closed by myself :)
next time i should read the issue page before posting that this bug is allways on the radar

**Comment by frymaster** [comment]
to be clear, there is **nothing** we can do about this bug per se

It's caused when the plugin tries to look up details about chests and there turns out to be 3 in a row (a triple chest or longer)

This is arguably a Bukkit bug, but since you're not supposed to be able to create these it doesn't normally come up

It's *possible* LogBlock might be involved in the creation of these triple chests, if you do an area-limited rollback and it ends up creating chests right next to existing ones, but that's unlikely

Generally logblock is a victim of this, not a perpetrator
