### ISSUE TITLE
MariaDB - No space left on device

### ISSUE THREAD

**Issue by L4BORG** [LogBlock/LogBlock#625]
```
[21:14:22 ERROR]: [Lookup] SELECT date, replaced, type, data, playername, UUID, signtext FROM `lb-world` INNER JOIN `lb-players` USING (playerid) LEFT JOIN `lb-world-sign` USING (id) WHERE type != replaced ORDER BY date DESC, id DESC :
java.sql.SQLException: Error writing file '/tmp/MYATaZYv' (Errcode: 28 "No space left on device")
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073) ~[spigot-survival.jar:git-Spigot-6d16e64-b105298]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593) ~[spigot-survival.jar:git-Spigot-6d16e64-b105298]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525) ~[spigot-survival.jar:git-Spigot-6d16e64-b105298]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986) ~[spigot-survival.jar:git-Spigot-6d16e64-b105298]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140) ~[spigot-survival.jar:git-Spigot-6d16e64-b105298]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2620) ~[spigot-survival.jar:git-Spigot-6d16e64-b105298]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2570) ~[spigot-survival.jar:git-Spigot-6d16e64-b105298]
        at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1474) ~[spigot-survival.jar:git-Spigot-6d16e64-b105298]
        at com.zaxxer.hikari.proxy.StatementProxy.executeQuery(StatementProxy.java:99) ~[LogBlock.jar:?]
        at com.zaxxer.hikari.proxy.StatementJavassistProxy.executeQuery(StatementJavassistProxy.java) ~[LogBlock.jar:?]
        at de.diddiz.LogBlock.CommandsHandler.executeQuery(CommandsHandler.java:853) ~[LogBlock.jar:?]
        at de.diddiz.LogBlock.CommandsHandler.access$200(CommandsHandler.java:42) ~[LogBlock.jar:?]
        at de.diddiz.LogBlock.CommandsHandler$CommandLookup.run(CommandsHandler.java:474) [LogBlock.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot-survival.jar:git-Spigot-6d16e64-b105298]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot-survival.jar:git-Spigot-6d16e64-b105298]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
```

```
root@Eristoff:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        20G  6.9G   12G  38% /
devtmpfs         16G     0   16G   0% /dev
tmpfs            16G     0   16G   0% /dev/shm
tmpfs            16G  394M   16G   3% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            16G     0   16G   0% /sys/fs/cgroup
/dev/md2         90G   29G   57G  34% /home
root@Eristoff:~#
```

Any idea what caused this?

Running lastest LogBlock and latest Spigot 1.8.7.

Thanks!

**Comment by L4BORG** [comment]
```
>lb
[21:31:03 INFO]: LogBlock v1.94-dev-SNAPSHOT (build #259) by DiddiZ
[21:31:03 INFO]: Type /lb help for help
```

**Comment by frymaster** [comment]
How many rows is your ``lb-world`` database?

I actually suspect your disk was genuinely full.  That query had no time or distance restrictions on it, so it's very possibly your server was creating a temp file to hold the results, which were basically a copy of **every** row from your logging table, plus a few extra columns for player details and any signs placed

of course, the minute this query failed, it would have deleted its working data and the space would have been recovered.

Other things I've seen cause this are file permission errors (unlikely in /tmp but check it out) or running out of inodes on the disk.  In any case, this is definitely a MySQL server error, not a LogBlock error.  I don't mind keeping helping you troubleshoot so feel free to add more comments, but I'm going to close the issue just to keep things tidy (or at least stop them getting messier)

**Comment by L4BORG** [comment]
```
SELECT * FROM `lb-world` 
```

```
 Showing rows 0 - 24 (43026801 total, Query took 0.0002 seconds.)
```

Could this be caused by running only /lb world "world"

and if so, can I limit this somehow?

Thanks!

**Comment by frymaster** [comment]
yeah, ``/lb world "world"`` will give you back all block breaks anywhere since the beginning of time

you need to do something like ``/lb area 30 since 100d`` (for anything within a 30 blocks of you in any direction in the last 100 days)

**Comment by L4BORG** [comment]
Yeah I know that but I thought if there is a way to globaly limit all queries to prevent selecting too much data.

**Comment by frymaster** [comment]
Not as such.  There's options for default area and time but they only kick in if you ask for a restriction but don't supply a value
