### ISSUE TITLE
Could not pass event EntityDeathEvent

### ISSUE THREAD

**Issue by L4BORG** [LogBlock/LogBlock#626]
```
[21:22:21 ERROR]: Could not pass event EntityDeathEvent to LogBlock v1.94-dev-SNAPSHOT (build #259)
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-survival.jar:git-Spigot-6d16e64-b105298]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-survival.jar:git-Spigot-6d16e64-b105298]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-survival.jar:git-Spigot-6d16e64-b105298]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-survival.jar:git-Spigot-6d16e64-b105298]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:377) [spigot-survival.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.EntityLiving.die(EntityLiving.java:873) [spigot-survival.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:811) [spigot-survival.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.EntityBat.damageEntity(SourceFile:190) [spigot-survival.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.EntityArrow.t_(EntityArrow.java:242) [spigot-survival.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607) [spigot-survival.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.World.g(World.java:1582) [spigot-survival.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425) [spigot-survival.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) [spigot-survival.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:785) [spigot-survival.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-survival.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot-survival.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot-survival.jar:git-Spigot-6d16e64-b105298]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.NullPointerException
        at de.diddiz.LogBlock.Actor.actorFromProjectileSource(Actor.java:85) ~[?:?]
        at de.diddiz.LogBlock.Consumer.queueKill(Consumer.java:223) ~[?:?]
        at de.diddiz.LogBlock.listeners.KillLogging.onEntityDeath(KillLogging.java:39) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor261.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-survival.jar:git-Spigot-6d16e64-b105298]
        ... 17 more
```

```
>lb
[21:31:03 INFO]: LogBlock v1.94-dev-SNAPSHOT (build #259) by DiddiZ
[21:31:03 INFO]: Type /lb help for help
```

**Comment by frymaster** [comment]
looks like something (person or animal) was killed by a projectile, but the projectile source (IE who shot them) was blank

Scope of this error: that specific kill will not have been recorded. Do you know what was happening at the time? Should be easy enough to record the kill as being caused by the projectile, at least (e.g. killed by Arrow instead of killed by Skeleton)

**Comment by L4BORG** [comment]
I don't think player got killed, I think players were messing around with Bats (killing them with arrows I think, I had 70 players online so idk for sure).

**Comment by frymaster** [comment]
Thanks for the report.  This *should* fix the bug, but I haven't been able to reproduce it.  In any case, it doesn't seem to break anything new
