### ISSUE TITLE
Data truncation: Incorrect string value: '\xC4\xB0sTru...

### ISSUE THREAD

**Issue by L4BORG** [LogBlock/LogBlock#630]
```
[13:36:04 ERROR]: [Consumer] SQL exception on UPDATE `lb-players` SET lastlogin = FROM_UNIXTIME(1437996964), firstlogin = IF(firstlogin = 0, FROM_UNIXTIME(1437996964), firstlogin), ip = '/...', playername = 'ThisİsTrue' WHERE UUID = '...';:
com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect string value: '\xC4\xB0sTru...' for column 'playername' at row 1
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3591) ~[spigot-acidisland.jar:git-Spigot-f94fe8f-2642f9b]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525) ~[spigot-acidisland.jar:git-Spigot-f94fe8f-2642f9b]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986) ~[spigot-acidisland.jar:git-Spigot-f94fe8f-2642f9b]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140) ~[spigot-acidisland.jar:git-Spigot-f94fe8f-2642f9b]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2620) ~[spigot-acidisland.jar:git-Spigot-f94fe8f-2642f9b]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2570) ~[spigot-acidisland.jar:git-Spigot-f94fe8f-2642f9b]
        at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:779) ~[spigot-acidisland.jar:git-Spigot-f94fe8f-2642f9b]
        at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:622) ~[spigot-acidisland.jar:git-Spigot-f94fe8f-2642f9b]
        at com.zaxxer.hikari.proxy.StatementProxy.execute(StatementProxy.java:83) ~[LogBlock.jar:?]
        at com.zaxxer.hikari.proxy.StatementJavassistProxy.execute(StatementJavassistProxy.java) ~[LogBlock.jar:?]
        at de.diddiz.LogBlock.Consumer.run(Consumer.java:424) [LogBlock.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot-acidisland.jar:git-Spigot-f94fe8f-2642f9b]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot-acidisland.jar:git-Spigot-f94fe8f-2642f9b]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
```

using utf8_general_ci ... wth? :/

**Comment by frymaster** [comment]
Hrm, I'd thought the player name field was more restricted than that, is this an offline server?

**Comment by frymaster** [comment]
also, can you paste the results of the SQL query ``SHOW CREATE TABLE `lb-players`;`` please?

**Comment by L4BORG** [comment]
Yeah, it's "offline-server",

```
-- phpMyAdmin SQL Dump
-- version 4.4.10
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Jul 27, 2015 at 04:28 PM
-- Server version: 10.0.20-MariaDB-1~jessie-log
-- PHP Version: 5.6.9-0+deb8u1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `server_survival`
--

-- --------------------------------------------------------

--
-- Table structure for table `lb-players`
--

CREATE TABLE IF NOT EXISTS `lb-players` (
  `playerid` int(10) unsigned NOT NULL,
  `UUID` varchar(36) NOT NULL,
  `playername` varchar(32) NOT NULL,
  `firstlogin` datetime NOT NULL,
  `lastlogin` datetime NOT NULL,
  `onlinetime` int(10) unsigned NOT NULL,
  `ip` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `lb-players`
--
ALTER TABLE `lb-players`
  ADD PRIMARY KEY (`playerid`),
  ADD KEY `UUID` (`UUID`),
  ADD KEY `playername` (`playername`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `lb-players`
--
ALTER TABLE `lb-players`
  MODIFY `playerid` int(10) unsigned NOT NULL AUTO_INCREMENT;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

```

**Comment by L4BORG** [comment]
![Image](http://shrani.si/f/2X/Sx/2W4LiDcq/untitled.png)

**Comment by L4BORG** [comment]
Also IIRC (didn't hat github acc before) there is SQL injection for username filed if you run offline server and got players with names like "It'sMe".

**Comment by frymaster** [comment]
@L4BORG http://ci.md-5.net/job/LogBlock/lastBuild/ has a fix for that last issue, at least. Going to do some more tests on that first thing, because I can manually insert that into my DB with no issues. Something odd going on there

We don't currently enforce any kind of character encoding on the name field (we do on e.g. chat and sign text) because it's not supposed to need it - but it works on mine. Odd.

**Comment by L4BORG** [comment]
Thanks!

Maybe connection encoding? Since database and table are both in UTF8 and Spigot too.

with JDBC for example I would force UTF-8 encoding for connection like this:

```
connection = DriverManager.getConnection("jdbc:mysql://" + hostname + ":" + port + "/" + database + "?autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8", user, password);
```

But dunno how hikari's connection pool handle this... maybe: https://github.com/brettwooldridge/HikariCP/issues/40

**Comment by frymaster** [comment]
Easy way to check - join the server with a "normal" name, paste that name into chat, and see if the chat logging blows up

But we *do* enforce utf8 encoding on the connection, so I would expect that to work

**Comment by L4BORG** [comment]
Nope, if I paste it in chat everything is fine and it gets logged in chatlog too.

**Comment by L4BORG** [comment]
Then again...

```
UPDATE `lb-players` SET `playername` = 'ThisİsTrue' WHERE `lb-players`.`playerid` = 5; 
```

works too. o.0

**Comment by frymaster** [comment]
ok, this is weird

I hardcoded it to use 'ThisİsTrue' as the name, and got no error

![2015-07-29_20 26 24](https://cloud.githubusercontent.com/assets/426814/8968288/1073effe-3634-11e5-8702-8312856bdd8a.png)

Can you still reproduce this?

**Comment by L4BORG** [comment]
No, just tried and I can't... hm.

**Comment by frymaster** [comment]
can you paste the log from a few lines further up, showing all the lines related to that player joining the server?

**Comment by L4BORG** [comment]
```
[13:36:04] [Thread-1500/INFO]: UUID of player ThisİsTrue is abc2dd03-e4ba-3166-bc17-4e137a0ae205
[13:36:04] [Server thread/INFO]: [AcidIsland] No players/abc2dd03-e4ba-3166-bc17-4e137a0ae205.yml found. Creating it...
[13:36:04] [Server thread/INFO]: ThisİsTrue[/88.245.45.11:49857] logged in with entity id 19664733 at ([world]-1.5, 62.0, 0.5)
[13:36:04] [Craft Scheduler Thread - 5500/INFO]: [GAListener] Player: ThisİsTrue has 0 votes
[13:36:04] [pool-9-thread-1/INFO]: Creating empty config: /home/minecraft/acidisland/plugins/Essentials/userdata/abc2dd03-e4ba-3166-bc17-4e137a0ae205.yml
[13:36:04] [Craft Scheduler Thread - 5509/ERROR]: [Consumer] SQL exception on UPDATE `lb-players` SET lastlogin = FROM_UNIXTIME(1437996964), firstlogin = IF(firstlogin = 0, FROM_UNIXTIME(1437996964), firstlogin), ip = '/88.245.45.11:49857', playername = 'ThisİsTrue' WHERE UUID = 'abc2dd03-e4ba-3166-bc17-4e137a0ae205';: 
com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect string value: '\xC4\xB0sTru...' for column 'playername' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3591) ~[spigot-acidisland.jar:git-Spigot-f94fe8f-2642f9b]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525) ~[spigot-acidisland.jar:git-Spigot-f94fe8f-2642f9b]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986) ~[spigot-acidisland.jar:git-Spigot-f94fe8f-2642f9b]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140) ~[spigot-acidisland.jar:git-Spigot-f94fe8f-2642f9b]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2620) ~[spigot-acidisland.jar:git-Spigot-f94fe8f-2642f9b]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2570) ~[spigot-acidisland.jar:git-Spigot-f94fe8f-2642f9b]
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:779) ~[spigot-acidisland.jar:git-Spigot-f94fe8f-2642f9b]
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:622) ~[spigot-acidisland.jar:git-Spigot-f94fe8f-2642f9b]
	at com.zaxxer.hikari.proxy.StatementProxy.execute(StatementProxy.java:83) ~[LogBlock.jar:?]
	at com.zaxxer.hikari.proxy.StatementJavassistProxy.execute(StatementJavassistProxy.java) ~[LogBlock.jar:?]
	at de.diddiz.LogBlock.Consumer.run(Consumer.java:424) [LogBlock.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot-acidisland.jar:git-Spigot-f94fe8f-2642f9b]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot-acidisland.jar:git-Spigot-f94fe8f-2642f9b]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
[13:36:07] [Server thread/INFO]: ThisİsTrue has just earned the achievement [Taking Inventory]
[13:36:57] [Server thread/INFO]: ThisİsTrue issued server command: /island
[13:37:32] [Server thread/INFO]: ThisİsTrue has just earned the achievement [Getting Wood]
[13:37:42] [Server thread/INFO]: ThisİsTrue has just earned the achievement [Benchmarking]
```

But nvm I just found the issue.

I run multiple servers (got diff database for each server) and in database for that specific server I had collation latin1_swedish_ci for lb-players. Dunno how that get there or maybe... I've already had this problems, mariadb somehow created default databases in latin1 and logBlock would then create tables and fields with latin1... so it's my issue really, sorry :/

So I changed that into utf8_general_ci and now it's ok (upper exports and screens are from survival server... I thought I had everything in utf8_general_ci ... gotta recheck again everything now -.-).

I would still suggest enforcing UTF8:
https://dev.mysql.com/doc/refman/5.0/en/charset-table.html

Anyway thx for help and sorry for bothering since this is kinda my fault.

**Comment by frymaster** [comment]
>I would still suggest enforcing UTF8:

Yeah, that was going to be one of the takeaways from this regardless of your issue.  We do enforce UTF8 (actually, UTF8mb4 if the database supports it) for player chat and sign text, but we never bothered for names because we thought the Mojang name restrictions would always apply

**Comment by frymaster** [comment]
LB will ensure player names are stored in UTF8(mb4) by default, and will upgrade pre-existing tables. Thanks for report.
