### ISSUE TITLE
Tons of errors in console

### ISSUE THREAD

**Issue by McLive** [LogBlock/LogBlock#654]
```
[17:54:47] [Craft Scheduler Thread - 2290/ERROR]: [Consumer] Troublesome query: com.mysql.jdbc.JDBC4PreparedStatement@5392f1f6: INSERT INTO `lb-sky` (date, playerid, replaced, type, data, x, y, z) VALUES(FROM_UNIXTIME(1451753687), 46814, 0, 8, 1, -2982, 72, -3609)
[17:54:47] [Craft Scheduler Thread - 2290/ERROR]: [Consumer] SQL exception on insertion:
com.mysql.jdbc.exceptions.jdbc4.MySQLDataException: '2.191519547E9' in column '1' is outside valid range for the datatype INTEGER.
        at sun.reflect.GeneratedConstructorAccessor159.newInstance(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.7.0_60]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[?:1.7.0_60]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407) ~[paperspigot-1.8.8.jar:git-PaperSpigot-25a137f-53fac9f]
        at com.mysql.jdbc.Util.getInstance(Util.java:382) ~[paperspigot-1.8.8.jar:git-PaperSpigot-25a137f-53fac9f]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1025) ~[paperspigot-1.8.8.jar:git-PaperSpigot-25a137f-53fac9f]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987) ~[paperspigot-1.8.8.jar:git-PaperSpigot-25a137f-53fac9f]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982) ~[paperspigot-1.8.8.jar:git-PaperSpigot-25a137f-53fac9f]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927) ~[paperspigot-1.8.8.jar:git-PaperSpigot-25a137f-53fac9f]
        at com.mysql.jdbc.ResultSetImpl.throwRangeException(ResultSetImpl.java:7970) ~[paperspigot-1.8.8.jar:git-PaperSpigot-25a137f-53fac9f]
        at com.mysql.jdbc.ResultSetImpl.parseIntAsDouble(ResultSetImpl.java:7199) ~[paperspigot-1.8.8.jar:git-PaperSpigot-25a137f-53fac9f]
        at com.mysql.jdbc.ResultSetImpl.getInt(ResultSetImpl.java:2702) ~[paperspigot-1.8.8.jar:git-PaperSpigot-25a137f-53fac9f]
        at de.diddiz.LogBlock.Consumer$BlockRow.executeStatements(Consumer.java:532) ~[LogBlock.jar:?]
        at de.diddiz.LogBlock.Consumer.run(Consumer.java:325) [LogBlock.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [paperspigot-1.8.8.jar:git-PaperSpigot-25a137f-53fac9f]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [paperspigot-1.8.8.jar:git-PaperSpigot-25a137f-53fac9f]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_60]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_60]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_60]
```
It still logs blocks but its annoying as hell.

**Comment by McLive** [comment]
Fixed at https://github.com/McLive/LogBlock/commit/817b66f6b989d450438b00cab22b7e7b1f0b0d69
