### ISSUE TITLE
Can't rollback animal kills

### ISSUE THREAD

**Issue by 151baccardi** [LogBlock/LogBlock#656]
[02:27:25 INFO]: LogBlockQuestioner version 0.02
[02:27:25 INFO]: Ask questions for LogBlock.
[02:27:25 INFO]: Author: DiddiZ
[02:27:25 INFO]: LogBlock version 1.94
[02:27:25 INFO]: Logs blocks.
[02:27:25 INFO]: Website: http://dev.bukkit.org/server-mods/logblock/
[02:27:25 INFO]: Authors: DiddiZ, md_5, ammar2 and frymaster

Issue:
Column replaced not found (but it's there in the database) !!
4th column.
    4   replaced    tinyint(3)      UNSIGNED

/lb rb kills
Returns:

[02:16:42 ERROR]: [Rollback] SELECT x, y, z FROM `lb-claims-kills` WHERE date > date_sub(now(), INTERVAL 300 MINUTE) ORDER BY date DESC, id DESC :
java.sql.SQLException: Column 'replaced' not found.
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073) ~[spigot-R0.1-db6de129199.jar:git-Spigot-5f38d38-18fbb24]
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987) ~[spigot-R0.1-db6de129199.jar:git-Spigot-5f38d38-18fbb24]
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982) ~[spigot-R0.1-db6de129199.jar:git-Spigot-5f38d38-18fbb24]
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927) ~[spigot-R0.1-db6de129199.jar:git-Spigot-5f38d38-18fbb24]
at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1144) ~[spigot-R0.1-db6de129199.jar:git-Spigot-5f38d38-18fbb24]
at com.mysql.jdbc.ResultSetImpl.getInt(ResultSetImpl.java:2813) ~[spigot-R0.1-db6de129199.jar:git-Spigot-5f38d38-18fbb24]
at com.zaxxer.hikari.proxy.ResultSetJavassistProxy.getInt(ResultSetJavassistProxy.java) ~[LogBlock.jar:?]
at de.diddiz.LogBlock.CommandsHandler$CommandRollback.run(CommandsHandler.java:674) [LogBlock.jar:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot-R0.1-db6de129199.jar:git-Spigot-5f38d38-18fbb24]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot-R0.1-db6de129199.jar:git-Spigot-5f38d38-18fbb24]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]

/lb lookup kills works.

logKillsLevel: ANIMALS

and kills set to logged in the individual enabled worlds files...

I would seriously like to roll back griefers who kill animals.
Thanks

Config:
# 
# banPermission: mcbans.ban.local

tools:
  tool:
    defaultEnabled: true
    mode: LOOKUP
    aliases:
    - t
    params: area 0 all sum none limit 15 desc silent
    leftClickBehavior: NONE
    item: 270
    rightClickBehavior: TOOL
    permissionDefault: OP
    canDrop: true
  toolblock:
    params: area 0 all sum none limit 15 desc silent
    permissionDefault: OP
    rightClickBehavior: BLOCK
    item: 280
    mode: LOOKUP
    canDrop: true
    defaultEnabled: true
    aliases:
    - tb
    leftClickBehavior: TOOL
mysql:
  user: user*
  port: 3306
  password: password*
  host: host*
  database: database*
logging:
  hiddenBlocks:
- 0
  logCreeperExplosionsAsPlayerWhoTriggeredThese: false
  logPlayerInfo: true
  ignoredChat:
- /register
- /login
  logEnvironmentalKills: true
  hiddenPlayers: []
  logKillsLevel: ANIMALS
  consumer:
  timePerRun: 900
  useBukkitScheduler: true
  forceToProcessAtLeast: 500
  queueWarningSize: 2000
  fireCustomEvents: false
  delayBetweenRuns: 2
  lookup:
  dateFormat: MM-dd HH:mm:ss
  linesLimit: 1500
  defaultTime: 300 minutes
  defaultDist: 20
  linesPerPage: 30
  safety:
  id:
    check: true
  questioner:
  askClearLogs: true
  askRollbacks: true
  askRedos: true
  askClearLogAfterRollback: true
  askRollbackAfterBan: true
  banPermission: mcbans.ban.local
  loggedWorlds:
  - world
  - extreme
  - claims
  - ASkyBlock
    clearlog:
    enableAutoClearLog: false
    auto:
- world "world" before 1000 days all
- world "world" player lavaflow waterflow leavesdecay before 14 days all
- world world_nether before 1000 days all
- world world_nether player lavaflow before 14 days all
  autoClearLogDelay: 24h
  dumpDeletedLog: false
  rollback:
  replaceAnyway:
- 8
- 9
- 10
- 11
- 51
  maxArea: 500
  dontRollback:
- 10
- 11
- 46
- 51
  maxTime: 1365 days
  version: '1.94'
  debug: false

**Comment by frymaster** [comment]
Right now LB doesn't have the facility to rollback kills at all. I'm not sure if that will be added, but at the very least it shouldn't be as annoying about it

**Comment by Brokkonaut** [comment]
Added in the latest build
