### ISSUE TITLE
Spigot 1.9 MySql error

### ISSUE THREAD

**Issue by WindofFreedom** [LogBlock/LogBlock#660]
Plugin does not work on Spigot 1.9:
```
[12:33:04 INFO]: [LogBlock] Loading LogBlock v1.10.0-dev-SNAPSHOT (build #271)
[12:33:04 INFO]: [LogBlock] Connecting to c3_mc@jdbc:mysql://localhost:3306/c3_mc...
[12:33:04 INFO]: LogBlock-Connection-Pool - is starting.
[12:33:05 INFO]: LogBlock-Connection-Pool - is closing down.
[12:33:05 ERROR]: [LogBlock] Error while fetching connection:
com.zaxxer.hikari.pool.PoolInitializationException: Exception during pool initialization: Could not create connection to database server.
        at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:581) ~[LogBlock.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:152) ~[LogBlock.jar:?]
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96) ~[LogBlock.jar:?]
        at de.diddiz.util.MySQLConnectionPool.getConnection(MySQLConnectionPool.java:38) ~[LogBlock.jar:?]
        at de.diddiz.LogBlock.LogBlock.getConnection(LogBlock.java:263) [LogBlock.jar:?]
        at de.diddiz.LogBlock.LogBlock.onLoad(LogBlock.java:63) [LogBlock.jar:?]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugins(CraftServer.java:301) [spigot.jar:git-Spigot-dd155ed-31caee5]
        at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:201) [spigot.jar:git-Spigot-dd155ed-31caee5]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigot.jar:git-Spigot-dd155ed-31caee5]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_74]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_74]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_74]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_74]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[spigot.jar:git-Spigot-dd155ed-31caee5]
        at com.mysql.jdbc.Util.getInstance(Util.java:387) ~[spigot.jar:git-Spigot-dd155ed-31caee5]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919) ~[spigot.jar:git-Spigot-dd155ed-31caee5]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898) ~[spigot.jar:git-Spigot-dd155ed-31caee5]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887) ~[spigot.jar:git-Spigot-dd155ed-31caee5]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:862) ~[spigot.jar:git-Spigot-dd155ed-31caee5]
        at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2331) ~[spigot.jar:git-Spigot-dd155ed-31caee5]
        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2084) ~[spigot.jar:git-Spigot-dd155ed-31caee5]
        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:795) ~[spigot.jar:git-Spigot-dd155ed-31caee5]
        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44) ~[spigot.jar:git-Spigot-dd155ed-31caee5]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_74]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_74]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_
74]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_74]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[spigot.jar:git-Spigot-dd155ed-31caee5]
        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400) ~[spigot.jar:git-Spigot-dd155ed-31caee5]
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:327) ~[spigot.jar:git-Spigot-dd155ed-31ca
ee5]
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95) ~[LogBlock.jar:?]
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101) ~[LogBlock.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.addConnection(HikariPool.java:496) ~[LogBlock.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:565) ~[LogBlock.jar:?]
        ... 9 more
Caused by: java.lang.NullPointerException
        at com.mysql.jdbc.Buffer.<init>(Buffer.java:50) ~[spigot.jar:git-Spigot-dd155ed-31caee5]
        at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1669) ~[spigot.jar:git-Spigot-dd155ed-31caee5]
        at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1207) ~[spigot.jar:git-Spigot-dd155ed-31caee5]
        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2254) ~[spigot.jar:git-Spigot-dd155ed-31caee5]
        at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2285) ~[spigot.jar:git-Spigot-dd155ed-31caee5]
        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2084) ~[spigot.jar:git-Spigot-dd155ed-31caee5]
        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:795) ~[spigot.jar:git-Spigot-dd155ed-31caee5]
        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44) ~[spigot.jar:git-Spigot-dd155ed-31caee5]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_74]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_74]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_74]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_74]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[spigot.jar:git-Spigot-dd155ed-31caee5]
        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400) ~[spigot.jar:git-Spigot-dd155ed-31caee5]
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:327) ~[spigot.jar:git-Spigot-dd155ed-31caee5]
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95) ~[LogBlock.jar:?]
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101) ~[LogBlock.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.addConnection(HikariPool.java:496) ~[LogBlock.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:565) ~[LogBlock.jar:?]
        ... 9 more
```

**Comment by frymaster** [comment]
Does this happen with Spigot 1.8 or CraftBukkit 1.9? If it's working on either of those can you post logs?

**Comment by WindofFreedom** [comment]
Plugin work good on Spigot 1.8, but in Spigot and CraftBukkit 1.9 it does not work

**Comment by sgdc3** [comment]
@frymaster It's an issue with HikariCP, every plugin that use it (AuthMeReloaded, LogBlock, etc..) is unable to connect to the database. Maybe 1.9 introduced some security related restrictions, Idk ;(

**Comment by frymaster** [comment]
@sgdc3 Spigot did ship a much newer version of the Connector/J library. It's something to do with that and certain versions/configurations of mysql

**Comment by sgdc3** [comment]
@frymaster My friend @ljacqu found a workaroud: https://github.com/Xephi/AuthMeReloaded/issues/575#issuecomment-192639031

**Comment by Platinteufel** [comment]
Would be awesome if this could be solved without needing a new startup flag ^^

**Comment by frymaster** [comment]
@sgdc3 Yeah, that turned out to be a typo in the guy's config, and the only bug was the confusing error message  - it's possible that's a fix, but if so that's almost coincidental

@WindofFreedom - can you post the full startup logs for the working and not working logs please at https://gist.github.com/ and try adding `-Dfile.encoding=UTF-8` to the java options of your server please (the bit before the -jar)

**Comment by WindofFreedom** [comment]
https://gist.github.com/WindofFreedom/5dcaf922b4b4f6d4b1f3 - 1.8.8 working
https://gist.github.com/WindofFreedom/b4fecc169e6fc06f2bf3 - 1.9 not working

-Dfile.encoding=UTF-8 already is in my start.sh

**Comment by sgdc3** [comment]
Without it?

**Comment by WindofFreedom** [comment]
work fine without it

**Comment by sgdc3** [comment]
Wtf! O_O

**Comment by WindofFreedom** [comment]
I don't know, but it work without this parametr

**Comment by WindofFreedom** [comment]
I have used -Dfile.encoding=UTF instead of -Dfile.encoding=UTF-8. Sorry

**Comment by frymaster** [comment]
with that parameter, does it work on 1.9?

**Comment by WindofFreedom** [comment]
yes
