### ISSUE TITLE
Can't roll back Animal Kills

### ISSUE THREAD

**Issue by 151baccardi** [LogBlock/LogBlock#663]
Never worked 100% with any version.

/lb rb kills etc etc

returns this error in 1.6, 1.7 and 1.8 !!! All versions of logbock !!

Column replaced not found !!!

Logblock does not roll back kills no matter what I do.

[09:28:41 INFO]: Fahrferknukken issued server command: /lb rollback kills area 10 since 3h [09:28:41 ERROR]: [Rollback] SELECT x, y, z FROM `lb-claims-kills` WHERE x in (-2401,-2400,-2399,-2398,-2397,-2396,-2395,-2394,-2393,-2392,-2391,-2390,-2389,-2388,-2387,-2386,-2385,-2384,-2383) AND y in (55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73) AND z in (-765,-764,-763,-762,-761,-760,-759,-758,-757,-756,-755,-754,-753,-752,-751,-750,-749,-748,-747) AND date > date_sub(now(), INTERVAL 180 MINUTE) ORDER BY date DESC, id DESC : java.sql.SQLException: Column 'replaced' not found. at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:959) [spigot-R0.1-5d4e372f482-99f22a5c59d-db1761e3c9d.jar:git-Spigot-5d4e372-99f22a5] at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898) [spigot-R0.1-5d4e372f482-99f22a5c59d-db1761e3c9d.jar:git-Spigot-5d4e372-99f22a5] at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887) [spigot-R0.1-5d4e372f482-99f22a5c59d-db1761e3c9d.jar:git-Spigot-5d4e372-99f22a5] at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:862) [spigot-R0.1-5d4e372f482-99f22a5c59d-db1761e3c9d.jar:git-Spigot-5d4e372-99f22a5] at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1076) [spigot-R0.1-5d4e372f482-99f22a5c59d-db1761e3c9d.jar:git-Spigot-5d4e372-99f22a5] at com.mysql.jdbc.ResultSetImpl.getInt(ResultSetImpl.java:2580) [spigot-R0.1-5d4e372f482-99f22a5c59d-db1761e3c9d.jar:git-Spigot-5d4e372-99f22a5] at com.zaxxer.hikari.proxy.HikariResultSetProxy.getInt(HikariResultSetProxy.java) [LogBlock.jar:?] at de.diddiz.LogBlock.CommandsHandler$CommandRollback.run(CommandsHandler.java:674) [LogBlock.jar:?] at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-R0.1-5d4e372f482-99f22a5c59d-db1761e3c9d.jar:git-Spigot-5d4e372-99f22a5] at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot-R0.1-5d4e372f482-99f22a5c59d-db1761e3c9d.jar:git-Spigot-5d4e372-99f22a5] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_73] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_73] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]

**Comment by alcadel** [comment]
I have to up this because I've the same issue here :(

**Comment by frymaster** [comment]
Going to close this in favour of the older bug report #656
