### ISSUE TITLE
Logblock out od date...but not?

### ISSUE THREAD

**Issue by StuddedExpandable** [LogBlock/LogBlock#668]
Basically says it all in the title, here is the stacktrace:

`
   at net.skycraftmc.PluginManager.PluginManagerPlugin.onCommand(PluginManagerPlugin.java:287) [PluginManager.jar:?]
         at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot188.jar:git-Spigot-db6de12-d3e0b6f]
         at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot188.jar:git-Spigot-db6de12-d3e0b6f]
         at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot188.jar:git-Spigot-db6de12-d3e0b6f]
         at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot188.jar:git-Spigot-db6de12-d3e0b6f]
         at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot188.jar:git-Spigot-db6de12-d3e0b6f]
         at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot188.jar:git-Spigot-db6de12-d3e0b6f]
         at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot188.jar:git-Spigot-db6de12-d3e0b6f]
         at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot188.jar:git-Spigot-db6de12-d3e0b6f]
         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
         at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
         at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot188.jar:git-Spigot-db6de12-d3e0b6f]
         at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot188.jar:git-Spigot-db6de12-d3e0b6f]
         at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot188.jar:git-Spigot-db6de12-d3e0b6f]
         at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot188.jar:git-Spigot-db6de12-d3e0b6f]
         at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot188.jar:git-Spigot-db6de12-d3e0b6f]
         at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
 >`

Thanks,
Panda

**Comment by frymaster** [comment]
Logblock does not appear in that stacktrace, why do you think this is a Logblock error?

**Comment by StuddedExpandable** [comment]
Apologises, I have resolved the problem.e
