### ISSUE TITLE
LogBlock error: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player

### ISSUE THREAD

**Issue by Wicstar** [LogBlock/LogBlock#671]
Hello, I keep getting this error spamming my log:
[18:03:14] [Craft Scheduler Thread - 60/WARN]: Exception in thread "Craft Scheduler Thread - 60" [18:03:14] [Craft Scheduler Thread - 60/WARN]: org.apache.commons.lang.UnhandledException: Plugin LogBlock v1.94 generated an exception while executing task 12 at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56) at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at java.lang.Thread.run(Unknown Source) Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player; at de.diddiz.LogBlock.Metrics.postPlugin(Metrics.java:324) at de.diddiz.LogBlock.Metrics.access$400(Metrics.java:46) at de.diddiz.LogBlock.Metrics$1.run(Metrics.java:212) at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) ... 3 more

I loaded LogBlock through the BeastNode Control Panel
I am using 1.9.2

LogBlock is working properly so far apart from that issue.
Any help, thank you ?

**Comment by md-5** [comment]
http://ci.md-5.net/job/LogBlock/

**Comment by Wicstar** [comment]
Thanks it worked !  Apparently they are using an older version. I thought it was the latest one !
