### ISSUE TITLE
What did i do wrong... if i did...

### ISSUE THREAD

**Issue by MrKiller01** [LogBlock/LogBlock#674]
I eventually got sick of people telling me that they did not destroy this or that.... so i could eventually undo a lot with the backup, but when worldedit does not fully support 1.10 anymore i had to change my tactics, this plugin would be an option. I installed on my server SQL, no, not Mysql or anything else, just the real deal, SQL. I tested the connection to the database i setup, and put those data in the config.yml  that belongs to Logblock and restarted the server..... This i retrieved from the log:
`[16:20:58] [Server thread/INFO]: [LogBlock] Loading LogBlock v1.10.0
[16:20:58] [Server thread/INFO]: [LogBlock] Connecting to logblock@jdbc:mysql://STORAGE-SR5\SQLMC:3306/minecraft...
[16:20:58] [Server thread/INFO]: LogBlock-Connection-Pool - is starting.
[16:20:58] [Server thread/INFO]: LogBlock-Connection-Pool - is closing down.
[16:20:58] [Server thread/ERROR]: [LogBlock] Error while fetching connection: 
com.zaxxer.hikari.pool.PoolInitializationException: Exception during pool initialization: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
    at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:581) ~[LogBlock.jar:?]
    at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:152) ~[LogBlock.jar:?]
    at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96) ~[LogBlock.jar:?]
    at de.diddiz.util.MySQLConnectionPool.getConnection(MySQLConnectionPool.java:38) ~[LogBlock.jar:?]
    at de.diddiz.LogBlock.LogBlock.getConnection(LogBlock.java:263) [LogBlock.jar:?]
    at de.diddiz.LogBlock.LogBlock.onLoad(LogBlock.java:63) [LogBlock.jar:?]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:302) [spigot.jar:git-Spigot-e50d38c-02f4218]
    at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:202) [spigot.jar:git-Spigot-e50d38c-02f4218]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:539) [spigot.jar:git-Spigot-e50d38c-02f4218]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_91]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_91]
    at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_91]
    at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[spigot.jar:git-Spigot-e50d38c-02f4218]
    at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:983) ~[spigot.jar:git-Spigot-e50d38c-02f4218]
    at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:339) ~[spigot.jar:git-Spigot-e50d38c-02f4218]
    at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2252) ~[spigot.jar:git-Spigot-e50d38c-02f4218]
    at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2285) ~[spigot.jar:git-Spigot-e50d38c-02f4218]
    at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2084) ~[spigot.jar:git-Spigot-e50d38c-02f4218]
    at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:795) ~[spigot.jar:git-Spigot-e50d38c-02f4218]
    at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44) ~[spigot.jar:git-Spigot-e50d38c-02f4218]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_91]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_91]
    at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_91]
    at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[spigot.jar:git-Spigot-e50d38c-02f4218]
    at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400) ~[spigot.jar:git-Spigot-e50d38c-02f4218]
    at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:327) ~[spigot.jar:git-Spigot-e50d38c-02f4218]
    at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95) ~[LogBlock.jar:?]
    at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101) ~[LogBlock.jar:?]
    at com.zaxxer.hikari.pool.HikariPool.addConnection(HikariPool.java:496) ~[LogBlock.jar:?]
    at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:565) ~[LogBlock.jar:?]
    ... 9 more
Caused by: java.net.UnknownHostException: STORAGE-SR5\SQLMC
    at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[?:1.8.0_91]
    at java.net.InetAddress$2.lookupAllHostAddr(Unknown Source) ~[?:1.8.0_91]
    at java.net.InetAddress.getAddressesFromNameService(Unknown Source) ~[?:1.8.0_91]
    at java.net.InetAddress.getAllByName0(Unknown Source) ~[?:1.8.0_91]
    at java.net.InetAddress.getAllByName(Unknown Source) ~[?:1.8.0_91]
    at java.net.InetAddress.getAllByName(Unknown Source) ~[?:1.8.0_91]
    at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:191) ~[spigot.jar:git-Spigot-e50d38c-02f4218]
    at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:298) ~[spigot.jar:git-Spigot-e50d38c-02f4218]
    at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2252) ~[spigot.jar:git-Spigot-e50d38c-02f4218]
    at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2285) ~[spigot.jar:git-Spigot-e50d38c-02f4218]
    at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2084) ~[spigot.jar:git-Spigot-e50d38c-02f4218]
    at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:795) ~[spigot.jar:git-Spigot-e50d38c-02f4218]
    at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44) ~[spigot.jar:git-Spigot-e50d38c-02f4218]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_91]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_91]
    at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_91]
    at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[spigot.jar:git-Spigot-e50d38c-02f4218]
    at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400) ~[spigot.jar:git-Spigot-e50d38c-02f4218]
    at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:327) ~[spigot.jar:git-Spigot-e50d38c-02f4218]
    at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95) ~[LogBlock.jar:?]
    at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101) ~[LogBlock.jar:?]
    at com.zaxxer.hikari.pool.HikariPool.addConnection(HikariPool.java:496) ~[LogBlock.jar:?]
    at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:565) ~[LogBlock.jar:?]
    ... 9 more
`

**Comment by alekso56** [comment]
Logblock fails to get an connection to STORAGE-SR5\SQLMC , are you sure this is a real ip/domain?
Im pretty sure it won't accept computer names without host entries.

**Comment by MrKiller01** [comment]
Just to tell that the Minecraft server and the sql server reside on the same machine. As i tested the connection with a simple UDL file, wheras i can check if the connection at user level (on the server) will get established, it worked on the server itself, so i thought that any other proces running as administrator on my Windows2012 server is enough to let this local game plugin work... I did not test before from my gamepc, but as you asked, i had to check and no, that did not work. So, do i have to put the private ip adres of the server there?

**Comment by MrKiller01** [comment]
I went over it again, yes, on the server it works and beyond it i can't get the connection.... I am not that good with SQL, i know of the basics, and as far as i know there has to be no public access to this SQL database.

**Comment by alekso56** [comment]
if the server is on the same machine just use 127.0.0.1 as the ip..
and no, the SQL database won't need to be accessible outside the server. >_>

**Comment by MrKiller01** [comment]
Gonna try this tomorrow

**Comment by MrKiller01** [comment]
And two days later i did test a lot, the database called Minecraft is made, then i had to let the server know that its dns server was himself and not the other old one, 10.11.20.1 was old server and 10.11.30.1 is new server. I've done nslookup but only got ip adres and error. I used more plugins (Logblock and autorank) to see if they successfully connect, but no they didn't. Server name, with database name and without, username, with and without a password, ipadres of server with and without database name but nothing worked. It sees a database but then it says can't connect. So i think there should be more study from my side to at first try to connect to the database and make changes in it before i pursue more plugin material integrated in SQL. So thanks for helping, but i am stuck right now... Maybe at a later time i'll reopen my focus on the SQL server.

**Comment by polymetric1** [comment]
I know this is really old, but it's still open, so here goes:
I created a minecraft server on a digitalocean droplet (dedicated). I created a second droplet for mysql (you can also use mariadb or percona). However, mysql only opens a port on 127.0.0.1 by default. If you bound to the server's public IP, anyone could log in with the password, and your connection is unencrypted (unless you use SSL). to quickly get around this, set up ssh port forwarding. simply generate an ssh key, put the private key on your minecraft server, put the public key in `user@your_database_server`'s `authorized_keys` file, and run this ssh command on the minecraft server: `ssh -L 3306:localhost:3306 user@your_database_server`. This is how I set up a dedicated separate SQL server, as setting up one on the same server as spigot was taking up too much memory. you can set up a swap file following the directions here, though (digitalocean doesn't enable swap by default): https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04

**Comment by Brokkonaut** [comment]
java.net.UnknownHostException: STORAGE-SR5\SQLMC

The hostname could not be found. This is caused by an incorrect config.
