### ISSUE TITLE
Could not pass event InventoryCloseEvent

### ISSUE THREAD

**Issue by mibby** [LogBlock/LogBlock#681]
Logblock dev 274

```
[10:03:03] [Server thread/ERROR]: Could not pass event InventoryCloseEvent to LogBlock v1.10.1-SNAPSHOT (build #274)
org.bukkit.event.EventException
    at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.10.2.jar:git-Paper-819]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.10.2.jar:git-Paper-819]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.10.2.jar:git-Paper-819]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.10.2.jar:git-Paper-819]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.10.2.jar:git-Paper-819]
    at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:873) [patched_1.10.2.jar:git-Paper-819]
    at net.minecraft.server.v1_10_R1.EntityPlayer.closeInventory(EntityPlayer.java:866) [patched_1.10.2.jar:git-Paper-819]
    at net.minecraft.server.v1_10_R1.EntityPlayer.m(EntityPlayer.java:221) [patched_1.10.2.jar:git-Paper-819]
    at net.minecraft.server.v1_10_R1.World.entityJoinedWorld(World.java:1738) [patched_1.10.2.jar:git-Paper-819]
    at net.minecraft.server.v1_10_R1.World.g(World.java:1713) [patched_1.10.2.jar:git-Paper-819]
    at net.minecraft.server.v1_10_R1.WorldServer.l(WorldServer.java:666) [patched_1.10.2.jar:git-Paper-819]
    at net.minecraft.server.v1_10_R1.World.tickEntities(World.java:1496) [patched_1.10.2.jar:git-Paper-819]
    at net.minecraft.server.v1_10_R1.WorldServer.tickEntities(WorldServer.java:643) [patched_1.10.2.jar:git-Paper-819]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:859) [patched_1.10.2.jar:git-Paper-819]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-819]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725) [patched_1.10.2.jar:git-Paper-819]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624) [patched_1.10.2.jar:git-Paper-819]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: java.lang.NullPointerException
    at de.diddiz.LogBlock.listeners.ChestAccessLogging.onInventoryClose(ChestAccessLogging.java:45) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor526.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.10.2.jar:git-Paper-819]
    ... 17 more
```

**Comment by mibby** [comment]
Still happening as of commit https://github.com/LogBlock/LogBlock/commit/1ce92e1d3fdb46cc8af97f6326f9b9e8231716a3
```
[07:37:24] [Server thread/ERROR]: Could not pass event InventoryCloseEvent to LogBlock v1.12-SNAPSHOT (build #282)
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1320]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1320]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1320]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [patched_1.12.2.jar:git-Paper-1320]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) [patched_1.12.2.jar:git-Paper-1320]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:932) [patched_1.12.2.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.EntityPlayer.closeInventory(EntityPlayer.java:962) [patched_1.12.2.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.EntityPlayer.B_(EntityPlayer.java:281) [patched_1.12.2.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1771) [patched_1.12.2.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.World.h(World.java:1741) [patched_1.12.2.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.WorldServer.l(WorldServer.java:698) [patched_1.12.2.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1528) [patched_1.12.2.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:675) [patched_1.12.2.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:913) [patched_1.12.2.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1320]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.lang.NullPointerException
	at de.diddiz.LogBlock.listeners.ChestAccessLogging.onInventoryClose(ChestAccessLogging.java:45) ~[LogBlock.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor429.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1320]
	... 17 more
```

**Comment by Brokkonaut** [comment]
Should be fixed
