### ISSUE TITLE
Server crash related to the Consumer

### ISSUE THREAD

**Issue by JamieSinn** [LogBlock/LogBlock#689]
Stacktrace:
http://pastie.org/pastes/10985820/text?key=qeqhll1a4xgaqphvcsaq

` Recent tasks from 1772770-1772800{LogBlock:de.diddiz.LogBlock.Consumer@1772801,LogBlock:de.diddiz.LogBlock.Consumer@1772803,LogBlock:de.diddiz.LogBlock.Consumer@1772805,LogBlock:de.diddiz.LogBlock.Consumer@1772807,LogBlock:de.diddiz.LogBlock.Consumer@1772809,BuycraftX:net.buycraft.plugin.execution.strategy.PostCompletedCommandsTask@1772809,BungeeTabListPlus:codecrafter47.bungeetablistplus.bukkitbridge.BukkitBridge$$Lambda$42/381379811@1772809,LogBlock:de.diddiz.LogBlock.Consumer@1772811,LogBlock:de.diddiz.LogBlock.Consumer@1772813,LogBlock:de.diddiz.LogBlock.Consumer@1772815,LogBlock:de.diddiz.LogBlock.Consumer@1772817,LogBlock:de.diddiz.LogBlock.Consumer@1772819,LogBlock:de.diddiz.LogBlock.Consumer@1772821,LogBlock:de.diddiz.LogBlock.Consumer@1772823,LogBlock:de.diddiz.LogBlock.Consumer@1772825,LogBlock:de.diddiz.LogBlock.Consumer@1772827,LogBlock:de.diddiz.LogBlock.Consumer@1772829,BuycraftX:net.buycraft.plugin.execution.strategy.PostCompletedCommandsTask@1772829,BungeeTabListPlus:codecrafter47.bungeetablistplus.bukkitbridge.BukkitBridge$$Lambda$42/381379811@1772829,}`

`Time: 12/26/16 8:28 PM
Description: Exception ticking world

java.util.NoSuchElementException
	at java.util.TreeMap.key(Unknown Source)
	at java.util.TreeMap.firstKey(Unknown Source)
	at java.util.TreeSet.first(Unknown Source)
	at org.bukkit.craftbukkit.v1_11_R1.util.HashTreeSet.first(HashTreeSet.java:114)
	at net.minecraft.server.v1_11_R1.WorldServer.a(WorldServer.java:697)
	at net.minecraft.server.v1_11_R1.WorldServer.doTick(WorldServer.java:250)
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:790)
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.TreeMap.key(Unknown Source)
	at java.util.TreeMap.firstKey(Unknown Source)
	at java.util.TreeSet.first(Unknown Source)
	at org.bukkit.craftbukkit.v1_11_R1.util.HashTreeSet.first(HashTreeSet.java:114)
	at net.minecraft.server.v1_11_R1.WorldServer.a(WorldServer.java:697)
	at net.minecraft.server.v1_11_R1.WorldServer.doTick(WorldServer.java:250)

-- Affected level --
Details:
	Level name: end
	All players: 4 total; [EntityPlayer['ThomasVerth'/5052407, l='end', x=-38.82, y=63.00, z=-2095.06](ThomasVerth at -38.81605362750392,63.0,-2095.0559443622005), EntityPlayer['ClarinetPhoenix'/5696727, l='end', x=-993.81, y=28.15, z=-133.94](ClarinetPhoenix at -993.8097228316836,28.146606204866764,-133.94126378238693), EntityPlayer['rockboy2000'/5993338, l='end', x=-1088.30, y=20.00, z=2441.70](rockboy2000 at -1088.300000011921,20.0,2441.699999988079), EntityPlayer['Kick_Me_1235'/5997724, l='end', x=-1097.06, y=25.00, z=2415.35](Kick_Me_1235 at -1097.06023633132,25.00133597911215,2415.3517395426834)]
	Chunk stats: ServerChunkCache: 271 Drop: 0
	Level seed: -1768624432087943788
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (13,59,0), Chunk: (at 13,3,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 30926712 game time, 30926712 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:790)
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
	at java.lang.Thread.run(Unknown Source)`

From digging into it, looks like this async task is doing something wrong

https://github.com/LogBlock/LogBlock/blob/4195995ca99b4434ac38caf25a97571dfa46d847/src/main/java/de/diddiz/LogBlock/LogBlock.java#L116

@andrewkm
@md-5

**Comment by md-5** [comment]
I don't think there is any indication from this that logblock is doing something wrong
