### ISSUE TITLE
MySQL out of range exception logging a block greater than int max value

### ISSUE THREAD

**Issue by NovaBlastHD** [LogBlock/LogBlock#695]
When a player tries to place a block greater than MySQL's max int value this throws a MySQL out of range exception. For example, if you teleported far away and placed a block this would throw a MySQL out of range exception.

Error:
`[14:44:24] [Timer-1/ERROR]: [Consumer] Troublesome query: HikariProxyPreparedStatement@1829031557 wrapping com.mysql.jdbc.PreparedStatement@7acfe05c: INSERT INTO `lb-world` (date, playerid, replaced, type, data, x, y, z) VALUES(FROM_UNIXTIME(1497638664), 56, 2, 0, 0, -29999966, 65, -29999951)
[14:44:24] [Timer-1/ERROR]: [Consumer] SQL exception on insertion: 
java.sql.BatchUpdateException: Data truncation: Out of range value for column 'x' at row 2
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_131]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_131]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at com.mysql.jdbc.Util.getInstance(Util.java:387) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1160) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at com.mysql.jdbc.PreparedStatement.executeBatchedInserts(PreparedStatement.java:1582) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1248) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:959) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128) ~[hikari-2.6.1.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java) ~[hikari-2.6.1.jar:?]
	at de.diddiz.LogBlock.Consumer$MultiBlockChangeRow.executeStatements(Consumer.java:969) ~[LogBlock.jar:?]
	at de.diddiz.LogBlock.Consumer.run(Consumer.java:633) [LogBlock.jar:?]
	at java.util.TimerThread.mainLoop(Timer.java:555) [?:1.8.0_131]
	at java.util.TimerThread.run(Timer.java:505) [?:1.8.0_131]
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Out of range value for column 'x' at row 2
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3868) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2550) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5094) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at com.mysql.jdbc.PreparedStatement.executeBatchedInserts(PreparedStatement.java:1543) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	... 8 more`

**Comment by md-5** [comment]
Theres an FAQ article about changing your column sizes,
The default is smaller for optimisation/ legacy reasons.

**Comment by NovaBlastHD** [comment]
Thanks md
