### ISSUE TITLE
NullPointerException: null on lookup.

### ISSUE THREAD

**Issue by mibby** [LogBlock/LogBlock#696]
Compiled as of https://github.com/LogBlock/LogBlock/commit/80de6eb38335528c20062c5e76e13ad4bf5e4b74

```
[10:49:05] [Craft Scheduler Thread - 118/ERROR]: [Lookup] SELECT date, replaced, type, data, playername, UUID, signtext, itemtype, itemamount, itemdata FROM `lb-world` INNER JOIN `lb-players` USING (playerid) LEFT JOIN `lb-world-sign` USING (id) LEFT JOIN `lb-world-chest` USING (id) WHERE x = -15674 AND y = 155 AND z = -1834 ORDER BY date DESC, id DESC LIMIT 15: 
java.lang.NullPointerException: null
	at de.diddiz.LogBlock.QueryParams.getTitle(QueryParams.java:243) ~[LogBlock.jar:?]
	at de.diddiz.LogBlock.CommandsHandler$CommandLookup.run(CommandsHandler.java:475) [LogBlock.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) [patched_1.12.jar:git-Paper-1133]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.jar:git-Paper-1133]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.jar:git-Paper-1133]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by mibby** [comment]
Compiled as of https://github.com/LogBlock/LogBlock/commit/ba8c1281e3609b0ad8dde2d5ad176b94f0ce902d

```
[17:18:43] [Craft Scheduler Thread - 196/ERROR]: [Lookup] SELECT date, replaced, type, data, playername, UUID, signtext, itemtype, itemamount, itemdata FROM `lb-world` INNER JOIN `lb-players` USING (playerid) LEFT JOIN `lb-world-sign` USING (id) LEFT JOIN `lb-world-chest` USING (id) WHERE x = 7283 AND y = 66 AND z = 13147 ORDER BY date DESC, id DESC LIMIT 15: 
java.lang.NullPointerException: null
	at de.diddiz.LogBlock.QueryParams.getTitle(QueryParams.java:243) ~[LogBlock.jar:?]
	at de.diddiz.LogBlock.CommandsHandler$CommandLookup.run(CommandsHandler.java:475) [LogBlock.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) [patched_1.12.jar:git-Paper-1143]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.jar:git-Paper-1143]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.jar:git-Paper-1143]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```
