### ISSUE TITLE
MySQLSyntaxErrorException

### ISSUE THREAD

**Issue by mibby** [LogBlock/LogBlock#702]
@md-5 RE: https://github.com/LogBlock/LogBlock/commit/72851ca52f44b1e0cb1c683e77ddcd0c5a299640

Using MariaDB for MySQL database. Updated LogBlock from dev 276 to 279.
```
[20:38:06] [Server thread/INFO]: [LogBlock] Loading LogBlock v1.12-SNAPSHOT (build #279)
[20:38:06] [Server thread/INFO]: [LogBlock] Connecting to <censored>..
[20:38:06] [Server thread/INFO]: LogBlock-Connection-Pool - Started.
[20:38:06] [Server thread/INFO]: Updating tables to 1.12.0 ...
[20:38:06] [Server thread/ERROR]: [Updater] Error: 
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'VARCHAR(256) NOT NULL' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_144]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_144]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_144]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[patched_1.12.1.jar:git-Paper-1190]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[patched_1.12.1.jar:git-Paper-1190]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943) ~[patched_1.12.1.jar:git-Paper-1190]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973) ~[patched_1.12.1.jar:git-Paper-1190]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909) ~[patched_1.12.1.jar:git-Paper-1190]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527) ~[patched_1.12.1.jar:git-Paper-1190]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680) ~[patched_1.12.1.jar:git-Paper-1190]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2490) ~[patched_1.12.1.jar:git-Paper-1190]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2448) ~[patched_1.12.1.jar:git-Paper-1190]
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845) ~[patched_1.12.1.jar:git-Paper-1190]
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:745) ~[patched_1.12.1.jar:git-Paper-1190]
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95) ~[Guilds-1.8.4-BETA-all.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[Guilds-1.8.4-BETA-all.jar:?]
	at de.diddiz.LogBlock.Updater.update(Updater.java:395) [LogBlock.jar:?]
	at de.diddiz.LogBlock.LogBlock.onLoad(LogBlock.java:76) [LogBlock.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:310) [patched_1.12.1.jar:git-Paper-1190]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:223) [patched_1.12.1.jar:git-Paper-1190]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.1.jar:git-Paper-1190]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

**Comment by mibby** [comment]
It apparently doesn't connect to the sql database and just queues new tasks until it crashes the server too when it can't update the tables. Going to downgrade since the updater breaks things if lb-chat table doesn't exist (due to having chat logs disabled).

```
[23:11:39] [Craft Scheduler Thread - 434/WARN]: [LogBlock] Plugin LogBlock v1.12-SNAPSHOT (build #279) generated an exception while executing task 105
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method) ~[?:1.8.0_144]
	at java.lang.Thread.start(Thread.java:717) ~[?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957) ~[?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1367) ~[?:1.8.0_144]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) ~[?:1.8.0_144]
	at com.zaxxer.hikari.pool.HikariPool.addBagItem(HikariPool.java:298) ~[?:?]
	at com.zaxxer.hikari.util.ConcurrentBag.borrow(ConcurrentBag.java:166) ~[?:?]
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:163) ~[?:?]
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145) ~[?:?]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:99) ~[?:?]
	at de.diddiz.util.MySQLConnectionPool.getConnection(MySQLConnectionPool.java:38) ~[?:?]
	at de.diddiz.LogBlock.LogBlock.getConnection(LogBlock.java:263) ~[?:?]
	at de.diddiz.LogBlock.Consumer.run(Consumer.java:569) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.1.jar:git-Paper-1190]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.1.jar:git-Paper-1190]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.1.jar:git-Paper-1190]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```
```
[23:11:39] [LogBlock-Connection-Pool housekeeper/WARN]: LogBlock-Connection-Pool - Thread starvation or clock leap detected (housekeeper delta=2m38s479ms391µs340ns).
[23:11:39] [pool-16-thread-27/WARN]: Exception in thread "pool-16-thread-27" 
[23:11:39] [pool-16-thread-27/WARN]: java.lang.OutOfMemoryError: unable to create new native thread
[23:11:39] [pool-16-thread-27/WARN]: 	at java.lang.Thread.start0(Native Method)
[23:11:39] [pool-16-thread-27/WARN]: 	at java.lang.Thread.start(Thread.java:717)
[23:11:39] [pool-16-thread-27/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957)
[23:11:39] [pool-16-thread-27/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1025)
[23:11:39] [pool-16-thread-27/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[23:11:39] [pool-16-thread-27/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[23:11:39] [pool-16-thread-27/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```
```
[23:09:01] [Paper Watchdog Thread/ERROR]: ------------------------------
[23:09:01] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[23:09:01] [Paper Watchdog Thread/ERROR]: 	PID: 18 | Suspended: false | Native: false | State: RUNNABLE
[23:09:01] [Paper Watchdog Thread/ERROR]: 	Stack:
[23:09:01] [Paper Watchdog Thread/ERROR]: 		java.lang.Object.hashCode(Native Method)
[23:09:01] [Paper Watchdog Thread/ERROR]: 		java.util.HashMap.hash(HashMap.java:338)
[23:09:01] [Paper Watchdog Thread/ERROR]: 		java.util.HashMap.put(HashMap.java:611)
[23:09:01] [Paper Watchdog Thread/ERROR]: 		java.lang.Thread.getAllStackTraces(Thread.java:1615)
[23:09:01] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_12_R1.CraftCrashReport.call(CraftCrashReport.java:30)
[23:09:01] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_12_R1.CrashReportSystemDetails.a(SourceFile:78)
[23:09:01] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_12_R1.CrashReport.h(CrashReport.java:128)
[23:09:01] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_12_R1.CrashReport.<init>(CrashReport.java:35)
[23:09:01] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:685)
[23:09:01] [Paper Watchdog Thread/ERROR]: 		java.lang.Thread.run(Thread.java:748)
[23:09:01] [Paper Watchdog Thread/ERROR]: ------------------------------
```

```
	Line 3109: [22:14:58] [Craft Scheduler Thread - 179/ERROR]: [LogBlock] MySQL connection lost
	Line 3119: [22:15:28] [Craft Scheduler Thread - 179/ERROR]: [LogBlock] MySQL connection lost
	Line 3136: [22:15:45] [Craft Scheduler Thread - 1556/ERROR]: [LogBlock] MySQL connection lost
	Line 3143: [22:15:58] [Craft Scheduler Thread - 179/ERROR]: [LogBlock] MySQL connection lost
	Line 3145: [22:16:03] [Craft Scheduler Thread - 1753/ERROR]: [LogBlock] MySQL connection lost
	Line 3148: [22:16:07] [Craft Scheduler Thread - 1786/ERROR]: [LogBlock] MySQL connection lost
	Line 3154: [22:16:23] [Craft Scheduler Thread - 1960/ERROR]: [LogBlock] MySQL connection lost
	Line 3156: [22:16:26] [Craft Scheduler Thread - 1978/ERROR]: [LogBlock] MySQL connection lost
	Line 3157: [22:16:28] [Craft Scheduler Thread - 179/ERROR]: [LogBlock] MySQL connection lost
	Line 3158: [22:16:28] [Craft Scheduler Thread - 1998/ERROR]: [LogBlock] MySQL connection lost
	Line 3175: [22:16:58] [Craft Scheduler Thread - 179/ERROR]: [LogBlock] MySQL connection lost
	Line 3189: [22:17:28] [Craft Scheduler Thread - 179/ERROR]: [LogBlock] MySQL connection lost
	Line 3214: [22:17:58] [Craft Scheduler Thread - 179/ERROR]: [LogBlock] MySQL connection lost
	Line 3215: [22:17:58] [Craft Scheduler Thread - 179/INFO]: [Consumer] Queue overloaded. Size: 1011
	Line 3227: [22:18:28] [Craft Scheduler Thread - 179/ERROR]: [LogBlock] MySQL connection lost
	Line 3228: [22:18:28] [Craft Scheduler Thread - 179/INFO]: [Consumer] Queue overloaded. Size: 1210
	Line 3245: [22:18:58] [Craft Scheduler Thread - 179/ERROR]: [LogBlock] MySQL connection lost
	Line 3246: [22:18:58] [Craft Scheduler Thread - 179/INFO]: [Consumer] Queue overloaded. Size: 1360
	Line 3261: [22:19:28] [Craft Scheduler Thread - 179/ERROR]: [LogBlock] MySQL connection lost
	Line 3262: [22:19:28] [Craft Scheduler Thread - 179/INFO]: [Consumer] Queue overloaded. Size: 1458
	Line 3263: [22:19:58] [Craft Scheduler Thread - 179/ERROR]: [LogBlock] MySQL connection lost
	Line 3264: [22:19:58] [Craft Scheduler Thread - 179/INFO]: [Consumer] Queue overloaded. Size: 1721
	Line 3278: [22:20:28] [Craft Scheduler Thread - 179/ERROR]: [LogBlock] MySQL connection lost
	Line 3279: [22:20:28] [Craft Scheduler Thread - 179/INFO]: [Consumer] Queue overloaded. Size: 1949
	Line 3293: [22:20:53] [Craft Scheduler Thread - 4940/INFO]: [GrandExchange] Updating Guide Prices
	Line 3299: [22:20:58] [Craft Scheduler Thread - 179/ERROR]: [LogBlock] MySQL connection lost
	Line 3300: [22:20:58] [Craft Scheduler Thread - 179/INFO]: [Consumer] Queue overloaded. Size: 2181
	Line 3314: [22:21:28] [Craft Scheduler Thread - 179/ERROR]: [LogBlock] MySQL connection lost
	Line 3315: [22:21:28] [Craft Scheduler Thread - 179/INFO]: [Consumer] Queue overloaded. Size: 2332
	Line 3346: [22:21:58] [Craft Scheduler Thread - 179/ERROR]: [LogBlock] MySQL connection lost
	Line 3347: [22:21:58] [Craft Scheduler Thread - 179/INFO]: [Consumer] Queue overloaded. Size: 2532
	Line 3362: [22:22:28] [Craft Scheduler Thread - 179/ERROR]: [LogBlock] MySQL connection lost
	Line 3363: [22:22:28] [Craft Scheduler Thread - 179/INFO]: [Consumer] Queue overloaded. Size: 2796
	Line 3376: [22:22:58] [Craft Scheduler Thread - 179/ERROR]: [LogBlock] MySQL connection lost
	Line 3377: [22:22:58] [Craft Scheduler Thread - 179/INFO]: [Consumer] Queue overloaded. Size: 3105
	Line 3388: [22:23:16] [Craft Scheduler Thread - 6067/ERROR]: [LogBlock] MySQL connection lost
	Line 3389: [22:23:17] [Craft Scheduler Thread - 6082/ERROR]: [LogBlock] MySQL connection lost
	Line 3390: [22:23:18] [Craft Scheduler Thread - 6085/ERROR]: [LogBlock] MySQL connection lost
	Line 3391: [22:23:18] [Craft Scheduler Thread - 6084/ERROR]: [LogBlock] MySQL connection lost
	Line 3392: [22:23:19] [Craft Scheduler Thread - 6099/ERROR]: [LogBlock] MySQL connection lost
	Line 3393: [22:23:19] [Craft Scheduler Thread - 6104/ERROR]: [LogBlock] MySQL connection lost
	Line 3397: [22:23:20] [Craft Scheduler Thread - 6114/ERROR]: [LogBlock] MySQL connection lost
	Line 3398: [22:23:21] [Craft Scheduler Thread - 6113/ERROR]: [LogBlock] MySQL connection lost
	Line 3399: [22:23:21] [Craft Scheduler Thread - 6124/ERROR]: [LogBlock] MySQL connection lost
	Line 3400: [22:23:21] [Craft Scheduler Thread - 6128/ERROR]: [LogBlock] MySQL connection lost
	Line 3401: [22:23:22] [Craft Scheduler Thread - 6125/ERROR]: [LogBlock] MySQL connection lost
	Line 3403: [22:23:22] [Craft Scheduler Thread - 6137/ERROR]: [LogBlock] MySQL connection lost
	Line 3404: [22:23:22] [Craft Scheduler Thread - 6136/ERROR]: [LogBlock] MySQL connection lost
	Line 3406: [22:23:25] [Craft Scheduler Thread - 6161/ERROR]: [LogBlock] MySQL connection lost
	Line 3407: [22:23:25] [Craft Scheduler Thread - 6173/ERROR]: [LogBlock] MySQL connection lost
	Line 3408: [22:23:26] [Craft Scheduler Thread - 6180/ERROR]: [LogBlock] MySQL connection lost
	Line 3409: [22:23:26] [Craft Scheduler Thread - 6176/ERROR]: [LogBlock] MySQL connection lost
	Line 3410: [22:23:26] [Craft Scheduler Thread - 6183/ERROR]: [LogBlock] MySQL connection lost
	Line 3411: [22:23:27] [Craft Scheduler Thread - 6182/ERROR]: [LogBlock] MySQL connection lost
	Line 3412: [22:23:27] [Craft Scheduler Thread - 6190/ERROR]: [LogBlock] MySQL connection lost
	Line 3413: [22:23:28] [Craft Scheduler Thread - 6203/ERROR]: [LogBlock] MySQL connection lost
	Line 3414: [22:23:28] [Craft Scheduler Thread - 179/ERROR]: [LogBlock] MySQL connection lost
	Line 3415: [22:23:28] [Craft Scheduler Thread - 179/INFO]: [Consumer] Queue overloaded. Size: 3327
	Line 3416: [22:23:28] [Craft Scheduler Thread - 6201/ERROR]: [LogBlock] MySQL connection lost
	Line 3417: [22:23:28] [Craft Scheduler Thread - 6204/ERROR]: [LogBlock] MySQL connection lost
	Line 3418: [22:23:28] [Craft Scheduler Thread - 6209/ERROR]: [LogBlock] MySQL connection lost
	Line 3419: [22:23:28] [Craft Scheduler Thread - 6210/ERROR]: [LogBlock] MySQL connection lost
	Line 3420: [22:23:30] [Craft Scheduler Thread - 6228/ERROR]: [LogBlock] MySQL connection lost
	Line 3423: [22:23:30] [Craft Scheduler Thread - 6236/ERROR]: [LogBlock] MySQL connection lost
	Line 3427: [22:23:39] [Craft Scheduler Thread - 6314/ERROR]: [LogBlock] MySQL connection lost
	Line 3428: [22:23:39] [Craft Scheduler Thread - 6322/ERROR]: [LogBlock] MySQL connection lost
	Line 3429: [22:23:39] [Craft Scheduler Thread - 6320/ERROR]: [LogBlock] MySQL connection lost
```
Too long to even upload the crash log or console crash output to a paste site. Created 32,285 scheduler threads.
http://paste.ubuntu.com/25310735/
