### ISSUE TITLE
NullPointerException in Consumer

### ISSUE THREAD

**Issue by Bobbbe** [LogBlock/LogBlock#718]
Hello,
I have another little problem since a few days, I installed the 'build # 19'
to see if that would correct the problem but it does not change anything.
If you know where it comes from, it would be well appreciated.
Here's what I see in the console.

[21:13:00] [Logblock-Consumer/ERROR]: [LogBlock] [Consumer] Could not insert entries!

java.lang.NullPointerException: null

	at de.diddiz.LogBlock.Consumer$ChatRow.process(Consumer.java:857) ~[LogBlock.jar:?]

	at de.diddiz.LogBlock.Consumer.run(Consumer.java:487) [LogBlock.jar:?]

**Comment by Brokkonaut** [comment]
Please try build # 21

**Comment by Bobbbe** [comment]
ok thank you, version # 21 seems to have solved the problem, I'll know more today, but now I've got this-
[Logblock-Consumer / WARN]: [LogBlock] [Consumer] Failed to add player

This seems to appear only with new players.

**Comment by Brokkonaut** [comment]
Can you have a look at your database if this (Your server reached 65000 players) might be the cause: https://github.com/LogBlock/LogBlock/wiki/FAQ#logblock-your-server-reached-65000-players-

**Comment by Bobbbe** [comment]
I checked, I am very far from the 65000 (the server is 1 year old) but I found something else.
In the database, there are tables that are not created.
(lb-world), (lb-world-chest) and (lb-world-sign) these tables contain the columns, (data, date, id, playerid, replaced, type, x, y, z, signtext and others) and the index.
I have other tables (lb-world-blocks) (lb-world-chestdata) (lb-world-kills) (lb-world-state)
the tables are present on the old map but not on the news that I just created.
Yet players arrive on an old map to their connection!
I'm going to put version '' # 19 '' back to see if the problem persists.

**Comment by Brokkonaut** [comment]
The different table names are normal, the documentation for that is just a bit outdated. But I have no idea why it is not able to add new players to the lb-players table. The code for that was not changed for years..

**Comment by Bobbbe** [comment]
Error

Requête SQL : Documentation

SELECT MAX(playerid) FROM lb-players
 LIMIT 0, 25 

MySQL a répondu: Documentation
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-players
LIMIT 0, 25' at line 1

**Comment by Bobbbe** [comment]
I'm rotten with '' phpmyadmin ''
I give you the passwords and '' ID '' if you want :)

**Comment by Bobbbe** [comment]
1061 max playerid !! i can change this ?

**Comment by Bobbbe** [comment]
![screen](https://user-images.githubusercontent.com/42454593/45580747-b94df580-b862-11e8-8ff8-9ef2b4fca6a3.png)

**Comment by Brokkonaut** [comment]
No, thats fine - Its the maximum currently assigned player id. I just wanted to know if the player id might be the cause. I will try to add some debug code to logblock to see whats going wrong there

**Comment by Bobbbe** [comment]
![screen2](https://user-images.githubusercontent.com/42454593/45580799-442ef000-b863-11e8-8778-7234eb27abf7.png)

**Comment by Brokkonaut** [comment]
Please try build # 23 - It should create some debug output when adding a player to the database fails.

For the old (1.12) database:
Generally upgrading an old database is possible, but if it upgrades all new data would be lost, so I would not recommend to do it now,

**Comment by Bobbbe** [comment]
I installed version 23 everything looks good but there is no new player at the moment (it's a French server and I'm from quebec canada, so I'm alone at night) so I'll have to wait tomorrow to check or if you come on the server it will do the job. play.freebuildminecraft.com

**Comment by Bobbbe** [comment]
[03:54:40] [Server thread/INFO]: Brokkonaut a rejoint la partie!

[03:54:40] [Server thread/INFO]: [Novice] Brokkonaut has made the advancement [Isn't It Iron Pick]

[03:54:40] [Server thread/INFO]: [Novice] Brokkonaut has made the advancement [Suit Up]

[03:54:40] [Server thread/INFO]: [WarpSystem] Got a player > Searching...

[03:54:44] [Server thread/INFO]: [AdvancedAchievements] Player Brokkonaut received the achievement: connect_1 (Good Choice)

[03:54:50] [Server thread/INFO]: [WarpSystem] Did not find a BungeeCord > Ignore GlobalWarps

[03:55:01] [Server thread/INFO]: [Server] hi

[03:55:03] [Async Chat Thread - #0/INFO]: [MapNormal]-[Novice]   Brokkonaut : hi

[03:55:03] [Logblock-Consumer/WARN]: [LogBlock] [Consumer] Failed to add player Brokkonaut

[03:55:03] [Logblock-Consumer/WARN]: [LogBlock] [Consumer-Debug] Query 1: INSERT IGNORE INTO `lb-players` (playername,UUID) SELECT 'Brokkonaut','06d29950-2262-474c-acd6-fcab8e632ae1' FROM `lb-players` WHERE NOT EXISTS (SELECT NULL FROM `lb-players` WHERE UUID = '06d29950-2262-474c-acd6-fcab8e632ae1') LIMIT 1;

[03:55:03] [Logblock-Consumer/WARN]: [LogBlock] [Consumer-Debug] Query 1 - Result: 0

[03:55:03] [Logblock-Consumer/WARN]: [LogBlock] [Consumer-Debug] Query 2: SELECT playerid FROM `lb-players` WHERE UUID = '06d29950-2262-474c-acd6-fcab8e632ae1'

[03:55:17] [Logblock-Consumer/WARN]: [LogBlock] [Consumer] Failed to add player Brokkonaut

[03:55:17] [Logblock-Consumer/WARN]: [LogBlock] [Consumer-Debug] Query 1: INSERT IGNORE INTO `lb-players` (playername,UUID) SELECT 'Brokkonaut','06d29950-2262-474c-acd6-fcab8e632ae1' FROM `lb-players` WHERE NOT EXISTS (SELECT NULL FROM `lb-players` WHERE UUID = '06d29950-2262-474c-acd6-fcab8e632ae1') LIMIT 1;

[03:55:17] [Logblock-Consumer/WARN]: [LogBlock] [Consumer-Debug] Query 1 - Result: 0

[03:55:17] [Logblock-Consumer/WARN]: [LogBlock] [Consumer-Debug] Query 2: SELECT playerid FROM `lb-players` WHERE UUID = '06d29950-2262-474c-acd6-fcab8e632ae1'

[03:55:19] [Server thread/INFO]: [@: Spread 1 players around 0.5, 0.5 with an average distance of 0.00 blocks apart]

[03:55:20] [Server thread/INFO]: [Server] ok im copy paste log

[03:55:28] [Logblock-Consumer/WARN]: [LogBlock] [Consumer] Failed to add player Brokkonaut

[03:55:28] [Logblock-Consumer/WARN]: [LogBlock] [Consumer-Debug] Query 1: INSERT IGNORE INTO `lb-players` (playername,UUID) SELECT 'Brokkonaut','06d29950-2262-474c-acd6-fcab8e632ae1' FROM `lb-players` WHERE NOT EXISTS (SELECT NULL FROM `lb-players` WHERE UUID = '06d29950-2262-474c-acd6-fcab8e632ae1') LIMIT 1;

[03:55:28] [Logblock-Consumer/WARN]: [LogBlock] [Consumer-Debug] Query 1 - Result: 0

[03:55:28] [Logblock-Consumer/WARN]: [LogBlock] [Consumer-Debug] Query 2: SELECT playerid FROM `lb-players` WHERE UUID = '06d29950-2262-474c-acd6-fcab8e632ae1'

[03:55:32] [Logblock-Consumer/WARN]: [LogBlock] [Consumer] Failed to add player Brokkonaut

[03:55:32] [Logblock-Consumer/WARN]: [LogBlock] [Consumer-Debug] Query 1: INSERT IGNORE INTO `lb-players` (playername,UUID) SELECT 'Brokkonaut','06d29950-2262-474c-acd6-fcab8e632ae1' FROM `lb-players` WHERE NOT EXISTS (SELECT NULL FROM `lb-players` WHERE UUID = '06d29950-2262-474c-acd6-fcab8e632ae1') LIMIT 1;

[03:55:32] [Logblock-Consumer/WARN]: [LogBlock] [Consumer-Debug] Query 1 - Result: 0

[03:55:32] [Logblock-Consumer/WARN]: [LogBlock] [Consumer-Debug] Query 2: SELECT playerid FROM `lb-players` WHERE UUID = '06d29950-2262-474c-acd6-fcab8e632ae1'

[03:55:35] [Async Chat Thread - #0/INFO]: [MapNormal]-[Novice]   Brokkonaut : ok

[03:55:35] [Logblock-Consumer/WARN]: [LogBlock] [Consumer] Failed to add player Brokkonaut

[03:55:35] [Logblock-Consumer/WARN]: [LogBlock] [Consumer-Debug] Query 1: INSERT IGNORE INTO `lb-players` (playername,UUID) SELECT 'Brokkonaut','06d29950-2262-474c-acd6-fcab8e632ae1' FROM `lb-players` WHERE NOT EXISTS (SELECT NULL FROM `lb-players` WHERE UUID = '06d29950-2262-474c-acd6-fcab8e632ae1') LIMIT 1;

[03:55:35] [Logblock-Consumer/WARN]: [LogBlock] [Consumer-Debug] Query 1 - Result: 0

[03:55:35] [Logblock-Consumer/WARN]: [LogBlock] [Consumer-Debug] Query 2: SELECT playerid FROM `lb-players` WHERE UUID = '06d29950-2262-474c-acd6-fcab8e632ae1'

**Comment by Bobbbe** [comment]
[04:11:28] [Logblock-Consumer/WARN]: [LogBlock] [Consumer] Failed to add player Brokkonaut

[04:11:28] [Logblock-Consumer/WARN]: [LogBlock] [Consumer-Debug] Query 1: INSERT IGNORE INTO `lb-players` (playername,UUID) SELECT 'Brokkonaut','06d29950-2262-474c-acd6-fcab8e632ae1' FROM `lb-players` WHERE NOT EXISTS (SELECT NULL FROM `lb-players` WHERE UUID = '06d29950-2262-474c-acd6-fcab8e632ae1') LIMIT 1

[04:11:28] [Logblock-Consumer/WARN]: [LogBlock] [Consumer-Debug] Query 1 - Result: 0

[04:11:28] [Logblock-Consumer/WARN]: [LogBlock] [Consumer-Debug] Query 2: SELECT playerid FROM `lb-players` WHERE UUID = '06d29950-2262-474c-acd6-fcab8e632ae1'

[04:11:29] [Server thread/INFO]: Brokkonaut[/46.91.24.131:55470] logged in with entity id 1205 at ([MapNormal]-4863.986675008227, 66.0, 1586.280404390533)

[04:11:29] [Server thread/INFO]: Brokkonaut a rejoint la partie!

[04:11:29] [Server thread/INFO]: [ShopChest] Initialized 190 Shops

[04:11:29] [Server thread/INFO]: [WarpSystem] Got a player > Searching...

[04:11:33] [Logblock-Consumer/WARN]: [LogBlock] [Consumer] Failed to add player Brokkonaut

[04:11:33] [Logblock-Consumer/WARN]: [LogBlock] [Consumer-Debug] Query 1: INSERT IGNORE INTO `lb-players` (playername,UUID) SELECT 'Brokkonaut','06d29950-2262-474c-acd6-fcab8e632ae1' FROM `lb-players` WHERE NOT EXISTS (SELECT NULL FROM `lb-players` WHERE UUID = '06d29950-2262-474c-acd6-fcab8e632ae1') LIMIT 1

[04:11:33] [Logblock-Consumer/WARN]: [LogBlock] [Consumer-Debug] Query 1 - Result: 0

[04:11:33] [Logblock-Consumer/WARN]: [LogBlock] [Consumer-Debug] Query 2: SELECT playerid FROM `lb-players` WHERE UUID = '06d29950-2262-474c-acd6-fcab8e632ae1'

[04:11:34] [Logblock-Consumer/WARN]: [LogBlock] [Consumer] Failed to add player Brokkonaut

[04:11:34] [Logblock-Consumer/WARN]: [LogBlock] [Consumer-Debug] Query 1: INSERT IGNORE INTO `lb-players` (playername,UUID) SELECT 'Brokkonaut','06d29950-2262-474c-acd6-fcab8e632ae1' FROM `lb-players` WHERE NOT EXISTS (SELECT NULL FROM `lb-players` WHERE UUID = '06d29950-2262-474c-acd6-fcab8e632ae1') LIMIT 1

[04:11:34] [Logblock-Consumer/WARN]: [LogBlock] [Consumer-Debug] Query 1 - Result: 0

[04:11:34] [Logblock-Consumer/WARN]: [LogBlock] [Consumer-Debug] Query 2: SELECT playerid FROM `lb-players` WHERE UUID = '06d29950-2262-474c-acd6-fcab8e632ae1'

**Comment by Bobbbe** [comment]
[04:12:15] [Async Chat Thread - #0/INFO]: [MapNormal]-[Novice]   Brokkonaut : is the error still there?

[04:12:15] [Logblock-Consumer/WARN]: [LogBlock] [Consumer] Failed to add player Brokkonaut

[04:12:15] [Logblock-Consumer/WARN]: [LogBlock] [Consumer-Debug] Query 1: INSERT IGNORE INTO `lb-players` (playername,UUID) SELECT 'Brokkonaut','06d29950-2262-474c-acd6-fcab8e632ae1' FROM `lb-players` WHERE NOT EXISTS (SELECT NULL FROM `lb-players` WHERE UUID = '06d29950-2262-474c-acd6-fcab8e632ae1') LIMIT 1

[04:12:15] [Logblock-Consumer/WARN]: [LogBlock] [Consumer-Debug] Query 1 - Result: 0

[04:12:15] [Logblock-Consumer/WARN]: [LogBlock] [Consumer-Debug] Query 2: SELECT playerid FROM `lb-players` WHERE UUID = '06d29950-2262-474c-acd6-fcab8e632ae1'

[04:12:32] [Server thread/INFO]: [Server] yes but diferent

[04:12:35] [Async Chat Thread - #0/INFO]: [MapNormal]-[Novice]   Brokkonaut : ok

[04:12:35] [Logblock-Consumer/WARN]: [LogBlock] [Consumer] Failed to add player Brokkonaut

[04:12:35] [Logblock-Consumer/WARN]: [LogBlock] [Consumer-Debug] Query 1: INSERT IGNORE INTO `lb-players` (playername,UUID) SELECT 'Brokkonaut','06d29950-2262-474c-acd6-fcab8e632ae1' FROM `lb-players` WHERE NOT EXISTS (SELECT NULL FROM `lb-players` WHERE UUID = '06d29950-2262-474c-acd6-fcab8e632ae1') LIMIT 1

[04:12:35] [Logblock-Consumer/WARN]: [LogBlock] [Consumer-Debug] Query 1 - Result: 0

[04:12:35] [Logblock-Consumer/WARN]: [LogBlock] [Consumer-Debug] Query 2: SELECT playerid FROM `lb-players` WHERE UUID = '06d29950-2262-474c-acd6-fcab8e632ae1'

**Comment by Brokkonaut** [comment]
Can you give me the output of the value "Auto_increment" of this mysql command? (phpmyadmin)
```
SHOW TABLE STATUS WHERE `name` LIKE 'lb-players'
```

**Comment by Brokkonaut** [comment]
```
SELECT * FROM (SELECT playerid, count(*) as counter FROM `lb-players` p GROUP BY playerid) AS p2 WHERE counter > 1
```

**Comment by Bobbbe** [comment]
![screen5](https://user-images.githubusercontent.com/42454593/45581583-c8d33b80-b86e-11e8-85d5-e6c5b03fe6de.png)

**Comment by Bobbbe** [comment]
[04:52:07] [Server thread/INFO]: [LogBlock] Enabling LogBlock v1.13.1-SNAPSHOT (build #24)

[04:52:07] [Server thread/INFO]: [LogBlock] Connecting to minecraft_116584@jdbc:mysql://minecraft94.omgserv.com:3306/minecraft_116584...

[04:52:07] [Server thread/INFO]: LogBlock-Connection-Pool - Starting...

[04:52:25] [Server thread/INFO]: LogBlock-Connection-Pool - Start completed.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-players.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-chat.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-materials.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-blockstates.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-Freebuild1_13-blocks.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-Freebuild1_13-chestdata.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-Freebuild1_13-state.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-Freebuild1_13-kills.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-MapNormal_the_end-blocks.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-MapNormal_the_end-chestdata.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-MapNormal_the_end-state.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-MapNormal_the_end-kills.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-Messa-blocks.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-Messa-chestdata.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-Messa-state.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-Messa-kills.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-Sable-blocks.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-Sable-chestdata.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-Sable-state.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-Sable-kills.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-HalloWin-blocks.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-HalloWin-chestdata.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-HalloWin-state.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-Events-blocks.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-Events-chestdata.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-Events-state.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-Events-kills.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-MapNormal_nether-blocks.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-MapNormal_nether-chestdata.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-MapNormal_nether-state.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-MapNormal_nether-kills.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-SkyBlock-blocks.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-SkyBlock-chestdata.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-SkyBlock-state.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-SkyBlock-kills.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-creatif1-blocks.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-creatif1-chestdata.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-creatif1-state.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-creatif1-kills.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-pvp-blocks.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-pvp-chestdata.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-pvp-state.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-pvp-kills.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-gravier-blocks.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-gravier-chestdata.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-gravier-state.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-gravier-kills.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-MapNormal-blocks.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-MapNormal-chestdata.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-MapNormal-state.

[04:52:25] [Server thread/INFO]: [LogBlock] Creating table lb-MapNormal-kills.

[04:52:25] [Server thread/INFO]: [LogBlock] Add index name to table lb-materials: Table modified

[04:52:25] [Server thread/INFO]: [LogBlock] Add index name to table lb-blockstates: Table modified
