### ISSUE TITLE
message too long

### ISSUE THREAD

**Issue by Bobbbe** [LogBlock/LogBlock#722]
Hi i have new issues when im put a command block .
[15:30:21] [Logblock-Consumer/ERROR]: [LogBlock] [Consumer] Could not insert entries!

java.sql.BatchUpdateException: Data truncation: Data too long for column 'message' at row 1

	at sun.reflect.GeneratedConstructorAccessor192.newInstance(Unknown Source) ~[?:?]

	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_162]

	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_162]

	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]

	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]

	at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1163) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]

	at com.mysql.jdbc.PreparedStatement.executeBatchedInserts(PreparedStatement.java:1587) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]

	at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1253) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]

	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]

	at de.diddiz.lib.com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128) ~[LogBlock.jar:?]

	at de.diddiz.lib.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java) ~[LogBlock.jar:?]

	at de.diddiz.LogBlock.Consumer$BatchHelper.processStatements(Consumer.java:992) ~[LogBlock.jar:?]

	at de.diddiz.LogBlock.Consumer.run(Consumer.java:486) [LogBlock.jar:?]

Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'message' at row 1

	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3974) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]

	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]

	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]

	at com.mysql.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1283) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]

	at com.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:783) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]

	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]

	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]

	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]

	at com.mysql.jdbc.PreparedStatement.executeBatchedInserts(PreparedStatement.java:1548) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]

**Comment by Brokkonaut** [comment]
Please try the latest build - It might still report some errors while trying to import logs on the next server start, but it should be fine when you restart the server once more

**Comment by Bobbbe** [comment]
ok i'm upgrade all is ok :)
but today i have this.
[20:29:53] [Server thread/INFO]: soundm1065 issued server command: /spawn

[20:30:28] [Server thread/INFO]: [@: Spread 1 players around 0.5, 0.5 with an average distance of 0.00 blocks apart]

[20:35:14] [Server thread/ERROR]: Could not pass event BlockFromToEvent to LogBlock v1.13.1-SNAPSHOT (build #33)

org.bukkit.event.EventException: null

	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]

	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]

	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]

	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]

	at net.minecraft.server.v1_13_R2.FluidTypeFlowing.a(FluidTypeFlowing.java:195) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]

	at net.minecraft.server.v1_13_R2.FluidTypeFlowing.a(FluidTypeFlowing.java:167) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]

	at net.minecraft.server.v1_13_R2.FluidTypeFlowing.a(FluidTypeFlowing.java:497) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]

	at net.minecraft.server.v1_13_R2.Fluid.a(SourceFile:56) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]

	at net.minecraft.server.v1_13_R2.WorldServer.a(WorldServer.java:668) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]

	at net.minecraft.server.v1_13_R2.TickListServer.a(TickListServer.java:77) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]

	at net.minecraft.server.v1_13_R2.WorldServer.q(WorldServer.java:660) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]

	at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:301) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]

	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:952) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]

	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]

	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]

	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]

	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]

Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_13_R2.block.impl.CraftKelp cannot be cast to org.bukkit.block.data.Levelled

	at de.diddiz.LogBlock.listeners.FluidFlowLogging.onBlockFromTo(FluidFlowLogging.java:70) ~[?:?]

	at sun.reflect.GeneratedMethodAccessor383.invoke(Unknown Source) ~[?:?]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]

	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]

	... 16 more

**Comment by Bobbbe** [comment]
oh ! and this
[Server thread/WARN]: [LogBlock] [Consumer] Queue overloaded. Size: 1000

**Comment by Brokkonaut** [comment]
The BlockFromToEvent exception was fixes in Build 34 yesterday, so updating should help.

The overloaded queue is just a warning that that database is not able to handle the amount of new log entries at that point of time. If it does not happen too often, there is no problem. If it happens very often a faster database server or reducing the amount of created logs (disable some logging in the world configs) might help

**Comment by Bobbbe** [comment]
OK, thanks,
I have another question for you,
If I use the 'bedrock or pickaxe' to look at who has changed a block, I have only 86400 minutes (60 days) is it possible to increase it?
in the 'lookup' section of the config file I tried to increase the 'defaultTime' but that does not change anything.

There is also the section to see the information with the 'worledit' which is not visible with the tools, I activated them well, but if I place blocks with the 'worldedit' I do not have any info on these blocks.

**Comment by Bobbbe** [comment]
To increase the verification time, I found, I was not at the right section :) it works now.
It remains just the question of 'worldedit' to settle.

**Comment by Brokkonaut** [comment]
If you have enabled worldedit in the worlds config and you use the latest worldedit (7.0.0) it should be logged as blockplace/blockbreak events. I just tested it, it works as expected.

worlededit logging might be a bit problematic though, because it can cause a huge amount of block changes within a short period of time and so it can extremely overload the logging. I would not recommend using it.

**Comment by Bobbbe** [comment]
oh! im put build #34 logblock, desactivate worldedit and all is good :) thx

**Comment by Brokkonaut** [comment]
I don't know much about the worldborder fill feature, can't help you with that - sorry
