### ISSUE TITLE
Could not pass event BlockFromToEvent to LogBlock v1.13.1-SNAPSHOT (build #33)

### ISSUE THREAD

**Issue by saturnux** [LogBlock/LogBlock#724]
hello,

when I discover the map, it inevitably flows on lava, or vice versa.
i have this on log : 
```
[12:09:19] [Server thread/ERROR]: Could not pass event BlockFromToEvent to LogBlock v1.13.1-SNAPSHOT (build #33)
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.1.jar:git-Paper-373]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.1.jar:git-Paper-373]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.1.jar:git-Paper-373]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.FluidTypeFlowing.a(FluidTypeFlowing.java:196) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.FluidTypeFlowing.a(FluidTypeFlowing.java:167) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.FluidTypeFlowing.a(FluidTypeFlowing.java:512) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.Fluid.a(SourceFile:56) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.WorldServer.a(WorldServer.java:681) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.TickListServer.a(TickListServer.java:85) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.WorldServer.q(WorldServer.java:673) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:313) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1076) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:434) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.1.jar:git-Paper-373]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_13_R2.block.data.CraftBlockData cannot be cast to org.bukkit.block.data.Levelled
	at de.diddiz.LogBlock.listeners.FluidFlowLogging.onBlockFromTo(FluidFlowLogging.java:70) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor72.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.1.jar:git-Paper-373]
	... 16 more
```

For info i'm on paper 1.13.1

**Comment by Brokkonaut** [comment]
thanks, should be fixed in the latest build now
