### ISSUE TITLE
database errors, data lost

### ISSUE THREAD

**Issue by atesin** [LogBlock/LogBlock#726]
java.net.SocketException: Tubería rota (Write failed) // <--- (broken pipe)
[LogBlock] [Consumer] Could not insert entries!

"use the Connector/J connection property 'autoReconnect=true' to avoid this problem"

... it seems my minecraft server had been idle from some time and my db server had shutted down some connections to save resources... so when a player logins and starts to play and the plugin want to save the changes in the db, it finds the connection closed...  doesn't store the data, try to open the connection again and forward the data, preventing data loss .... instead it gives up immediately dropping the data, causing inconsistencies

i dont want to configure my database server to keep connections alive until eternity, i think the plugin should manage these cases by configure 'autoReconnect=true' to connector as suggested, then storing the data asynchronously

configuration:
- pentium xeon 4ghz 12 cores, 12gb ram
- CentOS 7 x86_64
- mariadb server  5.5.60
- java se  1.8.0_151-b12 + jdk
- paperclip for mc 1.13.1 build 376
- LogBlock version 1.13.1-SNAPSHOT (build 29)

full log:

`
[14:46:43] [User Authenticator #4/INFO]: UUID of player RATULCO is xxxx-xxxxx-xxxx-xxxxx-xxxx
[14:46:43] [Logblock-Consumer/WARN]: [de.diddiz.lib.com.zaxxer.hikari.pool.ProxyConnection] LogBlock-Connection-Pool - Connection com.mysql.jdbc.JDBC4Connection@7b9484a0 marked as broken because of SQLSTATE(08S01), ErrorCode(0)
java.sql.BatchUpdateException: The last packet successfully received from the server was 56.881.721 milliseconds ago.  The last packet sent successfully to the server was 56.881.743 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_151]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_151]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_151]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[patched_1.13.1.jar:git-Paper-376]
        at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[patched_1.13.1.jar:git-Paper-376]
        at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1163) ~[patched_1.13.1.jar:git-Paper-376]
        at com.mysql.jdbc.ServerPreparedStatement.executeBatchSerially(ServerPreparedStatement.java:758) ~[patched_1.13.1.jar:git-Paper-376]
        at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1262) ~[patched_1.13.1.jar:git-Paper-376]
        at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970) ~[patched_1.13.1.jar:git-Paper-376]
        at de.diddiz.lib.com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128) ~[?:?]
        at de.diddiz.lib.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java) ~[?:?]
        at de.diddiz.LogBlock.Consumer$BatchHelper.processStatements(Consumer.java:992) ~[?:?]
        at de.diddiz.LogBlock.Consumer.run(Consumer.java:486) ~[?:?]
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 56.881.721 milliseconds ago.  The last packet sent successfully to the server was 56.881.743 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_151]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_151]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_151]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[patched_1.13.1.jar:git-Paper-376]
        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990) ~[patched_1.13.1.jar:git-Paper-376]
        at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3749) ~[patched_1.13.1.jar:git-Paper-376]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2512) ~[patched_1.13.1.jar:git-Paper-376]
        at com.mysql.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1283) ~[patched_1.13.1.jar:git-Paper-376]
        at com.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:783) ~[patched_1.13.1.jar:git-Paper-376]
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079) ~[patched_1.13.1.jar:git-Paper-376]
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013) ~[patched_1.13.1.jar:git-Paper-376]
        at com.mysql.jdbc.ServerPreparedStatement.executeBatchSerially(ServerPreparedStatement.java:725) ~[patched_1.13.1.jar:git-Paper-376]
        ... 6 more
Caused by: java.net.SocketException: Tubería rota (Write failed)
        at java.net.SocketOutputStream.socketWrite0(Native Method) ~[?:1.8.0_151]
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111) ~[?:1.8.0_151]
        at java.net.SocketOutputStream.write(SocketOutputStream.java:155) ~[?:1.8.0_151]
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82) ~[?:1.8.0_151]
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140) ~[?:1.8.0_151]
        at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3731) ~[patched_1.13.1.jar:git-Paper-376]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2512) ~[patched_1.13.1.jar:git-Paper-376]
        at com.mysql.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1283) ~[patched_1.13.1.jar:git-Paper-376]
        at com.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:783) ~[patched_1.13.1.jar:git-Paper-376]
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079) ~[patched_1.13.1.jar:git-Paper-376]
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013) ~[patched_1.13.1.jar:git-Paper-376]
        at com.mysql.jdbc.ServerPreparedStatement.executeBatchSerially(ServerPreparedStatement.java:725) ~[patched_1.13.1.jar:git-Paper-376]
        ... 6 more
[14:46:43] [Logblock-Consumer/ERROR]: [LogBlock] [Consumer] Could not insert entries!
java.sql.BatchUpdateException: The last packet successfully received from the server was 56.881.721 milliseconds ago.  The last packet sent successfully to the server was 56.881.743 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_151]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_151]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_151]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[patched_1.13.1.jar:git-Paper-376]
        at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[patched_1.13.1.jar:git-Paper-376]
        at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1163) ~[patched_1.13.1.jar:git-Paper-376]
        at com.mysql.jdbc.ServerPreparedStatement.executeBatchSerially(ServerPreparedStatement.java:758) ~[patched_1.13.1.jar:git-Paper-376]
        at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1262) ~[patched_1.13.1.jar:git-Paper-376]
        at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970) ~[patched_1.13.1.jar:git-Paper-376]
        at de.diddiz.lib.com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128) ~[?:?]
        at de.diddiz.lib.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java) ~[?:?]
        at de.diddiz.LogBlock.Consumer$BatchHelper.processStatements(Consumer.java:992) ~[?:?]
        at de.diddiz.LogBlock.Consumer.run(Consumer.java:486) ~[?:?]
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 56.881.721 milliseconds ago.  The last packet sent successfully to the server was 56.881.743 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_151]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_151]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_151]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[patched_1.13.1.jar:git-Paper-376]
        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990) ~[patched_1.13.1.jar:git-Paper-376]
        at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3749) ~[patched_1.13.1.jar:git-Paper-376]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2512) ~[patched_1.13.1.jar:git-Paper-376]
        at com.mysql.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1283) ~[patched_1.13.1.jar:git-Paper-376]
        at com.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:783) ~[patched_1.13.1.jar:git-Paper-376]
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079) ~[patched_1.13.1.jar:git-Paper-376]
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013) ~[patched_1.13.1.jar:git-Paper-376]
        at com.mysql.jdbc.ServerPreparedStatement.executeBatchSerially(ServerPreparedStatement.java:725) ~[patched_1.13.1.jar:git-Paper-376]
        ... 6 more
Caused by: java.net.SocketException: Tubería rota (Write failed)
        at java.net.SocketOutputStream.socketWrite0(Native Method) ~[?:1.8.0_151]
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111) ~[?:1.8.0_151]
        at java.net.SocketOutputStream.write(SocketOutputStream.java:155) ~[?:1.8.0_151]
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82) ~[?:1.8.0_151]
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140) ~[?:1.8.0_151]
        at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3731) ~[patched_1.13.1.jar:git-Paper-376]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2512) ~[patched_1.13.1.jar:git-Paper-376]
        at com.mysql.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1283) ~[patched_1.13.1.jar:git-Paper-376]
        at com.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:783) ~[patched_1.13.1.jar:git-Paper-376]
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079) ~[patched_1.13.1.jar:git-Paper-376]
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013) ~[patched_1.13.1.jar:git-Paper-376]
        at com.mysql.jdbc.ServerPreparedStatement.executeBatchSerially(ServerPreparedStatement.java:725) ~[patched_1.13.1.jar:git-Paper-376]
        ... 6 more
`

**Comment by Brokkonaut** [comment]
Are you sure that logblock lost any data? it should retry with a new connection, if a connection failed and store the queued rows using the new connection.

For the autoReconnect setting:

> The use of this feature is not recommended, because it has side effects related to session state and data consistency when applications don't handle SQLExceptions properly, and is only designed to be used when you are unable to configure your application to handle SQLExceptions resulting from dead and stale connections properly. Alternatively, as a last option, investigate setting the MySQL server variable "wait_timeout" to a high value, rather than the default of 8 hours.
https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-configuration-properties.html

**Comment by Brokkonaut** [comment]
Testing revealed that it was possible that some data was not written to the database when a connection failed. This should be fixed in the latest build. I also improved the log messages when a connection failed.
