### ISSUE TITLE
Some chests won't show information

### ISSUE THREAD

**Issue by x1p** [LogBlock/LogBlock#727]
Some chests won't show information and only open.

This error appeared:
```
> [19:13:50 ERROR]: Could not pass event PlayerInteractEvent to LogBlock v1.13.1-SNAPSHOT (build #40)
java.lang.NoSuchMethodError: com.sk89q.worldedit.bukkit.BukkitAdapter.asBlockVector(Lorg/bukkit/Location;)Lcom/sk89q/worldedit/math/BlockVector3;
at de.diddiz.worldedit.CuboidRegion.fromCorners(CuboidRegion.java:57) ~[?:?]
at de.diddiz.LogBlock.listeners.ToolListener.onPlayerInteract(ToolListener.java:62) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor28.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-429]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-429]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-429]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-429]
at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:314) ~[patched_1.13.2.jar:git-Paper-429]
at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:465) ~[patched_1.13.2.jar:git-Paper-429]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1322) ~[patched_1.13.2.jar:git-Paper-429]
at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.13.2.jar:git-Paper-429]
at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.13.2.jar:git-Paper-429]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.2.jar:git-Paper-429]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.2.jar:git-Paper-429]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.2.jar:git-Paper-429]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-429]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-429]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-429]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```
I guess this version does not work in combination with worldedit-bukkit-7.0.0-beta-01

**Comment by Brokkonaut** [comment]
You have to update WorldEdit + WorldGuard (or downgrade LogBlock to build 38 or earlier, if you currently cannot update WorldEdit/WorldGuard because of other dependencies)

This happens due to a change in the latest WorldEdit/WorldGuard builds where they renamed some classes.

**Comment by x1p** [comment]
Thnx, I assumed this was the problem. The only problem is that Areashop is not up-to-date to handle vectoring.
