### ISSUE TITLE
Error when creating tables

### ISSUE THREAD

**Issue by MegaNarwhal** [LogBlock/LogBlock#728]
With default configs, I get this error when LogBlock goes to create all its tables:
```
[04:17:05 ERROR]: [LogBlock] [Updater] Error:
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Specified key was too long; max key length is 767 bytes
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_151]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_151]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_151]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[spigot.jar:git-Spigot-947a8e7-3a91182]
        at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[spigot.jar:git-Spigot-947a8e7-3a91182]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[spigot.jar:git-Spigot-947a8e7-3a91182]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[spigot.jar:git-Spigot-947a8e7-3a91182]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[spigot.jar:git-Spigot-947a8e7-3a91182]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[spigot.jar:git-Spigot-947a8e7-3a91182]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[spigot.jar:git-Spigot-947a8e7-3a91182]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2491) ~[spigot.jar:git-Spigot-947a8e7-3a91182]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2449) ~[spigot.jar:git-Spigot-947a8e7-3a91182]
        at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845) ~[spigot.jar:git-Spigot-947a8e7-3a91182]
        at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:745) ~[spigot.jar:git-Spigot-947a8e7-3a91182]
        at de.diddiz.lib.com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95) ~[LogBlock.jar:?]
        at de.diddiz.lib.com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[LogBlock.jar:?]
        at de.diddiz.LogBlock.Updater.createIndexIfDoesNotExist(Updater.java:740) ~[LogBlock.jar:?]
        at de.diddiz.LogBlock.Updater.update(Updater.java:723) [LogBlock.jar:?]
        at de.diddiz.LogBlock.LogBlock.onEnable(LogBlock.java:94) [LogBlock.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) [spigot.jar:git-Spigot-947a8e7-3a91182]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot.jar:git-Spigot-947a8e7-3a91182]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-947a8e7-3a91182]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) [spigot.jar:git-Spigot-947a8e7-3a91182]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) [spigot.jar:git-Spigot-947a8e7-3a91182]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:584) [spigot.jar:git-Spigot-947a8e7-3a91182]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:546) [spigot.jar:git-Spigot-947a8e7-3a91182]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:424) [spigot.jar:git-Spigot-947a8e7-3a91182]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot.jar:git-Spigot-947a8e7-3a91182]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702) [spigot.jar:git-Spigot-947a8e7-3a91182]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```
I have been able to replicate this with builds 42 and 44 of LogBlock from Jenkins. The database is using InnoDB and I have tried latin1, utf8, and utf8mb4 charsets, all have this issue.

**Comment by Brokkonaut** [comment]
Should be working in the latest build
