### ISSUE TITLE
Error connecting to database

### ISSUE THREAD

**Issue by ladspeak** [LogBlock/LogBlock#729]
Hi. I had a mysql database fully working with logblock over a week ago and it suddenly stopped working, I have no idea why. Since then I have tried changing the details several times (creating new databases, changing the IP in config from localhost to 127.0.0.1, or the actual IP) with no luck. Here is what LogBlock spits out in the console;

[13:12:05 INFO]: [LogBlock] Connecting to logblockusername@jdbc:mysql://localhost:3306/lb2...

[13:12:05 INFO]: [de.diddiz.lib.com.zaxxer.hikari.HikariDataSource] LogBlock-Connection-Pool - Starting...

[13:12:06 ERROR]: [de.diddiz.lib.com.zaxxer.hikari.pool.HikariPool] LogBlock-Connection-Pool - Exception during pool initialization.
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_181]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_181]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_181]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_181]
at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[patched_1.13.2.jar:git-Paper-432]
at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990) ~[patched_1.13.2.jar:git-Paper-432]
at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:342) ~[patched_1.13.2.jar:git-Paper-432]
at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2197) ~[patched_1.13.2.jar:git-Paper-432]
at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2230) ~[patched_1.13.2.jar:git-Paper-432]
at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2025) ~[patched_1.13.2.jar:git-Paper-432]
at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:778) ~[patched_1.13.2.jar:git-Paper-432]
at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[patched_1.13.2.jar:git-Paper-432]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_181]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_181]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_181]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_181]
at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[patched_1.13.2.jar:git-Paper-432]
at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386) ~[patched_1.13.2.jar:git-Paper-432]
at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330) ~[patched_1.13.2.jar:git-Paper-432]
at de.diddiz.lib.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:136) ~[?:?]
at de.diddiz.lib.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369) ~[?:?]
at de.diddiz.lib.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198) ~[?:?]
at de.diddiz.lib.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467) ~[?:?]
at de.diddiz.lib.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:541) ~[?:?]
at de.diddiz.lib.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[?:?]
at de.diddiz.lib.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[?:?]
at de.diddiz.util.MySQLConnectionPool.getConnection(MySQLConnectionPool.java:39) ~[?:?]
at de.diddiz.LogBlock.LogBlock.getConnection(LogBlock.java:271) ~[?:?]
at de.diddiz.LogBlock.LogBlock.onLoad(LogBlock.java:69) ~[?:?]
at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:365) ~[?:?]
at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) ~[?:?]
at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.2.jar:git-Paper-432]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-432]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:729) ~[patched_1.13.2.jar:git-Paper-432]
at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1761) ~[patched_1.13.2.jar:git-Paper-432]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1565) ~[patched_1.13.2.jar:git-Paper-432]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-432]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-432]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.2.jar:git-Paper-432]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.2.jar:git-Paper-432]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.2.jar:git-Paper-432]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-432]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-432]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-432]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_181]
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_181]
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_181]
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_181]
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_181]
at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_181]
at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211) ~[patched_1.13.2.jar:git-Paper-432]
at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:301) ~[patched_1.13.2.jar:git-Paper-432]
... 41 more

[13:12:06 ERROR]: [LogBlock] Error while fetching connection:
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_181]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_181]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_181]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_181]
at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[patched_1.13.2.jar:git-Paper-432]
at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990) ~[patched_1.13.2.jar:git-Paper-432]
at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:342) ~[patched_1.13.2.jar:git-Paper-432]
at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2197) ~[patched_1.13.2.jar:git-Paper-432]
at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2230) ~[patched_1.13.2.jar:git-Paper-432]
at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2025) ~[patched_1.13.2.jar:git-Paper-432]
at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:778) ~[patched_1.13.2.jar:git-Paper-432]
at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[patched_1.13.2.jar:git-Paper-432]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_181]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_181]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_181]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_181]
at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[patched_1.13.2.jar:git-Paper-432]
at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386) ~[patched_1.13.2.jar:git-Paper-432]
at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330) ~[patched_1.13.2.jar:git-Paper-432]
at de.diddiz.lib.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:136) ~[?:?]
at de.diddiz.lib.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369) ~[?:?]
at de.diddiz.lib.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198) ~[?:?]
at de.diddiz.lib.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467) ~[?:?]
at de.diddiz.lib.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:541) ~[?:?]
at de.diddiz.lib.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[?:?]
at de.diddiz.lib.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[?:?]
at de.diddiz.util.MySQLConnectionPool.getConnection(MySQLConnectionPool.java:39) ~[?:?]
at de.diddiz.LogBlock.LogBlock.getConnection(LogBlock.java:271) ~[?:?]
at de.diddiz.LogBlock.LogBlock.onLoad(LogBlock.java:69) ~[?:?]
at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:365) ~[?:?]
at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) ~[?:?]
at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.2.jar:git-Paper-432]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-432]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:729) ~[patched_1.13.2.jar:git-Paper-432]
at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1761) ~[patched_1.13.2.jar:git-Paper-432]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1565) ~[patched_1.13.2.jar:git-Paper-432]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-432]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-432]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.2.jar:git-Paper-432]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.2.jar:git-Paper-432]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.2.jar:git-Paper-432]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-432]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-432]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-432]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_181]
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_181]
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_181]
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_181]
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_181]
at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_181]
at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211) ~[patched_1.13.2.jar:git-Paper-432]
at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:301) ~[patched_1.13.2.jar:git-Paper-432]
... 41 more

[13:12:06 INFO]: [LogBlock] Enabling LogBlock v1.13.1-SNAPSHOT (manually compiled)

**Comment by Brokkonaut** [comment]
The exception message is "Connection refused" - maybe the ip/port is incorrect, there might be a connection limit, the database server is not running, a firewall is blocking the connection or something like that.

There is not much logblock can do when it is not possible to establish a connection to the mysql server
