### ISSUE TITLE
NullPointerException: null key in entry: null=1

### ISSUE THREAD

**Issue by Blueeyestar** [LogBlock/LogBlock#735]
Spigot Version: CraftBukkit version git-Spigot-518206a-c4a67ee (MC: 1.13.2)

In the latest spigot version I get this error again and again in the console

[16:45:37] [Craft Scheduler Thread - 27/WARN]: [LogBlock] Plugin LogBlock v1.13.1-SNAPSHOT (manually compiled) generated an exception while executing task 51
java.lang.NullPointerException: null key in entry: null=1
	at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:32) ~[minecraft_server.jar:git-Spigot-518206a-c4a67ee]
	at com.google.common.collect.ImmutableMapEntry.<init>(ImmutableMapEntry.java:49) ~[minecraft_server.jar:git-Spigot-518206a-c4a67ee]
	at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:172) ~[minecraft_server.jar:git-Spigot-518206a-c4a67ee]
	at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:248) ~[minecraft_server.jar:git-Spigot-518206a-c4a67ee]
	at org.bukkit.craftbukkit.v1_13_R2.inventory.CraftMetaItem.serializeEnchantments(CraftMetaItem.java:1181) ~[minecraft_server.jar:git-Spigot-518206a-c4a67ee]
	at org.bukkit.craftbukkit.v1_13_R2.inventory.CraftMetaItem.serialize(CraftMetaItem.java:1121) ~[minecraft_server.jar:git-Spigot-518206a-c4a67ee]
	at org.bukkit.craftbukkit.v1_13_R2.inventory.CraftMetaItem.serialize(CraftMetaItem.java:1104) ~[minecraft_server.jar:git-Spigot-518206a-c4a67ee]
	at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSerializable.representData(YamlRepresenter.java:33) ~[minecraft_server.jar:git-Spigot-518206a-c4a67ee]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[minecraft_server.jar:git-Spigot-518206a-c4a67ee]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:157) ~[minecraft_server.jar:git-Spigot-518206a-c4a67ee]
	at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:315) ~[minecraft_server.jar:git-Spigot-518206a-c4a67ee]
	at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSerializable.representData(YamlRepresenter.java:35) ~[minecraft_server.jar:git-Spigot-518206a-c4a67ee]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[minecraft_server.jar:git-Spigot-518206a-c4a67ee]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:157) ~[minecraft_server.jar:git-Spigot-518206a-c4a67ee]
	at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:315) ~[minecraft_server.jar:git-Spigot-518206a-c4a67ee]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[minecraft_server.jar:git-Spigot-518206a-c4a67ee]
	at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:65) ~[minecraft_server.jar:git-Spigot-518206a-c4a67ee]
	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:306) ~[minecraft_server.jar:git-Spigot-518206a-c4a67ee]
	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:270) ~[minecraft_server.jar:git-Spigot-518206a-c4a67ee]
	at org.yaml.snakeyaml.Yaml.dump(Yaml.java:245) ~[minecraft_server.jar:git-Spigot-518206a-c4a67ee]
	at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:38) ~[minecraft_server.jar:git-Spigot-518206a-c4a67ee]
	at de.diddiz.util.Utils.serializeYamlConfiguration(Utils.java:264) ~[?:?]
	at de.diddiz.util.Utils.saveItemStack(Utils.java:245) ~[?:?]
	at de.diddiz.LogBlock.Consumer$BlockRow.executeStatements(Consumer.java:730) ~[?:?]
	at de.diddiz.LogBlock.Consumer.run(Consumer.java:472) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[minecraft_server.jar:git-Spigot-518206a-c4a67ee]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [minecraft_server.jar:git-Spigot-518206a-c4a67ee]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by Brokkonaut** [comment]
Somehow the item is not serializable - Either its a spigot bug or the itemstack has got some invalid tags.
