### ISSUE TITLE
Error on Start

### ISSUE THREAD

**Issue by esieben1310** [LogBlock/LogBlock#738]
Hey,
i get this error when i start my server:
```
[19:31:57] [Server thread/ERROR]: Error occurred while enabling LogBlock v1.13.1-SNAPSHOT (manually compiled) (Is it up to date?)
java.lang.NumberFormatException: For input string: "u"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_181]
	at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_181]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_181]
	at de.diddiz.LogBlock.LogBlock.onEnable(LogBlock.java:109) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.reload(CraftServer.java:807) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.Bukkit.reload(Bukkit.java:570) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1641) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:895) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

Version: Snapshot 1.13.1-2
Server Version: CraftBukkit version git-Spigot-518206a-a5b9c7b (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Config:
```
consumer:
  forceToProcessAtLeast: 200
  delayBetweenRuns: 2
  queueWarningSize: 1000
  timePerRun: 1000
  fireCustomEvents: false
  useBukkitScheduler: true
tools:
  toolblock:
    item: BEDROCK
    canDrop: false
    leftClickBehavior: TOOL
    mode: LOOKUP
    aliases:
    - tb
    rightClickBehavior: BLOCK
    defaultEnabled: true
    permissionDefault: OP
    params: area 0 all sum none limit 15 desc silent
  tool:
    leftClickBehavior: NONE
    item: WOODEN_PICKAXE
    defaultEnabled: true
    mode: LOOKUP
    aliases:
    - t
    params: area 0 all sum none limit 15 desc silent
    permissionDefault: OP
    canDrop: true
    rightClickBehavior: TOOL
lookup:
  linesPerPage: 15
  dateFormat: MM-dd HH:mm:ss
  defaultTime: 30 minutes
  defaultDist: 20
  linesLimit: 1500
mysql:
  password: xxxxxx
  host: localhost
  port: 3306
  database: logblock
  user: root
questioner:
  askRollbacks: true
  askRedos: true
  askClearLogs: true
  banPermission: mcbans.ban.local
  askRollbackAfterBan: false
  askClearLogAfterRollback: true
clearlog:
  auto:
  - world "world" before 365 days all
  - world "world" player lavaflow waterflow leavesdecay before 7 days all
  - world world_nether before 365 days all
  - world world_nether player lavaflow before 7 days all
  dumpDeletedLog: false
  autoClearLogDelay: 6h
  enableAutoClearLog: false
logging:
  logCreeperExplosionsAsPlayerWhoTriggeredThese: false
  logPlayerInfo: false
  logEnvironmentalKills: false
  hiddenPlayers: []
  ignoredChat:
  - /register
  - /login
  logBedExplosionsAsPlayerWhoTriggeredThese: true
  logKillsLevel: PLAYERS
  hiddenBlocks:
  - AIR
  - CAVE_AIR
  - VOID_AIR
rollback:
  maxTime: 2 days
  dontRollback:
  - LAVA
  - TNT
  - FIRE
  maxArea: 50
  replaceAnyway:
  - LAVA
  - WATER
  - FIRE
version: 1.13.1-SNAPSHOT (manually compiled)
debug: false
safety:
  id:
    check: true
loggedWorlds:
- world
- world_nether
- world_the_end
- Rubmcraft

```

**Comment by Brokkonaut** [comment]
Please try the latest build from here: https://www.iani.de/jenkins/job/LogBlock/

**Comment by esieben1310** [comment]
Thanks, this version works
