### ISSUE TITLE
doesn't support fulltext indexes

### ISSUE THREAD

**Issue by Bobbbe** [LogBlock/LogBlock#739]
hi,
i have error in v.50, im update for v-55 and i have same error.

[16:20:21] [Server thread/INFO]: LogBlock-Connection-Pool - Starting...
[16:20:21] [Server thread/INFO]: LogBlock-Connection-Pool - Start completed.
[16:20:21] [Server thread/INFO]: [LogBlock] Creating table lb-chat.
[16:20:21] [Server thread/ERROR]: [LogBlock] Error while loading: The used table type doesn't support FULLTEXT indexes
java.sql.SQLException: The used table type doesn't support FULLTEXT indexes
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2491) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2449) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:745) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at de.diddiz.lib.com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95) ~[LogBlock.jar:?]
	at de.diddiz.lib.com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[LogBlock.jar:?]
	at de.diddiz.LogBlock.Updater.createTable(Updater.java:833) ~[LogBlock.jar:?]
	at de.diddiz.LogBlock.Updater.checkTables(Updater.java:810) ~[LogBlock.jar:?]
	at de.diddiz.LogBlock.LogBlock.onEnable(LogBlock.java:90) [LogBlock.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
[16:20:21] [Server thread/INFO]: [LogBlock] Disabling LogBlock v1.13.2-SNAPSHOT (build #55)
[16:20:21] [Server thread/INFO]: [LogBlock] Waiting for consumer ...
[16:20:21] [Server thread/INFO]: LogBlock-Connection-Pool - Shutdown initiated...
[16:20:21] [Server thread/INFO]: LogBlock-Connection-Pool - Shutdown completed.

**Comment by Brokkonaut** [comment]
I have no idea why this happens as that code did not change for several years and is usually working. Maybe some strange MySQL configuration/version? As a workaround I would recommend to disable chat logging in the config (for all worlds)

**Comment by Bobbbe** [comment]
this is done, thank you for your speed.

**Comment by Bobbbe** [comment]
This server is running CraftBukkit version git-Spigot-f56e2e7-9dc5658 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
it does not matter ?

**Comment by Brokkonaut** [comment]
No, the Spigot version should not matter for this, its just the mysql server version or the mysql server config that could make a difference
