### ISSUE TITLE
NPE: Could not pass event EntityDeathEvent to LogBlock v1.13.2-SNAPSHOT (build #55)

### ISSUE THREAD

**Issue by bermudalocket** [LogBlock/LogBlock#742]
Running Paper 1.13.2 build 498, with LogBlock v1.13.2-SNAPSHOT build 55.

Seems like this is due to an incomplete list of projectiles in BukkitUtils. I've been able to confirm that Dragon Fireballs and Shulker Bullets at the very least both cause this exception to be thrown. 

The EntityDeathEvent is fed into the Consumer where the problematic line is [here](https://github.com/LogBlock/LogBlock/blob/master/src/main/java/de/diddiz/LogBlock/Consumer.java#L283). Indeed, [the list of projectile EntityTypes --> Materials](https://github.com/LogBlock/LogBlock/blob/master/src/main/java/de/diddiz/util/BukkitUtils.java#L300) is somewhat lacking.

<details>
    <summary>Details</summary>

```[23:28:16] [Server thread/ERROR]: Could not pass event EntityDeathEvent to LogBlock v1.13.2-SNAPSHOT (build #55)
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.2.jar:git-Paper-498]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-498]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-498]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-498]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:602) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.EntityLiving.die(EntityLiving.java:1243) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:1088) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.EntityShulker.damageEntity(EntityShulker.java:404) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.EntityShulkerBullet.a(EntityShulkerBullet.java:315) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.EntityShulkerBullet.tick(EntityShulkerBullet.java:266) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1549) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.World.g(World.java:1516) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1323) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:598) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1099) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-498]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.IllegalArgumentException: Material cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.13.2.jar:git-Paper-498]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:73) ~[patched_1.13.2.jar:git-Paper-498]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:61) ~[patched_1.13.2.jar:git-Paper-498]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:49) ~[patched_1.13.2.jar:git-Paper-498]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:39) ~[patched_1.13.2.jar:git-Paper-498]
        at de.diddiz.LogBlock.Consumer.queueKill(Consumer.java:283) ~[?:?]
        at de.diddiz.LogBlock.listeners.KillLogging.onEntityDeath(KillLogging.java:39) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor225.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-498]
        ... 18 more```
</details>

**Comment by Brokkonaut** [comment]
thx

**Comment by bermudalocket** [comment]
Works great, thanks!
