### ISSUE TITLE
Constraint conflict

### ISSUE THREAD

**Issue by masterstreamer** [LogBlock/LogBlock#747]
I get this error all few minutes:
`[17:13:10 WARN]: [LogBlock] [Consumer] Database connection lost, reconnecting! SQLState: 23000
[17:13:10 WARN]: [LogBlock] [Consumer] Database connection lost, reconnecting! SQLState: 23000
[17:13:10 ERROR]: [LogBlock] [Consumer] Could not insert entries! SQLState: 23000
java.sql.BatchUpdateException: Duplicate entry '1462359' for key 'PRIMARY'
        at jdk.internal.reflect.GeneratedConstructorAccessor152.newInstance(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[spigot_server.jar:git-Spigot-f09662d-f40143e]
        at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[spigot_server.jar:git-Spigot-f09662d-f40143e]
        at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1163) ~[spigot_server.jar:git-Spigot-f09662d-f40143e]
        at com.mysql.jdbc.PreparedStatement.executeBatchedInserts(PreparedStatement.java:1632) ~[spigot_server.jar:git-Spigot-f09662d-f40143e]
        at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1298) ~[spigot_server.jar:git-Spigot-f09662d-f40143e]
        at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970) ~[spigot_server.jar:git-Spigot-f09662d-f40143e]
        at de.diddiz.lib.com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128) ~[LogBlock.jar:?]
        at de.diddiz.lib.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java) ~[LogBlock.jar:?]
        at de.diddiz.LogBlock.Consumer$BatchHelper.processStatements(Consumer.java:1204) ~[LogBlock.jar:?]
        at de.diddiz.LogBlock.Consumer.run(Consumer.java:516) [LogBlock.jar:?]
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1462359' for key 'PRIMARY'
        at jdk.internal.reflect.GeneratedConstructorAccessor151.newInstance(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[spigot_server.jar:git-Spigot-f09662d-f40143e]
        at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[spigot_server.jar:git-Spigot-f09662d-f40143e]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936) ~[spigot_server.jar:git-Spigot-f09662d-f40143e]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[spigot_server.jar:git-Spigot-f09662d-f40143e]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[spigot_server.jar:git-Spigot-f09662d-f40143e]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[spigot_server.jar:git-Spigot-f09662d-f40143e]
        at com.mysql.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1288) ~[spigot_server.jar:git-Spigot-f09662d-f40143e]
        at com.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:788) ~[spigot_server.jar:git-Spigot-f09662d-f40143e]
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124) ~[spigot_server.jar:git-Spigot-f09662d-f40143e]
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[spigot_server.jar:git-Spigot-f09662d-f40143e]
        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[spigot_server.jar:git-Spigot-f09662d-f40143e]
        at com.mysql.jdbc.PreparedStatement.executeBatchedInserts(PreparedStatement.java:1593) ~[spigot_server.jar:git-Spigot-f09662d-f40143e]
        ... 6 more`
I didn't changed anything and before a few days this was working fine.
Where can I find which table is affected?

**Comment by Brokkonaut** [comment]
This message says that an row-id that is not used in a world-blocks table is already used in another table. This cannot happen without external modifications to the tables.

It looks like you either have several servers inserting to the same database tables. If you run logblock on more than one server be sure to use different table prefixes for every world (config entry "table" in the logblock config for the world)

Or you have cleared/restored from a backup the world-blocks table of a world without clearing the world-state, world-chestdata, world-entities, world-entityid tables. If you do something like that you have to make sure that all tables are cleared.
