### ISSUE TITLE
Logblock 1.14pre5  Error

### ISSUE THREAD

**Issue by Blueeyestar** [LogBlock/LogBlock#750]
Spigot: CraftBukkit version git-Spigot-1eece4f-8ddb94d (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT)

[20:33:57] [Server thread/ERROR]: [LogBlock] Error while loading: String index out of range: -1
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967) ~[?:1.8.0_201]
	at de.diddiz.LogBlock.Updater.updateMaterialsPost1_13(Updater.java:850) ~[LogBlock.jar:?]
	at de.diddiz.LogBlock.LogBlock.onEnable(LogBlock.java:91) [LogBlock.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) [minecraft_server.jar:git-Spigot-1eece4f-8ddb94d]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [minecraft_server.jar:git-Spigot-1eece4f-8ddb94d]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) [minecraft_server.jar:git-Spigot-1eece4f-8ddb94d]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458) [minecraft_server.jar:git-Spigot-1eece4f-8ddb94d]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372) [minecraft_server.jar:git-Spigot-1eece4f-8ddb94d]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:441) [minecraft_server.jar:git-Spigot-1eece4f-8ddb94d]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [minecraft_server.jar:git-Spigot-1eece4f-8ddb94d]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:762) [minecraft_server.jar:git-Spigot-1eece4f-8ddb94d]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

**Comment by Brokkonaut** [comment]
Can you try if the latest commit fixes the problem?

**Comment by Blueeyestar** [comment]
It worked. Thank you :)

**Comment by Brokkonaut** [comment]
Ok :)
