### ISSUE TITLE
1.13.2 and 1.14 conflicts?

### ISSUE THREAD

**Issue by DmitryRendov** [LogBlock/LogBlock#751]
Hi guys,
I have some servers behind bungee - 1.13.2 and 1.14. All of them are tracked with LogBlock v1.13.2-SNAPSHOT (build #391) and shared MySQL database. Currently I've got an issue on 1.13.2 server - the plugin stop working with an issue:
`[06:05:37] [Server thread/ERROR]: [LogBlock] Error while loading: No enum constant org.bukkit.entity.EntityType.CAT
java.lang.IllegalArgumentException: No enum constant org.bukkit.entity.EntityType.CAT
        at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_211]
        at org.bukkit.entity.EntityType.valueOf(EntityType.java:1) ~[spigot-survival-1.13.2.jar:git-Spigot-e6eb36f-51100db]
        at de.diddiz.LogBlock.EntityTypeConverter.initializeEntityTypes(EntityTypeConverter.java:81) ~[LogBlock.jar:?]
        at de.diddiz.LogBlock.LogBlock.onEnable(LogBlock.java:93) [LogBlock.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) [spigot-survival-1.13.2.jar:git-Spigot-e6eb36f-51100db]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347) [spigot-survival-1.13.2.jar:git-Spigot-e6eb36f-51100db]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [spigot-survival-1.13.2.jar:git-Spigot-e6eb36f-51100db]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436) [spigot-survival-1.13.2.jar:git-Spigot-e6eb36f-51100db]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350) [spigot-survival-1.13.2.jar:git-Spigot-e6eb36f-51100db]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [spigot-survival-1.13.2.jar:git-Spigot-e6eb36f-51100db]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [spigot-survival-1.13.2.jar:git-Spigot-e6eb36f-51100db]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [spigot-survival-1.13.2.jar:git-Spigot-e6eb36f-51100db]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-survival-1.13.2.jar:git-Spigot-e6eb36f-51100db]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot-survival-1.13.2.jar:git-Spigot-e6eb36f-51100db]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
`
Could you please advise possible steps to restore it back to operational or just to update from 1.14 branch everywhere?
Big thanks in advance!

**Comment by DmitryRendov** [comment]
the same issue in case build #398 build

**Comment by Brokkonaut** [comment]
Yes, it conflicts because logblock has to maintain a material id table and mojang renamed some materials (for example "stone slab" -> "smooth stone slab"; and there is a different "stone slab" now). those id changes are also the reason why it is not possible to run the 1.14 branch on 1.13 servers.

to fix that problem stop the 1.14 server and configure it to use another database (you can clone the current database if you want to).

after that stop the 1.13 server and restore the database from a backup.

it is possible to fix the database without a backup but that would be very complicated, because you would have to manually fix the rows in lb-materials and lb-entitytypes and the corresponding entries in lb-worldname-blocks, lb-worldname-chestdata and lb-worldname-entities. any you would have to revert these renames: https://github.com/LogBlock/LogBlock/blob/1.14pre/src/main/java/de/diddiz/LogBlock/Updater.java#L861-L866

**Comment by Brokkonaut** [comment]
I improved the compatibility between 1.13 and 1.14 builds - now the latest builds (Build 64 for 1.13.2; Build 65+ for 1.14.1) for each should be able to use the same database without problems.
