### ISSUE TITLE
Unable to use /lb clearlog command

### ISSUE THREAD

**Issue by oranges13** [LogBlock/LogBlock#768]
We have several worlds and have been accumulating logs since our server was started in October 2018. At this point we would like to enable automatic log clearing, or at least perform this function manually from time to time.

Unfortunately, we receive an error when attempting to clear the logs, as follows.

You can see our config here: https://paste.ubuntu.com/p/gsXDwty8PG/
Here's an example of one of our world configs: https://paste.ubuntu.com/p/vHH8Bqf2gG/

Ideally we would like to remove all records older than 60 days. Modifying the default commands in the config, I have tried the following commands:

`/lb clearlog world "world" before 60 days all`

Here is the error we receive with the associated commands:

```
[14:59:02] [Craft Scheduler Thread - 162/ERROR]: [ClearLog] Exception: 
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown table 'lb-world' in MULTI DELETE
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_111]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_111]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[custom.jar:git-Spigot-a1ba5fe-3359cb1]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[custom.jar:git-Spigot-a1ba5fe-3359cb1]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[custom.jar:git-Spigot-a1ba5fe-3359cb1]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[custom.jar:git-Spigot-a1ba5fe-3359cb1]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[custom.jar:git-Spigot-a1ba5fe-3359cb1]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[custom.jar:git-Spigot-a1ba5fe-3359cb1]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[custom.jar:git-Spigot-a1ba5fe-3359cb1]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2491) ~[custom.jar:git-Spigot-a1ba5fe-3359cb1]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2449) ~[custom.jar:git-Spigot-a1ba5fe-3359cb1]
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845) ~[custom.jar:git-Spigot-a1ba5fe-3359cb1]
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:745) ~[custom.jar:git-Spigot-a1ba5fe-3359cb1]
	at de.diddiz.lib.com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95) ~[LogBlock.jar:?]
	at de.diddiz.lib.com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[LogBlock.jar:?]
	at de.diddiz.LogBlock.CommandsHandler$CommandClearLog.run(CommandsHandler.java:815) [LogBlock.jar:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) [custom.jar:git-Spigot-a1ba5fe-3359cb1]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [custom.jar:git-Spigot-a1ba5fe-3359cb1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by Brokkonaut** [comment]
I found no way to reproduce this issue, if it still exists I would need to see the logblock world config for the world "world"
