### ISSUE TITLE
Roman numeral conversion error + Exception thrown on level 10 items.

### ISSUE THREAD

**Issue by selfslaughter** [LogBlock/LogBlock#779]
**Tested on:**
 Paper 1.15.1 build 29
 Logblock build 87 (https://www.iani.de/jenkins/job/LogBlock/87/)

**Issue:**

- Placing enchanted items (Lvl 1-9) in a chest reads as +1 enchantment level. _(An item with Sharp V reports as Sharp VI. An item with Sharp IX reports as Sharp X etc.)_

- Placing an item with an enchantment level of 10 into a chest will throw an exception and cause any history prior to that item entering a chest to be unobtainable.

- Levels 11+ unaffected.

**Results of placing level 1 to level 12 blocks into chest, one by one:**

![javaw_2019_12_27_21_37_20_191 (2)](https://user-images.githubusercontent.com/12112089/71515820-2dde6380-28f1-11ea-9d9c-4f3ec60aee8e.png)

`[21:37:04 ERROR]: [Lookup] SELECT date, replaced, type, replacedData, typeData, playername, UUID, replacedState, typeState, item, itemremove, itemtype FROM `lb-world-blocks` INNER JOIN `lb-players` USING (playerid) LEFT JOIN `lb-world-state` USING (id) LEFT JOIN `lb-world-chestdata` USING (id) WHERE x = 3948 AND y = 63 AND z = 4909 AND date > date_sub(now(), INTERVAL 525600 MINUTE) ORDER BY id DESC LIMIT 15:
java.lang.ArrayIndexOutOfBoundsException: 10
        at de.diddiz.util.BukkitUtils.maybeToRoman(BukkitUtils.java:741) ~[?:?]
        at de.diddiz.util.BukkitUtils.toString(BukkitUtils.java:710) ~[?:?]
        at de.diddiz.LogBlock.BlockChange.getLogMessage(BlockChange.java:143) ~[?:?]
        at de.diddiz.LogBlock.CommandsHandler.showPage(CommandsHandler.java:408) ~[?:?]
        at de.diddiz.LogBlock.CommandsHandler.showPage(CommandsHandler.java:390) ~[?:?]
        at de.diddiz.LogBlock.CommandsHandler.access$300(CommandsHandler.java:58) ~[?:?]
        at de.diddiz.LogBlock.CommandsHandler$CommandLookup.run(CommandsHandler.java:532) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.1.jar:git-Paper-29]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.1.jar:git-Paper-29]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.1.jar:git-Paper-29]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
`

**Comment by Brokkonaut** [comment]
Thanks for the report, build 89 should fix this: https://www.iani.de/jenkins/job/LogBlock/89/
