### ISSUE TITLE
 InventoryCloseEvent to LogBlock v1.16.1.2-SNAPSHOT 

### ISSUE THREAD

**Issue by Blueeyestar** [LogBlock/LogBlock#803]
Paper: Paper version git-Paper-148 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

We keep getting this error message in our console on our server.

```
>.... [19:49:47 ERROR]: Could not pass event InventoryCloseEvent to LogBlock v1.16.1.2-SNAPSHOT (build #108)
java.lang.NullPointerException: null
at org.bukkit.craftbukkit.v1_16_R2.inventory.CraftMetaCompass.<init>(CraftMetaCompass.java:46) ~[patched_1.16.2.jar:git-Paper-148]
at org.bukkit.craftbukkit.v1_16_R2.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:496) ~[patched_1.16.2.jar:git-Paper-148]
at org.bukkit.craftbukkit.v1_16_R2.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:275) ~[patched_1.16.2.jar:git-Paper-148]
at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:111) ~[patched_1.16.2.jar:git-Paper-148]
at de.diddiz.util.BukkitUtils.compareInventories(BukkitUtils.java:527) ~[?:?]
at de.diddiz.LogBlock.listeners.ChestAccessLogging.onInventoryClose(ChestAccessLogging.java:43) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor581.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.2.jar:git-Paper-148]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.2.jar:git-Paper-148]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.2.jar:git-Paper-148]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.2.jar:git-Paper-148]
at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1425) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2200) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:18) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:5) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-148]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

**Comment by Brokkonaut** [comment]
Caused by this issue: https://hub.spigotmc.org/jira/browse/SPIGOT-6025

I added a workaround for this bug in the latest dev build ( https://www.iani.de/jenkins/job/LogBlock/ ) - It will still print the exception, but log the remaining inventory updates to the database.

**Comment by Blueeyestar** [comment]
Thanks for the good work. Keep it up :)
