### ISSUE TITLE
Queries causing NPE in EntityTypeConverter due to missing entity types in lb-entitytypes

### ISSUE THREAD

**Issue by bermudalocket** [LogBlock/LogBlock#804]
Hi, we're getting the following NPE on the latest version of LogBlock (build 111).

Command:

    /lb coords entities area 10 kills entity zombie time 2d

NPE:

    [14:28:27] [Craft Scheduler Thread - 5202 - LogBlock/WARN]: [LogBlock] Plugin LogBlock v1.16.1.2-SNAPSHOT (build #111) generated an exception while executing task 1210484
    java.lang.NullPointerException: null
        at de.diddiz.LogBlock.EntityTypeConverter.getExistingEntityTypeId(EntityTypeConverter.java:20) ~[?:?]
        at de.diddiz.LogBlock.QueryParams.getEntityTypeIds(QueryParams.java:1047) ~[?:?]
        at de.diddiz.LogBlock.QueryParams.getWhere(QueryParams.java:486) ~[?:?]
        at de.diddiz.LogBlock.QueryParams.getWhere(QueryParams.java:420) ~[?:?]
        at de.diddiz.LogBlock.QueryParams.getQuery(QueryParams.java:289) ~[?:?]
        at de.diddiz.LogBlock.CommandsHandler$CommandLookup.run(CommandsHandler.java:545) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.2.jar:git-Tuinity-"158e03c"]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.2.jar:git-Tuinity-"158e03c"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.2.jar:git-Tuinity-"158e03c"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]

Relevant line: https://github.com/LogBlock/LogBlock/blob/d548206c3a12c14e55b79158d327a62e5d94f7bf/src/main/java/de/diddiz/LogBlock/EntityTypeConverter.java#L20

Checking our database:

    mysql> SELECT * FROM `lb-entitytypes`;
    +----+----------------+
    | id | name           |
    +----+----------------+
    |  0 | HOGLIN         |
    |  1 | SHEEP          |
    |  2 | PIG            |
    |  3 | CHICKEN        |
    |  4 | VILLAGER       |
    |  5 | WOLF           |
    |  6 | COW            |
    |  7 | SQUID          |
    |  8 | TURTLE         |
    |  9 | TROPICAL_FISH  |
    | 10 | DOLPHIN        |
    | 11 | PUFFERFISH     |
    | 12 | COD            |
    | 13 | IRON_GOLEM     |
    | 14 | SALMON         |
    | 15 | HORSE          |
    | 16 | FOX            |
    | 17 | RABBIT         |
    | 18 | LLAMA          |
    | 19 | ARMOR_STAND    |
    | 20 | STRIDER        |
    | 21 | CAT            |
    | 22 | TRADER_LLAMA   |
    | 23 | DONKEY         |
    | 24 | MULE           |
    | 25 | BEE            |
    | 26 | SKELETON_HORSE |
    | 27 | ITEM_FRAME     |
    | 28 | POLAR_BEAR     |
    +----+----------------+
    29 rows in set (0.00 sec)

Replacing `zombie` in the command with, e.g., `hoglin` does not produce the error, but replacing it with, e.g., `spider` does.

**Comment by Brokkonaut** [comment]
Thanks, should be fixed in the latest build

**Comment by bermudalocket** [comment]
Confirmed fixed. Thank you!
