### ISSUE TITLE
Java/SQL error when doing lookups

### ISSUE THREAD

**Issue by brwnie** [LogBlock/LogBlock#807]
When I place the toolblock down, or do a manual look-up, I get an error like below:

[17:36:38 ERROR]: [LogBlock] [Lookup] SELECT date, replaced, type, replacedData, typeData, playername, UUID, replacedState, typeState, item, itemremove, itemtype FROM `lb-world-blocks` INNER JOIN `lb-players` USING (playerid) LEFT JOIN `lb-world-state` USING (id) LEFT JOIN `lb-world-chestdata` USING (id) WHERE x = -3358 AND y = 157 AND z = -3565 AND date > date_sub(now(), INTERVAL 86400 MINUTE) ORDER BY id DESC LIMIT 15:
java.sql.SQLException: Operation not allowed for a result set of type ResultSet.TYPE_FORWARD_ONLY.
        at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[?:?]
        at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[?:?]
        at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[?:?]
        at me.lucko.luckperms.lib.mysql.cj.jdbc.result.ResultSetImpl.beforeFirst(ResultSetImpl.java:426) ~[?:?]
        at de.diddiz.lib.com.zaxxer.hikari.pool.HikariProxyResultSet.beforeFirst(HikariProxyResultSet.java) ~[?:?]
        at de.diddiz.LogBlock.CommandsHandler$CommandLookup.run(CommandsHandler.java:511) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-275]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.4.jar:git-Paper-275]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Paper-275]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]

**Comment by Brokkonaut** [comment]
Did you recently update LuckPerms? If yes, try to update to the latest LuckPerms dev build or go back to the previus version you used. This is not a LogBlock issue but a LuckPerms issue.

**Comment by brwnie** [comment]
@Brokkonaut 

Yup, LuckPerms messing with LogBlock.
Latest dev build of LuckPerms fixes it, and now that you've said that it's pretty obvious from the log!

Appreciate the help, will close.
