### ISSUE TITLE
latest WE update causes NoSuchMethodError

### ISSUE THREAD

**Issue by electronicboy** [LogBlock/LogBlock#818]
Forwarding an exception on from some random dude who I do stuff for, 

```
[08:28:47] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to LogBlock v1.16.1.2-SNAPSHOT (build #465)
java.lang.NoSuchMethodError: com.sk89q.worldedit.entity.BaseEntity.<init>(Lcom/sk89q/worldedit/world/entity/EntityType;Lcom/sk89q/worldedit/util/nbt/CompoundBinaryTag;)V
	at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_16_R3.getEntity(Spigot_v1_16_R3.java:419) ~[?:?]
	at com.sk89q.worldedit.bukkit.BukkitEntity.getState(BukkitEntity.java:93) ~[?:?]
	at de.diddiz.worldedit.WorldEditHelper$Internal.serializeEntity(WorldEditHelper.java:131) ~[?:?]
	at de.diddiz.worldedit.WorldEditHelper.serializeEntity(WorldEditHelper.java:63) ~[?:?]
	at de.diddiz.LogBlock.listeners.AdvancedEntityLogging.onEntityDamage(AdvancedEntityLogging.java:226) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor317.execute(Unknown Source) ~[?:?]
	```
	
	This is due to the latest WE commit https://github.com/EngineHub/WorldEdit/commit/2c7ac3d21fd4936848a6b058ead10c8521aa22f7 which changes the signatures of some internal methods

**Comment by electronicboy** [comment]
wait, actually, ignore me, I might be dumb here
