### ISSUE TITLE
Table already exists Error 

### ISSUE THREAD

**Issue by seema84** [LogBlock/LogBlock#823]
plugin dont load
i get this error with build #122

[LogBlock] Error while loading: Table 'lb-players' already exists
java.sql.SQLSyntaxErrorException: Table 'lb-players' already exists
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[patched_1.16.5.jar:git-Paper-592]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[patched_1.16.5.jar:git-Paper-592]
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:762) ~[patched_1.16.5.jar:git-Paper-592]
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:646) ~[patched_1.16.5.jar:git-Paper-592]
	at de.diddiz.lib.com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95) ~[?:?]
	at de.diddiz.lib.com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[?:?]
	at de.diddiz.LogBlock.Updater.createTable(Updater.java:848) ~[?:?]
	at de.diddiz.LogBlock.Updater.checkTables(Updater.java:813) ~[?:?]
	at de.diddiz.LogBlock.LogBlock.onEnable(LogBlock.java:96) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-592]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-592]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-592]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-592]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-592]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:580) ~[patched_1.16.5.jar:git-Paper-592]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.16.5.jar:git-Paper-592]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1055) ~[patched_1.16.5.jar:git-Paper-592]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-592]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by Brokkonaut** [comment]
Can you check if build 124 fixes this issue?

**Comment by seema84** [comment]
build 124 works
