### ISSUE TITLE
Database connection error

### ISSUE THREAD

**Issue by tromek21** [LogBlock/LogBlock#827]
Hello I have a problem connecting to the database. 

System: `debian-10-buster-v20210420`
Error: `[11:46:04] [Server thread/INFO]: [LogBlock] Enabling LogBlock v1.16.5.1`
`[11:46:04] [Server thread/INFO]: [LogBlock] Connecting to [hidden]...`
`[11:46:04] [Server thread/INFO]: [de.diddiz.lib.com.zaxxer.hikari.HikariDataSource] LogBlock-Connection-Pool - Starting...`
`[11:46:04] [Server thread/ERROR]: [de.diddiz.lib.com.zaxxer.hikari.pool.HikariPool] LogBlock-Connection-Pool - Exception during pool initialization.
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure`

`The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.`
	`at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[patched_1.16.5.jar:git-Paper-658]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[patched_1.16.5.jar:git-Paper-658]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:833) ~[patched_1.16.5.jar:git-Paper-658]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[patched_1.16.5.jar:git-Paper-658]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[patched_1.16.5.jar:git-Paper-658]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[patched_1.16.5.jar:git-Paper-658]
	at de.diddiz.lib.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[?:?]
	at de.diddiz.lib.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353) ~[?:?]
	at de.diddiz.lib.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[?:?]
	at de.diddiz.lib.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473) ~[?:?]
	at de.diddiz.lib.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562) ~[?:?]
	at de.diddiz.lib.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[?:?]
	at de.diddiz.lib.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[?:?]
	at de.diddiz.util.MySQLConnectionPool.getConnection(MySQLConnectionPool.java:44) ~[?:?]
	at de.diddiz.LogBlock.LogBlock.getConnection(LogBlock.java:259) ~[?:?]
	at de.diddiz.LogBlock.LogBlock.onEnable(LogBlock.java:82) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-658]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-658]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-658]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-658]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-658]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:591) ~[patched_1.16.5.jar:git-Paper-658]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:281) ~[patched_1.16.5.jar:git-Paper-658]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1065) ~[patched_1.16.5.jar:git-Paper-658]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-658]
	at java.lang.Thread.run(Thread.java:829) [?:?]`
`Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure`

`The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[patched_1.16.5.jar:git-Paper-658]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[patched_1.16.5.jar:git-Paper-658]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[patched_1.16.5.jar:git-Paper-658]
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167) ~[patched_1.16.5.jar:git-Paper-658]
	at com.mysql.cj.protocol.a.NativeProtocol.negotiateSSLConnection(NativeProtocol.java:342) ~[patched_1.16.5.jar:git-Paper-658]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:167) ~[patched_1.16.5.jar:git-Paper-658]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1350) ~[patched_1.16.5.jar:git-Paper-658]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[patched_1.16.5.jar:git-Paper-658]
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:953) ~[patched_1.16.5.jar:git-Paper-658]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823) ~[patched_1.16.5.jar:git-Paper-658]
	... 23 more
Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:170) ~[?:?]
	at sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:98) ~[?:?]
	at sun.security.ssl.TransportContext.kickstart(TransportContext.java:221) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:433) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:411) ~[?:?]
	at com.mysql.cj.protocol.ExportControlled.performTlsHandshake(ExportControlled.java:317) ~[patched_1.16.5.jar:git-Paper-658]
	at com.mysql.cj.protocol.StandardSocketFactory.performTlsHandshake(StandardSocketFactory.java:188) ~[patched_1.16.5.jar:git-Paper-658]
	at com.mysql.cj.protocol.a.NativeSocketConnection.performTlsHandshake(NativeSocketConnection.java:97) ~[patched_1.16.5.jar:git-Paper-658]
	at com.mysql.cj.protocol.a.NativeProtocol.negotiateSSLConnection(NativeProtocol.java:333) ~[patched_1.16.5.jar:git-Paper-658]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:167) ~[patched_1.16.5.jar:git-Paper-658]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1350) ~[patched_1.16.5.jar:git-Paper-658]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[patched_1.16.5.jar:git-Paper-658]
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:953) ~[patched_1.16.5.jar:git-Paper-658]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823) ~[patched_1.16.5.jar:git-Paper-658]
	... 23 more`
`[11:46:04] [Server thread/ERROR]: [LogBlock] Could not connect to the Database! Please check your config! Communications link failure`

`The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.`

**Comment by Brokkonaut** [comment]
It looks like your mysql server is offline/not reachable or the database config in logblock is incorrect.

**Comment by tromek21** [comment]
Only the same configuration file on my local server works. Is it possible that the Debian system does not work?

**Comment by Brokkonaut** [comment]
If you have your database server correctly configured it should work on Debian.

**Comment by tromek21** [comment]
From the fact that on the local server on windows everything works and on debian it is not possible that vps is blocking the connection? or some other such thing

**Comment by Brokkonaut** [comment]
many things can disrupt the connection, i cannot really help you there. but i think there are many resources in the internet that could help you. the fastest and most stable option is always to run the database on the same machine where the minecraft server is running.

**Comment by tromek21** [comment]
Thanks for your help, the solution was to install mysql server on the local machine.
