### ISSUE TITLE
[SQLState: 22001] [Data truncation: Out of range value for column 'x' at row 1]

### ISSUE THREAD

**Issue by javlock** [LogBlock/LogBlock#839]
java:
openjdk version "16.0.2" 2021-07-20
OpenJDK Runtime Environment (build 16.0.2+7)
OpenJDK 64-Bit Server VM (build 16.0.2+7, mixed mode)

OS:Linux archlinux 5.14.8-arch1-1 #1 SMP PREEMPT Sun, 26 Sep 2021 19:36:15 +0000 x86_64 GNU/Linux
mysql:mariadb 10.6.4-1

plugin:
LogBlock-1.16.5.1
sha256 f76fdf87c3f6d946a5c1de663a6948a6548ef044e3cdfcd2f8edfdcae92af043

[exception.txt](https://github.com/LogBlock/LogBlock/files/7292995/exception.txt)

**Comment by javlock** [comment]
mc:
git-Paper-304 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 90f717f)

**Comment by Brokkonaut** [comment]
The coordinates of the block that should be logged are very far away. This currently does not work out of the box with logblock, but you can manually edit the sql schema to fix this. see here: https://github.com/LogBlock/LogBlock/issues/796

**Comment by DmitryRendov** [comment]
I've just updated Logblock to `v1.17.0.0-SNAPSHOT (build #152)` 
and getting the same error:
``
[10:33:03 ERROR]: [LogBlock] [Consumer] Could not insert entries! SQLState: 22001
java.sql.BatchUpdateException: Data truncation: Out of range value for column 'y' at row 1
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at com.mysql.cj.util.Util.handleNewInstance(Util.java:192) ~[mysql-connector-java-8.0.27.jar:8.0.27]
        at com.mysql.cj.util.Util.getInstance(Util.java:167) ~[mysql-connector-java-8.0.27.jar:8.0.27]
        at com.mysql.cj.util.Util.getInstance(Util.java:174) ~[mysql-connector-java-8.0.27.jar:8.0.27]
        at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:224) ~[mysql-connector-java-8.0.27.jar:8.0.27]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchedInserts(ClientPreparedStatement.java:755) ~[mysql-connector-java-8.0.27.jar:8.0.27]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:426) ~[mysql-connector-java-8.0.27.jar:8.0.27]
        at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:800) ~[mysql-connector-java-8.0.27.jar:8.0.27]
        at de.diddiz.lib.com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128) ~[LogBlock.jar:?]
        at de.diddiz.lib.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java) ~[LogBlock.jar:?]
        at de.diddiz.LogBlock.Consumer$BatchHelper.processStatements(Consumer.java:1196) ~[LogBlock.jar:?]
        at de.diddiz.LogBlock.Consumer.run(Consumer.java:484) ~[LogBlock.jar:?]
Caused by: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Out of range value for column 'y' at row 1
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104) ~[mysql-connector-java-8.0.27.jar:8.0.27]
        at com.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:634) ~[mysql-connector-java-8.0.27.jar:8.0.27]
        at com.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:418) ~[mysql-connector-java-8.0.27.jar:8.0.27]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1098) ~[mysql-connector-java-8.0.27.jar:8.0.27]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1046) ~[mysql-connector-java-8.0.27.jar:8.0.27]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1371) ~[mysql-connector-java-8.0.27.jar:8.0.27]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchedInserts(ClientPreparedStatement.java:716) ~[mysql-connector-java-8.0.27.jar:8.0.27]
        ... 6 more
``
Server version: git-Paper-24 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: cfa5b37)
The MySQL DB schema was as of 1.17.1

**Comment by Brokkonaut** [comment]
Can you please post the complete schema for the logblock tables? Looks like something is wrong there (y columns should always be "smallint not null")

And did you modify the "version" field in the logblock config by hand? - If yes, please set it back to 1.16.0 and restart the server.

**Comment by kaiarne** [comment]
Our (8? year old) database had some fields of 'y' coordinates definied as "unsigned". The changes from 1.18 make it necessary, that this field is "signed", so Logblock can add negative values. 

Not only the lb-xxx-blocks tables may affected, but also the lb-xxx-kills tables. They even had x,z as smallint (should be mediumint at least) and y as tinyint unsigned (should be smallint signed).

With phpmyadmin this is easy to change. HeidiSQL and the command line client are alternatives.
