### ISSUE TITLE
 Statement.executeQuery() cannot issue statements that do not produce result sets.

### ISSUE THREAD

**Issue by DmitryRendov** [LogBlock/LogBlock#843]
As I can see, your latest commit should fix the issue, though I couldn't find a place where I can download the jar file.
CI is broken due to Java versions issue.
Can you release a snapshot somewhere?
Thanks!

The error log:
```
[10:53:38] [Server thread/ERROR]: [LogBlock] Error while loading: Statement.executeQuery() cannot issue statements that do not produce result sets.
java.sql.SQLException: Statement.executeQuery() cannot issue statements that do not produce result sets.
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.27.jar:8.0.27]
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.27.jar:8.0.27]
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.27.jar:8.0.27]
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.27.jar:8.0.27]
        at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1140) ~[mysql-connector-java-8.0.27.jar:8.0.27]
        at de.diddiz.lib.com.zaxxer.hikari.pool.ProxyStatement.executeQuery(ProxyStatement.java:111) ~[LogBlock.jar:?]
        at de.diddiz.lib.com.zaxxer.hikari.pool.HikariProxyStatement.executeQuery(HikariProxyStatement.java) ~[LogBlock.jar:?]
        at de.diddiz.LogBlock.LogBlock.onEnable(LogBlock.java:92) ~[LogBlock.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.18.jar:git-Paper-24]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.18.jar:git-Paper-24]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.jar:git-Paper-24]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.jar:git-Paper-24]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.jar:git-Paper-24]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.jar:git-Paper-24]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-24]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Brokkonaut** [comment]
Snapshots are linked in the readme: https://www.iani.de/jenkins/job/LogBlock/ The latest build should work in 1.18

**Comment by DmitryRendov** [comment]
Thanks, It helps.
