### ISSUE TITLE
Failed to convert Itemstack to JSON

### ISSUE THREAD

**Issue by Trustmega** [LogBlock/LogBlock#844]
Hi everyone. I get a stacktrace when checking a blockchange with the bedrock tool. This _only_ happens to blocks placed after the upgrade to 1.18 spigot. Blocks that have changed before the update aren't affected from what I can see.

**Versions:**
Spigot, latest version: This server is running CraftBukkit version 3353-Spigot-dbf4938-f49e9d1 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) 
Logblock: Latest experimental build from the jenkins server. (build number 152)

**Server info:**
Old server, logblock database fully converted to new format. World fully converted to 1.18 format by running --ForceUpgrade.

**Plugins:**
```
[16:53:54] [Server thread/INFO]: Plugins (7): dynmap, WorldEdit, OpenInv, discraft, WorldGuard, Dynmap-WorldGuard, LogBlock
```
**Error message:**

```
[16:49:16] [Craft Scheduler Thread - 1/ERROR]: [LogBlock] Failed to convert Itemstack to JSON
java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.getTag()
        at java.lang.Class.getMethod(Class.java:2227) ~[?:?]
        at de.diddiz.LogBlock.util.BukkitUtils.getItemTag(BukkitUtils.java:784) ~[Logblock1.18.jar:?]
        at de.diddiz.LogBlock.util.BukkitUtils.toString(BukkitUtils.java:769) [Logblock1.18.jar:?]
        at de.diddiz.LogBlock.BlockChange.getLogMessage(BlockChange.java:142) [Logblock1.18.jar:?]
        at de.diddiz.LogBlock.CommandsHandler.showPage(CommandsHandler.java:442) [Logblock1.18.jar:?]
        at de.diddiz.LogBlock.CommandsHandler.showPage(CommandsHandler.java:424) [Logblock1.18.jar:?]
        at de.diddiz.LogBlock.CommandsHandler.access$300(CommandsHandler.java:60) [Logblock1.18.jar:?]
        at de.diddiz.LogBlock.CommandsHandler$CommandLookup.run(CommandsHandler.java:573) [Logblock1.18.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:82) [spigot-1.18-R0.1-SNAPSHOT.jar:3353-Spigot-dbf4938-f49e9d1]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.18-R0.1-SNAPSHOT.jar:3353-Spigot-dbf4938-f49e9d1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[16:49:16] [Craft Scheduler Thread - 1/ERROR]: [LogBlock] Failed to convert Itemstack to JSON
java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.getTag()
        at java.lang.Class.getMethod(Class.java:2227) ~[?:?]
        at de.diddiz.LogBlock.util.BukkitUtils.getItemTag(BukkitUtils.java:784) ~[Logblock1.18.jar:?]
        at de.diddiz.LogBlock.util.BukkitUtils.toString(BukkitUtils.java:769) [Logblock1.18.jar:?]
        at de.diddiz.LogBlock.BlockChange.getLogMessage(BlockChange.java:147) [Logblock1.18.jar:?]
        at de.diddiz.LogBlock.CommandsHandler.showPage(CommandsHandler.java:442) [Logblock1.18.jar:?]
        at de.diddiz.LogBlock.CommandsHandler.showPage(CommandsHandler.java:424) [Logblock1.18.jar:?]
        at de.diddiz.LogBlock.CommandsHandler.access$300(CommandsHandler.java:60) [Logblock1.18.jar:?]
        at de.diddiz.LogBlock.CommandsHandler$CommandLookup.run(CommandsHandler.java:573) [Logblock1.18.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:82) [spigot-1.18-R0.1-SNAPSHOT.jar:3353-Spigot-dbf4938-f49e9d1]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.18-R0.1-SNAPSHOT.jar:3353-Spigot-dbf4938-f49e9d1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

Ingame it seems to log the placing and removing of blocks correctly though. Rollback also seems to work as expected.
Oh well, just letting you guys know.

**Comment by Brokkonaut** [comment]
Can you try build 153? It should be fixed there.

**Comment by Trustmega** [comment]
Yup that solved the issue, thanks for the quick fix! :100:
