### ISSUE TITLE
Failed to convert Itemstack to JSON || getTagClone()

### ISSUE THREAD

**Issue by Drift91** [LogBlock/LogBlock#846]
Seems to be a similar issue to https://github.com/LogBlock/LogBlock/issues/844, but `getTagClone()` instead of `getTag()`.

Happened after I put a stick in a chest and took it back out, then used bedrock to lookup the chest. The stack trace shows up once for every entry in the LogBlock log. When I mouse over "stick" in the in-game chat it shows "Error" in light red.

`/version` output:
```
This server is running Paper version git-Paper-81 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 8c189d0)
You are running the latest version
Previous version: git-Paper-77 (MC: 1.18.1)
```
`/logblock` output:
```
LogBlock v1.17.0.0-SNAPSHOT (build #153) by DiddiZ
```

Stack trace:
```
[07:16:16 ERROR]: [LogBlock] Failed to convert Itemstack to JSON
java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.getTagClone()
	at java.lang.Class.getMethod(Class.java:2227) ~[?:?]
	at de.diddiz.LogBlock.util.BukkitUtils.getItemTag(BukkitUtils.java:784) ~[LogBlock.jar:?]
	at de.diddiz.LogBlock.util.BukkitUtils.toString(BukkitUtils.java:769) ~[LogBlock.jar:?]
	at de.diddiz.LogBlock.BlockChange.getLogMessage(BlockChange.java:147) ~[LogBlock.jar:?]
	at de.diddiz.LogBlock.CommandsHandler.showPage(CommandsHandler.java:442) ~[LogBlock.jar:?]
	at de.diddiz.LogBlock.CommandsHandler.showPage(CommandsHandler.java:424) ~[LogBlock.jar:?]
	at de.diddiz.LogBlock.CommandsHandler.access$300(CommandsHandler.java:60) ~[LogBlock.jar:?]
	at de.diddiz.LogBlock.CommandsHandler$CommandLookup.run(CommandsHandler.java:573) ~[LogBlock.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-81]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.1.jar:git-Paper-81]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.1.jar:git-Paper-81]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Malelus** [comment]
I have the same problem

**Comment by Drift91** [comment]
Appears to be fixed as of build 155. Thank you.
