### ISSUE TITLE
1.18.1 error

### ISSUE THREAD

**Issue by Bobbbe** [LogBlock/LogBlock#853]
i don't know if you have support for 1.18.1 but im put a smal error here for your futur update :)
have a nice day.
Paper-1.18.1, build- 151
logblock build-511

(wath is this build ? https://ci.md-5.net/job/LogBlock/) not good ?
im change for your build-159

[13:36:48 ERROR]: [LogBlock] Failed to convert Itemstack to JSON
java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.getTagClone()
        at java.lang.Class.getMethod(Class.java:2227) ~[?:?]
        at de.diddiz.LogBlock.util.BukkitUtils.getItemTag(BukkitUtils.java:784) ~[LogBlock-build-511.jar:?]
        at de.diddiz.LogBlock.util.BukkitUtils.toString(BukkitUtils.java:769) ~[LogBlock-build-511.jar:?]
        at de.diddiz.LogBlock.BlockChange.getLogMessage(BlockChange.java:142) ~[LogBlock-build-511.jar:?]
        at de.diddiz.LogBlock.CommandsHandler.showPage(CommandsHandler.java:442) ~[LogBlock-build-511.jar:?]
        at de.diddiz.LogBlock.CommandsHandler.showPage(CommandsHandler.java:424) ~[LogBlock-build-511.jar:?]
        at de.diddiz.LogBlock.CommandsHandler.access$300(CommandsHandler.java:60) ~[LogBlock-build-511.jar:?]
        at de.diddiz.LogBlock.CommandsHandler$CommandLookup.run(CommandsHandler.java:573) ~[LogBlock-build-511.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-151]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.1.jar:git-Paper-151]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.1.jar:git-Paper-151]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Bobbbe** [comment]
no more error with build-159 
this is my fault, i had the wrong version.
sorry for this issue. have a nice day :)
