### ISSUE TITLE
incompatibility with zspawner plugin

### ISSUE THREAD

**Issue by Bobbbe** [LogBlock/LogBlock#854]
i have plugin for manage spawners, but if im install logblock i have problem. this error.
the plugin cannot save spawners placed in other worlds. only in the main world.
if I remove the LogBlock plugin, everything is fine!
again, paper build-151, logblock build-159 and zSpawner-PRE-3.0.2.0

[19:33:26 INFO]: Bobbber issued server command: /spawners
[19:33:26 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.World.getName()" because the return value of "org.bukkit.Location.getWorld()" is null
[19:33:26 WARN]:        at zSpawner-PRE-3.0.2.0.jar//fr.maxlego08.zspawner.objects.SpawnerObject.toLocation(SpawnerObject.java:139)
[19:33:26 WARN]:        at zSpawner-PRE-3.0.2.0.jar//fr.maxlego08.zspawner.objects.SpawnerObject.lambda$0(SpawnerObject.java:125)
[19:33:26 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[19:33:26 WARN]:        at zSpawner-PRE-3.0.2.0.jar//fr.maxlego08.zspawner.objects.SpawnerObject.getItemStack(SpawnerObject.java:121)
[19:33:26 WARN]:        at zSpawner-PRE-3.0.2.0.jar//fr.maxlego08.zspawner.inventory.inventories.InventorySpawnerPaginate.buildItem(InventorySpawnerPaginate.java:32)
[19:33:26 WARN]:        at zSpawner-PRE-3.0.2.0.jar//fr.maxlego08.zspawner.inventory.inventories.InventorySpawnerPaginate.buildItem(InventorySpawnerPaginate.java:1)
[19:33:26 WARN]:        at zSpawner-PRE-3.0.2.0.jar//fr.maxlego08.zspawner.inventory.PaginateInventory.lambda$0(PaginateInventory.java:94)
[19:33:26 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[19:33:26 WARN]:        at zSpawner-PRE-3.0.2.0.jar//fr.maxlego08.zspawner.inventory.PaginateInventory.openInventory(PaginateInventory.java:92)
[19:33:26 WARN]:        at zSpawner-PRE-3.0.2.0.jar//fr.maxlego08.zspawner.inventory.VInventory.preOpenInventory(VInventory.java:179)
[19:33:26 WARN]:        at zSpawner-PRE-3.0.2.0.jar//fr.maxlego08.zspawner.inventory.InventoryManager.createInventory(InventoryManager.java:60)
[19:33:26 WARN]:        at zSpawner-PRE-3.0.2.0.jar//fr.maxlego08.zspawner.inventory.InventoryManager.createInventory(InventoryManager.java:42)
[19:33:26 WARN]:        at zSpawner-PRE-3.0.2.0.jar//fr.maxlego08.zspawner.zcore.utils.ZUtils.createInventory(ZUtils.java:789)
[19:33:26 WARN]:        at zSpawner-PRE-3.0.2.0.jar//fr.maxlego08.zspawner.ZSpawnerManager.openInventory(ZSpawnerManager.java:250)
[19:33:26 WARN]:        at zSpawner-PRE-3.0.2.0.jar//fr.maxlego08.zspawner.command.commands.CommandSpawner.perform(CommandSpawner.java:34)
[19:33:26 WARN]:        at zSpawner-PRE-3.0.2.0.jar//fr.maxlego08.zspawner.command.VCommand.prePerform(VCommand.java:374)
[19:33:26 WARN]:        at zSpawner-PRE-3.0.2.0.jar//fr.maxlego08.zspawner.command.CommandManager.processRequirements(CommandManager.java:173)
[19:33:26 WARN]:        at zSpawner-PRE-3.0.2.0.jar//fr.maxlego08.zspawner.command.CommandManager.onCommand(CommandManager.java:97)
[19:33:26 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[19:33:26 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[19:33:26 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:897)
[19:33:26 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2285)
[19:33:26 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2096)
[19:33:26 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2077)
[19:33:26 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[19:33:26 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[19:33:26 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[19:33:26 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[19:33:26 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:149)
[19:33:26 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(IAsyncTaskHandlerReentrant.java:23)
[19:33:26 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1413)
[19:33:26 WARN]:        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189)
[19:33:26 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:122)
[19:33:26 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1391)
[19:33:26 WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1384)
[19:33:26 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:132)
[19:33:26 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1362)
[19:33:26 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1268)
[19:33:26 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[19:33:26 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Bobbbe** [comment]
this is the discord groupZ for zspawner plugin if you need to speek with dev... https://discord.gg/H28xMCag

**Comment by Brokkonaut** [comment]
I have no idea how logblock should cause this. You should look for other possible reasons, maybe a different plugin load order when logblock is added that could cause this or something else.

**Comment by Bobbbe** [comment]
for sure, this is linked between these 2 plugins.
because if I remove the logblock, everything works fine.
you suggest me to add in the plugin.yml loadbefore or depend to change the loading order... I will test that and report this message to the dev. ZSpawner too.
