### ISSUE TITLE
Incompatibility with SlimeFun

### ISSUE THREAD

**Issue by SofiaRedmond** [LogBlock/LogBlock#855]
The plugin spams this text on my console (Pls fix it):

```
[21:45:12 ERROR]: [dough: protection] An Error occured while logging for the Protection Module: "LogBlock"
java.lang.NoClassDefFoundError: de/diddiz/util/LoggingUtil
        at io.github.thebusybiscuit.slimefun4.libraries.dough.protection.loggers.LogBlockLogger.logAction(LogBlockLogger.java:33) ~[Slimefun4 - RC 30 (git fd4b4).jar:?]
        at io.github.thebusybiscuit.slimefun4.libraries.dough.protection.ProtectionManager.logAction(ProtectionManager.java:165) ~[Slimefun4 - RC 30 (git fd4b4).jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.items.tools.ExplosiveTool.breakBlock(ExplosiveTool.java:149) ~[Slimefun4 - RC 30 (git fd4b4).jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.items.tools.ExplosiveTool.breakBlocks(ExplosiveTool.java:103) ~[Slimefun4 - RC 30 (git fd4b4).jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.items.tools.ExplosiveTool.lambda$getItemHandler$0(ExplosiveTool.java:70) ~[Slimefun4 - RC 30 (git fd4b4).jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.lambda$callToolHandler$1(BlockListener.java:138) ~[Slimefun4 - RC 30 (git fd4b4).jar:?]
        at io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem.callItemHandler(SlimefunItem.java:924) ~[Slimefun4 - RC 30 (git fd4b4).jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.callToolHandler(BlockListener.java:138) ~[Slimefun4 - RC 30 (git fd4b4).jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.onBlockBreak(BlockListener.java:122) ~[Slimefun4 - RC 30 (git fd4b4).jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor490.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-167]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:400) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:354) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:314) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1762) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:34) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:8) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-167]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-167]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-167]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-167]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-167]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.1.jar:git-Paper-167]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.1.jar:git-Paper-167]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-167]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: de.diddiz.util.LoggingUtil
        ... 34 more
```

**Comment by Brokkonaut** [comment]
Thats an issue in the SlimeFun plugin, they should update their logblock dependency

**Comment by WalshyDev** [comment]
This is already fixed in Slimefun, they're running an outdated version. @SofiaRedmond update - https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/
