### ISSUE TITLE
SQLExeption during update process

### ISSUE THREAD

**Issue by colaman90** [LogBlock/LogBlock#858]
Dear all,

we are running:
This server is running Paper version git-Paper-197 (MC: 1.18.1)
Server version: 10.3.31-MariaDB-0+deb10u1 Debian 10
Loading LogBlock v1.17.0.0-SNAPSHOT (build #161)

We receive an Stacktrace during the first startup with Version 1.18.1:
```
[04:26:42] [Craft Scheduler Thread - 9 - LogBlock/ERROR]: [LogBlock] [Updater] Error: 
java.sql.SQLException: Index 8 out of bounds for length 7
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1206) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at de.diddiz.lib.com.zaxxer.hikari.pool.ProxyStatement.executeQuery(ProxyStatement.java:111) ~[LogBlock_1.18.1_dev161.jar:?]
	at de.diddiz.lib.com.zaxxer.hikari.pool.HikariProxyStatement.executeQuery(HikariProxyStatement.java) ~[LogBlock_1.18.1_dev161.jar:?]
	at de.diddiz.LogBlock.Updater$PlayerCountChecker.run(Updater.java:1004) ~[LogBlock_1.18.1_dev161.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-197]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.1.jar:git-Paper-197]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.1.jar:git-Paper-197]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 7
	at com.mysql.cj.protocol.a.NativePacketPayload.readInteger(NativePacketPayload.java:386) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.protocol.a.NativeServerSessionStateController$NativeServerSessionStateChanges.init(NativeServerSessionStateController.java:108) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.protocol.a.result.OkPacket.parse(OkPacket.java:64) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.protocol.a.NativeProtocol.readServerStatusForResultSets(NativeProtocol.java:1691) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.protocol.a.ResultsetRowReader.read(ResultsetRowReader.java:83) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.protocol.a.ResultsetRowReader.read(ResultsetRowReader.java:42) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1587) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:82) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:48) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1600) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.protocol.a.NativeProtocol.readAllResults(NativeProtocol.java:1654) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1000) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryString(NativeProtocol.java:933) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:664) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1174) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	... 9 more
```

Can you please help to fix it?

Kind regards

**Comment by colaman90** [comment]
I can confirm, this error also occurs in the current Paper 1.18.2 (Build #250)
