### ISSUE TITLE
Could not insert entries! SQLState: 22003

### ISSUE THREAD

**Issue by HippieBeak** [LogBlock/LogBlock#861]
Hi,

I suddenly started getting these errors spammed on my server, and no blocks are being logged:

08.05 21:06:40 [Server] ERROR [LogBlock] [Consumer] Could not insert entries! SQLState: 22003
08.05 21:06:40 [Server] INFO java.sql.SQLDataException: Value '3014020830' is outside of valid range for type java.lang.Integer
08.05 21:06:40 [Server] INFO at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:114) ~[patched_1.17.1.jar:git-Pufferfish-22]
08.05 21:06:40 [Server] INFO at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[patched_1.17.1.jar:git-Pufferfish-22]
08.05 21:06:40 [Server] INFO at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[patched_1.17.1.jar:git-Pufferfish-22]
08.05 21:06:40 [Server] INFO at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[patched_1.17.1.jar:git-Pufferfish-22]
08.05 21:06:40 [Server] INFO at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[patched_1.17.1.jar:git-Pufferfish-22]
08.05 21:06:40 [Server] INFO at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:92) ~[patched_1.17.1.jar:git-Pufferfish-22]
08.05 21:06:40 [Server] INFO at com.mysql.cj.jdbc.result.ResultSetImpl.getObject(ResultSetImpl.java:1411) ~[patched_1.17.1.jar:git-Pufferfish-22]
08.05 21:06:40 [Server] INFO at com.mysql.cj.jdbc.result.ResultSetImpl.getInt(ResultSetImpl.java:816) ~[patched_1.17.1.jar:git-Pufferfish-22]
08.05 21:06:40 [Server] INFO at de.diddiz.lib.com.zaxxer.hikari.pool.HikariProxyResultSet.getInt(HikariProxyResultSet.java) ~[LogBlock-1.16.5.1.jar:?]
08.05 21:06:40 [Server] INFO at de.diddiz.LogBlock.Consumer$BatchHelper.processStatements(Consumer.java:1175) ~[LogBlock-1.16.5.1.jar:?]
08.05 21:06:40 [Server] INFO at de.diddiz.LogBlock.Consumer.run(Consumer.java:481) ~[LogBlock-1.16.5.1.jar:?]

We are using the version on https://www.spigotmc.org/resources/logblock.67333/ on a 1.17.1 server. I am currently trying to use the development build, but it is taking awhile to update -- will update here if it fixes it. If this doesn't fix it, any idea what I should do?

**Comment by Brokkonaut** [comment]
I'm not sure what value is this "3014020830" - looks like it it the log entry id, this is currently limited to int values (maximum of 2147483647) - i don't really know why the values are that high in your database. do you have a huge amount of log entries, or maybe did someone try some database operation that broke it?

**Comment by Brokkonaut** [comment]
Currently the only option would be to convert all logblock tables to use BIGINT for the id columns. I will probably add some automatic converter in the future to get rid of those limitations.

**Comment by KleinCrafter** [comment]
I found a potential solution: https://stackoverflow.com/questions/740358/reorder-reset-auto-increment-primary-key
But there are currently no FKs so that would kill the structure..

First step would be to add FKs with `ON UPDATE CASCADE` (and `ON DELETE CASCADE`?)
