### ISSUE TITLE
Updater Error

### ISSUE THREAD

**Issue by Goonhaven** [LogBlock/LogBlock#867]
OS: CentOS, version 8.

Java version:
openjdk version "17.0.1" 2021-10-19 LTS
OpenJDK Runtime Environment 21.9 (build 17.0.1+12-LTS)
OpenJDK 64-Bit Server VM 21.9 (build 17.0.1+12-LTS, mixed mode, sharing)

Error:
```
[11:52:45 ERROR]: [LogBlock] [Updater] Error:
java.sql.SQLException: Index 8 out of bounds for length 7
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1200) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at de.diddiz.lib.com.zaxxer.hikari.pool.ProxyStatement.executeQuery(ProxyStatement.java:111) ~[LogBlock.jar:?]
        at de.diddiz.lib.com.zaxxer.hikari.pool.HikariProxyStatement.executeQuery(HikariProxyStatement.java) ~[LogBlock.jar:?]
        at de.diddiz.LogBlock.Updater$PlayerCountChecker.run(Updater.java:1006) ~[LogBlock.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-26]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-26]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 7
        at com.mysql.cj.protocol.a.NativePacketPayload.readInteger(NativePacketPayload.java:398) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.protocol.a.NativeServerSessionStateController$NativeServerSessionStateChanges.init(NativeServerSessionStateController.java:103) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.protocol.a.result.OkPacket.parse(OkPacket.java:66) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.protocol.a.NativeProtocol.readServerStatusForResultSets(NativeProtocol.java:1752) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.protocol.a.ResultsetRowReader.read(ResultsetRowReader.java:83) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.protocol.a.ResultsetRowReader.read(ResultsetRowReader.java:42) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1648) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:82) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:48) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1661) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.protocol.a.NativeProtocol.readAllResults(NativeProtocol.java:1715) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1065) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.protocol.a.NativeProtocol.sendQueryString(NativeProtocol.java:998) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.NativeSession.execSQL(NativeSession.java:655) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1168) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        ... 9 more
```

Plugin: LogBlock build #183 (for 1.20).

**Comment by Brokkonaut** [comment]
Looks like an errror with the sql driver or the datasbase. Are you using an updated mariadb database? Can you tell me the database version? And is it reproducible without any other plugin?

**Comment by Goonhaven** [comment]
Version: MariaDB 10.5.6, can confirm it occurs without any other plugins enabled.

**Comment by KleinCrafter** [comment]
Can not reproduce.
New MariaDB 10.5.6 Installation (docker) with only LogBlock as a Plugin, no exceptions. 
```
[14:29:40] [Server thread/INFO]: Starting minecraft server version 1.20.1
[14:29:40] [Server thread/INFO]: Loading properties
[14:29:40] [Server thread/INFO]: This server is running CraftBukkit version 3871-Spigot-d2eba2c-3f9263b (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)
[...]
[14:29:54] [Server thread/INFO]: [LogBlock] Enabling LogBlock v1.20.0.0-SNAPSHOT (manually compiled)
[14:29:54] [Server thread/INFO]: [LogBlock] Connecting to minecraft@jdbc:mysql://localhost:3306/minecraft...
[14:29:54] [Server thread/INFO]: LogBlock-Connection-Pool - Starting...
[14:29:54] [Server thread/INFO]: LogBlock-Connection-Pool - Added connection com.mysql.cj.jdbc.ConnectionImpl@62b5d544
[14:29:54] [Server thread/INFO]: LogBlock-Connection-Pool - Start completed.
[14:29:54] [Server thread/INFO]: [LogBlock] Creating table lb-players.
[14:29:54] [Server thread/INFO]: [LogBlock] Creating table lb-materials.
[14:29:54] [Server thread/INFO]: [LogBlock] Creating table lb-blockstates.
[14:29:54] [Server thread/INFO]: [LogBlock] Creating table lb-entitytypes.
[14:29:54] [Server thread/INFO]: [LogBlock] Creating table lb-world-blocks.
[14:29:54] [Server thread/INFO]: [LogBlock] Creating table lb-world-chestdata.
[14:29:54] [Server thread/INFO]: [LogBlock] Creating table lb-world-state.
[14:29:54] [Server thread/INFO]: [LogBlock] Creating table lb-world-entityids.
[14:29:54] [Server thread/INFO]: [LogBlock] Creating table lb-world-entities.
[14:29:54] [Server thread/INFO]: [LogBlock] Creating table lb-world_the_end-blocks.
[14:29:54] [Server thread/INFO]: [LogBlock] Creating table lb-world_the_end-chestdata.
[14:29:54] [Server thread/INFO]: [LogBlock] Creating table lb-world_the_end-state.
[14:29:54] [Server thread/INFO]: [LogBlock] Creating table lb-world_the_end-entityids.
[14:29:54] [Server thread/INFO]: [LogBlock] Creating table lb-world_the_end-entities.
[14:29:54] [Server thread/INFO]: [LogBlock] Creating table lb-world_nether-blocks.
[14:29:54] [Server thread/INFO]: [LogBlock] Creating table lb-world_nether-chestdata.
[14:29:54] [Server thread/INFO]: [LogBlock] Creating table lb-world_nether-state.
[14:29:54] [Server thread/INFO]: [LogBlock] Creating table lb-world_nether-entityids.
[14:29:54] [Server thread/INFO]: [LogBlock] Creating table lb-world_nether-entities.
[14:29:55] [Server thread/INFO]: [LogBlock] Add index name to table lb-materials: Table modified
[14:29:55] [Server thread/INFO]: [LogBlock] Add index name to table lb-blockstates: Table modified
[14:29:55] [Server thread/INFO]: [LogBlock] [Updater] Current Minecraft Version: '1.20.1'
[14:29:55] [Server thread/ERROR]: [LogBlock] No compatible WorldEdit found, entity logging will not work!
```

Changed the `lb-players` back to `SMALLINT` -> no exception.
Maxed out the increment -> no exception.
`[14:43:22] [Craft Scheduler Thread - 0/WARN]: [LogBlock] Your server reached 65000 players. You should soon update your database table schema - see FAQ: https://github.com/LogBlock/LogBlock/wiki/FAQ#logblock-your-server-reached-65000-players-`

How is your table `lb-players` looking like?
```SHOW CREATE TABLE `lb-players`;```

**Comment by Brokkonaut** [comment]
It is a bit strange, because the ArrayIndexOutOfBoundsException happens deep inside of the mysql driver. So I have no idea what should cause it other than some driver/database incompatibility or a bug in the driver.
