### ISSUE TITLE
java.lang.IllegalArgumentException: Could not parse data: minecraft:cauldron[level=0]

### ISSUE THREAD

**Issue by othello777** [LogBlock/LogBlock#869]
Just installed the latest dev build of logblock (jun 12th 2023) with the latest build of paper for 1.20.1 and got this wack error.
```
[21:36:41 INFO]: [LogBlock] Updating tables to 1.12.0 ...
[21:36:41 INFO]: [LogBlock] Updating tables to 1.13.0 ...
[21:36:42 ERROR]: [LogBlock] Error while loading: Could not parse data: minecraft:cauldron[level=0]
java.lang.IllegalArgumentException: Could not parse data: minecraft:cauldron[level=0]
        at org.bukkit.craftbukkit.v1_20_R1.block.data.CraftBlockData.createNewData(CraftBlockData.j
ava:582) ~[paper-1.20.1.jar:git-Paper-84]
        at org.bukkit.craftbukkit.v1_20_R1.block.data.CraftBlockData.lambda$newData$1(CraftBlockData.java:557) ~[paper-1.20.1.jar:git-Paper-84]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.block.data.CraftBlockData.newData(CraftBlockData.java:557) ~[paper-1.20.1.jar:git-Paper-84]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.createBlockData(CraftServer.java:2676) ~[paper-1.20.1.jar:git-Paper-84]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.createBlockData(CraftServer.java:2669) ~[paper-1.20.1.jar:git-Paper-84]
        at org.bukkit.Bukkit.createBlockData(Bukkit.java:2215) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at de.diddiz.LogBlock.Updater$MaterialUpdater1_13.<init>(Updater.java:1040) ~[LogBlock.jar:?]
        at de.diddiz.LogBlock.Updater.update(Updater.java:416) ~[LogBlock.jar:?]
        at de.diddiz.LogBlock.LogBlock.onEnable(LogBlock.java:116) ~[LogBlock.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-84]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-84]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.1.jar:git-Paper-84]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.1.jar:git-Paper-84]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-84]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-84]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-84]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-84]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-84]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Block minecraft:cauldron does not have property 'level' at position 19: ...:cauldron[<--[HERE]
[21:36:42 INFO]: [LogBlock] Disabling LogBlock v1.20.0.0-SNAPSHOT (build #183)
```
This is my first time using it, so I could've misconfigured something, but this looks like a pretty unique error. Any ideas?

**Comment by Brokkonaut** [comment]
It looks like you have some very old (pre 1.13) logblock tables in your database. I would recommend to delete them if you do not need them any more. Or please try the latest dev build, it should be fixed now.
