### ISSUE TITLE
1.20.6: ERROR - LogBlock Failed to convert Itemstack to JSON

### ISSUE THREAD

**Issue by andrewkm** [LogBlock/LogBlock#897]
Paper 1.20.6 Build 128
LogBlock compiled against: https://github.com/LogBlock/LogBlock/commit/20e70f91cdd26e7f56a78715ecf0387a0d335490 (2 commits behind)

LogBlock is not showing tool/item information on any items when logblocking containers (Barrel, chest, trapped chest, brewing stands, and shulkerboxes):

This should be a pickaxe with lore, enchantments, and a few other things on it.
![Error](https://i.imgur.com/iEPlHvx.png)

Also this error is running whenever I logblock a container, even when empty.
```
[14:24:41] [Craft Scheduler Thread - 585 - LogBlock/ERROR]: [LogBlock] Failed to convert Itemstack to JSON
java.lang.ClassNotFoundException: org.bukkit.craftbukkit.craftbukkit.inventory.CraftItemStack
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:529) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:508) ~[?:?]
	at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy.java:68) ~[reflection-rewriter-runtime-0.0.1.jar:?]
	at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source) ~[paper-1.20.6.jar:1.20.6-128-3181470]
	at LogBlock.jar/de.diddiz.LogBlock.util.ReflectionUtil.getCraftBukkitClass(ReflectionUtil.java:25) ~[LogBlock.jar:?]
	at LogBlock.jar/de.diddiz.LogBlock.util.BukkitUtils.getItemTag(BukkitUtils.java:678) ~[LogBlock.jar:?]
	at LogBlock.jar/de.diddiz.LogBlock.util.BukkitUtils.toString(BukkitUtils.java:667) ~[LogBlock.jar:?]
	at LogBlock.jar/de.diddiz.LogBlock.BlockChange.getLogMessage(BlockChange.java:151) ~[LogBlock.jar:?]
	at LogBlock.jar/de.diddiz.LogBlock.CommandsHandler.showPage(CommandsHandler.java:446) ~[LogBlock.jar:?]
	at LogBlock.jar/de.diddiz.LogBlock.CommandsHandler.showPage(CommandsHandler.java:428) ~[LogBlock.jar:?]
	at LogBlock.jar/de.diddiz.LogBlock.CommandsHandler$CommandLookup.run(CommandsHandler.java:578) ~[LogBlock.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.6.jar:1.20.6-128-3181470]
	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.6.jar:1.20.6-128-3181470]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.6.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

**Comment by andrewkm** [comment]
Testing against https://github.com/LogBlock/LogBlock/commit/1965d5f985034177c81a0118ea547bf89aa9c8ed

This diamond axe:
![issue](https://i.imgur.com/wNVPv1F.png)

Shows up as such:
![issue](https://i.imgur.com/igHT1EE.png)

**Comment by Brokkonaut** [comment]
Yes, the api is currently broken in 1.20.6 - until it is fixed in the server (or i find a workaround) i had to remove the item info display

**Comment by andrewkm** [comment]
Ah I see. Darn, that was such an incredibly useful feature. :(

**Comment by Brokkonaut** [comment]
I have reported this to spigot, hopefully they will fix it soon

**Comment by andrewkm** [comment]
@Brokkonaut can you perhaps use Adventure instead?
We had one of our plugins break in this way and simply switched to Adventure to display these things.

**Comment by Brokkonaut** [comment]
That would be a huge change for this rather small issue and I would like to avoid it if spigot fixes this soon. But if they won't fix it I might switch to adventure in fthe future.

**Comment by Brokkonaut** [comment]
Waiting for https://github.com/SpigotMC/BungeeCord/issues/3688

**Comment by andrewkm** [comment]
> Waiting for [SpigotMC/BungeeCord#3688](https://github.com/SpigotMC/BungeeCord/issues/3688)

Thanks for the update, fingers crossed. 😄

**Comment by andrewkm** [comment]
@Brokkonaut still no luck? 😞

**Comment by andrewkm** [comment]
@Brokkonaut can we perhaps start looking into adventure? This is likely going to go years without a fix on bungees side and a more permanent fix in log block would be the ideal way forward.

**Comment by Brokkonaut** [comment]
As this takes way longer on the Spigot side than I expected, I will have a look at it when I find time for this. But because it is a rather large in logblock it will take some time.

**Comment by andrewkm** [comment]
> As this takes way longer on the Spigot side than I expected, I will have a look at it when I find time for this. But because it is a rather large in logblock it will take some time.

Any updates on this?
Bungeecord is basically a lost cause.

**Comment by Brokkonaut** [comment]
At least for paper this should work now, for spigot I will fix it when bungee components are updated
